//! The runner's fixed Zig text, emitted into every generated testbench: the
//! Newton solver, the differential gates run at every point, and the
//! `@Vector(NL, f64)` batch family. Nothing here runs in the compiler.
//! LRM: §1, §2.8.3, §3.4.1, §3.6.1.2, §4.2.1.1, §4.3.1, §4.5, §4.5.2, §5.3.1,
//! §5.6.1.2, §5.10.5, §9.4.

const std = @import("std");
const tb = @import("../tb.zig");
const naming = @import("../naming.zig");

/// The testbench's first lines: its imports and `n_u`.
pub const runner_head =
    \\// GENERATED BY VerA — DO NOT EDIT.
    \\// A runnable Verilog-A testbench: the device's own `$strobe` output plus
    \\// the residual and Jacobian at each `//!`-declared operating point.
    \\
    \\const std = @import("std");
    \\const D = @import("device");
    \\const contract = @import("contract");
    \\
    \\const n_u = @typeInfo(D.U).@"enum".fields.len;
    \\
    \\
;

/// The directive-independent runner: host answers, the solver and the gates.
pub const runner_body =
    \\/// §2.8.3/§12.32: this testbench is a HOST, and a host answers for every
    \\/// `$name` the compiler left to a VPI application. There is no application
    \\/// in a `vera --run` build, so this one answers zero — and that answer is
    \\/// the testbench's, written here where a reader can see it, not a value the
    \\/// compiler substituted behind everyone's back.
    \\///
    \\/// ZERO IS NOT A CLAIM ABOUT THE FUNCTION. §12.32.3's own sampnhold listing
    \\/// never initializes `sampler->value` before its first update callback, so
    \\/// the language fixes no value for an unregistered systf and there is
    \\/// nothing here to be wrong about. What a fixture over one of these may
    \\/// assert is what does NOT depend on the value: that the analog block runs
    \\/// straight through the call (§5.3.1), that the residual is still built.
    \\/// Asserting the 0.0 itself would pin this file's choice as if it were the
    \\/// LRM's, and a host-linked conforming tool would then fail the fixture.
    \\///
    \\/// The partials are zero for the same reason and one more: a systf whose
    \\/// derivative were left undefined would put a number nothing computed into
    \\/// the Jacobian, and Newton would chase it.
    \\fn noVpiApp(_: *anyopaque, _: usize, _: []const f64, partials: []f64) f64 {
    \\    @memset(partials, 0);
    \\    return 0;
    \\}
    \\var no_vpi_app: contract.SystfHost = .{ .ctx = undefined, .call = noVpiApp };
    \\
    \\/// §9.12 / IEEE 1364 §17.10: this binary's own command line is the
    \\/// invocation `Instance.plusargs` carries; the harness passes a
    \\/// fixture's `//! plusargs` there.
    \\fn plusargs(init: std.process.Init.Minimal) []const [:0]const u8 {
    \\    const argv = init.args.toSlice(std.heap.page_allocator) catch return &.{};
    \\    return argv[@min(1, argv.len)..];
    \\}
    \\
    \\/// What `contract.validateHost` checks this host by. The testbench is not
    \\/// exempt from it: an exemption for the tool's own host is how a seam stops
    \\/// being tested, and this is the host that runs against every device the
    \\/// torture suite compiles.
    \\pub const iteration_hooks = true;
    \\pub const mutable_eval = true;
    \\/// 4.6.4.3 an array-parameter noise table: this host reads the card's own
    \\/// knots out of `noiseTablePoints`, not the declared defaults that reach
    \\/// `noise_tables`. See `emitNoiseTopology`'s `points=` comparison.
    \\pub const noise_table_points = true;
    \\/// §3.4 this host refuses a card that moves a shape parameter: `shapeCheck`
    \\/// runs after every `derive`.
    \\pub const shape_check = true;
    \\/// The testbench calls `setup` after every card it writes (`tb/runner.zig`).
    \\pub const calls_setup = true;
    \\fn shapeCheck(m: *const D.Model) void {
    \\    if (comptime !@hasDecl(D, "checkShape")) return;
    \\    const name = D.checkShape(m) orelse return;
    \\    std.debug.print("error: LRM 3.4: the model card sets shape parameter `{s}` to a value this device was not compiled for\n", .{name});
    \\    std.process.exit(1);
    \\}
    \\pub fn systf(_: *const D.Model) ?*const contract.SystfHost {
    \\    return &no_vpi_app;
    \\}
    \\comptime {
    \\    contract.validateHost(@This(), D);
    \\}
    \\
    \\/// §3.4.1: "If the type of the parameter is specified as integer or real,
    \\/// and the value assigned to the parameter conflicts with the type of the
    \\/// parameter, the value is converted to the type of the parameter (see
    \\/// 4.2.1.1)." A `//! param` card is written in reals, like any host's, so
    \\/// an integer parameter is handed one here.
    \\///
    \\/// §4.2.1.1: "Real numbers are converted to integers by rounding the real
    \\/// number to the nearest integer, rather than by truncating it ... If the
    \\/// fractional part of the real number is exactly 0.5, it shall be rounded
    \\/// away from zero." `@round` is exactly that tie rule; `lossyCast` then
    \\/// saturates rather than trapping, which is the model card's own guard
    \\/// against a number outside the field's width.
    \\fn cardValue(comptime T: type, v: f64) T {
    \\    return switch (@typeInfo(T)) {
    \\        .int => std.math.lossyCast(T, @round(v)),
    \\        else => v,
    \\    };
    \\}
    \\
    \\/// Index of the unknown a directive named. A miss is a compile error that
    \\/// names the directive, not a runtime surprise.
    \\fn ix(comptime name: []const u8) usize {
    \\    const u = comptime std.meta.stringToEnum(D.U, name) orelse
    \\        @compileError(title ++ ": `//!` names unknown `" ++ name ++ "`, which this module does not have");
    \\    return @intFromEnum(u);
    \\}
    \\
    \\/// A `//! seed` or `//! limit` want: equal to the 12 significant digits a
    \\/// hand derivation writes.
    \\fn near(got: f64, want: f64) bool {
    \\    return @abs(got - want) <= 1e-12 * @abs(want) + 1e-15;
    \\}
    \\
    \\/// Forward-mode dual: value plus one partial per solver unknown. It is the
    \\/// contract's reference family in its dense layout, so the testbench runs
    \\/// the numerics every host is held to (`contract.RefFamily`).
    \\/// `collapsed` is the contract's `collapse_applied` trait: the testbench
    \\/// evaluates with `false`, and `narrowCheck` with both.
    \\const Dual = DualC(false);
    \\fn DualC(comptime collapsed: bool) type {
    \\    return contract.RefFamily(f64, &lane_of, .{ .dense = true, .collapse_applied = collapsed });
    \\}
    \\/// Unknown `u` on lane `u`.
    \\const lane_of = blk: {
    \\    var l: [n_u]u8 = undefined;
    \\    for (&l, 0..) |*e, u| e.* = u;
    \\    break :blk l;
    \\};
    \\/// The value family of the value-only entry points (`updateState`,
    \\/// `noisePsd`, `limit`, `seed`, `collapse`, `derive`, the iteration hooks):
    \\/// the reference family with no lanes, so every path runs the arithmetic
    \\/// `eval` does.
    \\const Val = contract.RefFamily(f64, &(.{contract.no_lane} ** n_u), .{ .dense = true });
    \\
    \\/// A batch family: `V` is NL operating points, one per vector element, and
    \\/// every value is lane-free. Per element it computes what `Val` does:
    \\/// `contract.RefFamily`'s IEEE division, `gm` transcendentals.
    \\/// Instantiated only for a device that declares `batch_ok` — codegen's
    \\/// promise that nothing steers on a `.val()` of an x-dependent value,
    \\/// which is what makes `val` answering element 0 safe.
    \\const NL = 4;
    \\const VF = @Vector(NL, f64);
    \\const Batch = struct {
    \\    pub const V = VF;
    \\    pub fn Of(comptime _: u64) type { return B; }
    \\    pub fn con(c: f64) B { return .{ .v = @splat(c) }; }
    \\    pub fn lift(v: VF) B { return .{ .v = v }; }
    \\    pub fn probe(comptime _: usize, v: VF) B { return .{ .v = v }; }
    \\    pub fn sel(c: B, a: B, b: B) B { return .{ .v = @select(f64, c.v != zeros, a.v, b.v) }; }
    \\    const zeros: VF = @splat(0.0);
    \\    const ones: VF = @splat(1.0);
    \\    const B = struct {
    \\        v: VF,
    \\        fn map1(a: B, comptime f: anytype) B {
    \\            var r: VF = undefined;
    \\            inline for (0..NL) |i| r[i] = f(a.v[i]);
    \\            return .{ .v = r };
    \\        }
    \\        pub fn to(a: B, comptime _: u64) B { return a; }
    \\        pub fn val(a: B) f64 { return a.v[0]; }
    \\        pub fn ddxAt(_: B, comptime _: usize) f64 { return 0.0; }
    \\        pub fn add(a: B, b: B) B { return .{ .v = a.v + b.v }; }
    \\        pub fn sub(a: B, b: B) B { return .{ .v = a.v - b.v }; }
    \\        pub fn neg(a: B) B { return .{ .v = -a.v }; }
    \\        pub fn mul(a: B, b: B) B { return .{ .v = a.v * b.v }; }
    \\        pub fn div(a: B, b: B) B { return .{ .v = a.v / b.v }; }
    \\        pub fn scale(a: B, c: f64) B { return .{ .v = a.v * @as(VF, @splat(c)) }; }
    \\        pub fn addC(a: B, c: f64) B { return .{ .v = a.v + @as(VF, @splat(c)) }; }
    \\        pub fn exp(a: B) B { return map1(a, contract.gm.exp); }
    \\        pub fn log(a: B) B { return map1(a, contract.gm.log); }
    \\        pub fn expm1(a: B) B { return map1(a, contract.gm.expm1); }
    \\        pub fn log1p(a: B) B { return map1(a, std.math.log1p); }
    \\        pub fn sqrt(a: B) B { return .{ .v = @sqrt(a.v) }; }
    \\        pub fn sin(a: B) B { return map1(a, contract.gm.sin); }
    \\        pub fn cos(a: B) B { return map1(a, contract.gm.cos); }
    \\        pub fn tanh(a: B) B { return map1(a, contract.gm.tanh); }
    \\        pub fn sinh(a: B) B { return map1(a, contract.gm.sinh); }
    \\        pub fn cosh(a: B) B { return map1(a, contract.gm.cosh); }
    \\        pub fn atan(a: B) B { return map1(a, contract.gm.atan); }
    \\        pub fn pow(a: B, c: f64) B {
    \\            var r: VF = undefined;
    \\            inline for (0..NL) |i| r[i] = contract.gm.pow(a.v[i], c);
    \\            return .{ .v = r };
    \\        }
    \\        pub fn lt(a: B, b: B) B { return .{ .v = @select(f64, a.v < b.v, ones, zeros) }; }
    \\        pub fn le(a: B, b: B) B { return .{ .v = @select(f64, a.v <= b.v, ones, zeros) }; }
    \\        pub fn eq(a: B, b: B) B { return .{ .v = @select(f64, a.v == b.v, ones, zeros) }; }
    \\    };
    \\};
    \\
    \\comptime {
    \\    contract.checkFamily(Dual);
    \\    contract.checkFamily(Val);
    \\    contract.checkFamily(Batch);
    \\}
    \\
    \\/// The batch gate (ref/SIMD-Strategies T8): one `eval` over NL perturbed
    \\/// copies of the operating point, one per element of `Batch.V`, must agree
    \\/// with NL scalar evals, element by element. Bit equality is the
    \\/// expectation — the same IEEE ops run in the same order per element —
    \\/// with a 1e-12 relative escape for a vectorizer that contracts
    \\/// differently than the scalar pipeline. Silent on success.
    \\fn laneCheck(x: *const [n_u]f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    if (comptime !(@hasDecl(D, "batch_ok") and D.batch_ok)) return;
    \\    var xs: [NL][n_u]f64 = undefined;
    \\    var xv: [n_u]VF = undefined;
    \\    for (0..NL) |k| {
    \\        const s = 1.0 + 1.0e-3 * @as(f64, @floatFromInt(k));
    \\        for (0..n_u) |i| xs[k][i] = x[i] * s + 1.0e-3 * @as(f64, @floatFromInt(k));
    \\    }
    \\    for (0..n_u) |i| {
    \\        // Through an array: a vector index must be comptime-known.
    \\        var lanes: [NL]f64 = undefined;
    \\        for (0..NL) |k| lanes[k] = xs[k][i];
    \\        xv[i] = lanes;
    \\    }
    \\    const rv: [n_u]Batch.B = D.eval(Batch, &xv, model, inst, sim_state);
    \\    const qv: [n_u]Batch.B = if (comptime @hasDecl(D, "q")) qRowsOf(Batch, &xv, model, inst) else undefined;
    \\    for (0..NL) |k| {
    \\        const rs: [n_u]Val = D.eval(Val, &xs[k], model, inst, sim_state);
    \\        for (0..n_u) |i| laneAssert("res", i, k, @as([NL]f64, rv[i].v)[k], rs[i].v);
    \\        if (comptime @hasDecl(D, "q")) {
    \\            const qs = qRowsOf(Val, &xs[k], model, inst);
    \\            for (0..n_u) |i| laneAssert("q", i, k, @as([NL]f64, qv[i].v)[k], qs[i].v);
    \\        }
    \\    }
    \\}
    \\
    \\fn laneAssert(what: []const u8, i: usize, k: usize, a: f64, b: f64) void {
    \\    if (@as(u64, @bitCast(a)) == @as(u64, @bitCast(b))) return;
    \\    if (@abs(a - b) <= 1.0e-12 * @max(@abs(a), @abs(b))) return;
    \\    std.debug.print("lane_check FAIL: {s}[{s}] lane {d}: batch {e} vs scalar {e}\n", .{ what, u_names[i], k, a, b });
    \\    std.process.exit(1);
    \\}
    \\
    \\/// The analysis in force, as every entry point reads it.
    \\var sim_state: contract.SimState = .{};
    \\
    \\/// The fused differential gate: `evalQ` shares ONE core call between the
    \\/// two halves, so it must return exactly what the separate `eval` and `q`
    \\/// return. Same ops, same order, same core — bit equality, no epsilon.
    \\/// A mismatch means the shared-core hoist changed the physics, which is
    \\/// the only way this refactor can be wrong.
    \\fn fusedCheck(x: *const [n_u]f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    if (comptime !@hasDecl(D, "evalQ")) return;
    \\    const both = D.evalQ(Dual, x, model, inst, sim_state);
    \\    const both_res: [n_u]Dual = both.res;
    \\    const both_q: [n_q]Dual = both.q;
    \\    const res: [n_u]Dual = D.eval(Dual, x, model, inst, sim_state);
    \\    const qq: [n_q]Dual = D.q(Dual, x, model, inst, sim_state);
    \\    for (0..n_u) |i| {
    \\        fusedAssert("res", i, both_res[i].v, res[i].v);
    \\        for (0..n_u) |j| fusedAssert("dres", i, both_res[i].d[j], res[i].d[j]);
    \\    }
    \\    // §5.6.1.2 one charge per site (`contract.nQ`), compared as sites.
    \\    for (0..n_q) |k| {
    \\        fusedAssertSite("q", k, both_q[k].v, qq[k].v);
    \\        for (0..n_u) |j| fusedAssertSite("dq", k, both_q[k].d[j], qq[k].d[j]);
    \\    }
    \\}
    \\
    \\/// The structural-Jacobian gate. `jac_pattern`/`q_pattern` tell a host
    \\/// which local matrix entries this device can fill, and the host DELETES
    \\/// the stamps for the rest — it does not even reserve the matrix entry.
    \\/// So a cleared bit with a nonzero partial behind it is a silently missing
    \\/// Jacobian entry, and that is the one way the declaration can be wrong.
    \\/// The converse is legal: the pattern over-approximates on purpose, and a
    \\/// set bit that happens to be zero at this bias costs one stamp.
    \\fn patternCheck(x: *const [n_u]f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    const r = withConst(Dual, D.eval(Dual, x, model, inst, sim_state), model, false);
    \\    if (comptime @hasDecl(D, "jac_pattern")) patAssert("res", D.jac_pattern, &r);
    \\    if (comptime @hasDecl(D, "jac_rows")) rowAssert("res", D.jac_rows, &r);
    \\    if (comptime @hasDecl(D, "q")) {
    \\        const qr = withConst(Dual, qRowsOf(Dual, x, model, inst), model, true);
    \\        if (comptime @hasDecl(D, "q_pattern")) patAssert("q", D.q_pattern, &qr);
    \\        if (comptime @hasDecl(D, "q_rows")) rowAssert("q", D.q_rows, &qr);
    \\    }
    \\}
    \\
    \\/// The constant-column gate, the one a host relies on when it stamps
    \\/// `contract.jacConst(D)` for every column outside `contract.derivReads(D)`
    \\/// (the device reads no lane there). The promise is that such a column
    \\/// enters every row linearly with the exact coefficient the table states,
    \\/// so a unit step on it moves each row by that coefficient: checked on
    \\/// `eval` and on the reactive rows, to the rounding of the rows' own
    \\/// magnitude. A zero step answer matches an absent entry.
    \\///
    \\/// Run under BOTH collapse settings (`collapse_applied` false, then true),
    \\/// stamping a guarded entry exactly when `contract.jacConstApplies` says a
    \\/// host would: its `Model` flag set and the collapse state it names.
    \\///
    \\/// Always on, not behind a flag: a gate that has to be asked for is one
    \\/// somebody forgets.
    \\fn narrowCheck(x: *const [n_u]f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    inline for (.{ false, true }) |collapsed| narrowCheckAs(collapsed, x, model, inst);
    \\}
    \\
    \\fn narrowCheckAs(comptime collapsed: bool, x: *const [n_u]f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    const Dl = DualC(collapsed);
    \\    const r0: [n_u]Dl = D.eval(Dl, x, model, inst, sim_state);
    \\    const q0: [n_u]Dl = if (comptime @hasDecl(D, "q")) qRowsOf(Dl, x, model, inst) else undefined;
    \\    for (0..n_u) |c| {
    \\        if (hasLane(c)) continue;
    \\        var xs = x.*;
    \\        xs[c] += 1.0;
    \\        const r1: [n_u]Dl = D.eval(Dl, &xs, model, inst, sim_state);
    \\        narrowAssert(Dl, "res", false, model, c, &r0, &r1);
    \\        if (comptime @hasDecl(D, "q")) {
    \\            const q1: [n_u]Dl = qRowsOf(Dl, &xs, model, inst);
    \\            narrowAssert(Dl, "q", true, model, c, &q0, &q1);
    \\        }
    \\    }
    \\}
    \\
    \\/// The constant-stamp gate. A device that declares `constant` promises its
    \\/// Jacobian (`g`) or capacitance matrix (`c`) is the same at every x, so a
    \\/// host builds the stamp once: the whole local matrix, `jac_const`
    \\/// included, must come out the same at a second, unrelated bias, to the
    \\/// rounding of its own entries.
    \\fn constCheck(x: *const [n_u]f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    if (comptime !@hasDecl(D, "constant")) return;
    \\    var xs: [n_u]f64 = undefined;
    \\    for (&xs, x, 0..) |*o, v, i| o.* = v * 1.5 - 0.25 - 0.125 * @as(f64, @floatFromInt(i));
    \\    if (comptime D.constant.g) constAssert("res", withConst(Dual, D.eval(Dual, x, model, inst, sim_state), model, false), withConst(Dual, D.eval(Dual, &xs, model, inst, sim_state), model, false));
    \\    if (comptime D.constant.c and @hasDecl(D, "q")) constAssert("q", withConst(Dual, qRowsOf(Dual, x, model, inst), model, true), withConst(Dual, qRowsOf(Dual, &xs, model, inst), model, true));
    \\}
    \\
    \\fn constAssert(what: []const u8, a: [n_u]Dual, b: [n_u]Dual) void {
    \\    for (0..n_u) |i| for (0..n_u) |j| {
    \\        const p = a[i].d[j];
    \\        const q = b[i].d[j];
    \\        if (p == q or @abs(p - q) <= 1e-12 * @max(@abs(p), @abs(q))) continue;
    \\        std.debug.print("const_check FAIL: d{s}[{s}]/dx[{s}] is {e} at one bias and {e} at another, but the device declares it constant\n", .{ what, u_names[i], u_names[j], p, q });
    \\        std.process.exit(1);
    \\    };
    \\}
    \\
    \\/// The family gate. The device's rows on a SPARSE family, whose each value
    \\/// carries only the lanes of the unknowns it may depend on, must be
    \\/// `Dual`'s: every value bit for bit, and every lane `deriv_reads` names
    \\/// equal, a lane the sparse value does not carry reading as zero. Two
    \\/// escapes, neither a tolerance: zeros match whatever their sign, and
    \\/// `Dual`'s NaN may stand where the sparse value has no lane — a dense
    \\/// `0·inf` on a lane that is structurally zero. Above 64 unknowns no mask
    \\/// names a lane and there is nothing to compare.
    \\fn sparseCheck(x: *const [n_u]f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    if (comptime n_u > 64) return;
    \\    const Sp = contract.RefFamily(f64, &lane_of, .{ .dense = false });
    \\    const want: [n_u]Dual = D.eval(Dual, x, model, inst, sim_state);
    \\    const got = D.eval(Sp, x, model, inst, sim_state);
    \\    inline for (0..n_u) |r| sparseAssert("res", u_names[r], got[r], want[r]);
    \\    if (comptime @hasDecl(D, "q")) {
    \\        const wq: [n_q]Dual = D.q(Dual, x, model, inst, sim_state);
    \\        const gq = D.q(Sp, x, model, inst, sim_state);
    \\        inline for (0..n_q) |k| sparseAssert("q site", std.fmt.comptimePrint("{d}", .{k}), gq[k], wq[k]);
    \\        if (comptime @hasDecl(D, "evalQ")) {
    \\            const both = D.evalQ(Sp, x, model, inst, sim_state);
    \\            inline for (0..n_u) |r| sparseAssert("evalQ res", u_names[r], both.res[r], want[r]);
    \\            inline for (0..n_q) |k| sparseAssert("evalQ q site", std.fmt.comptimePrint("{d}", .{k}), both.q[k], wq[k]);
    \\        }
    \\    }
    \\}
    \\
    \\fn sparseAssert(what: []const u8, name: []const u8, got: anytype, want: Dual) void {
    \\    if (@as(u64, @bitCast(got.val())) != @as(u64, @bitCast(want.v))) {
    \\        std.debug.print("sparse_check FAIL: {s}[{s}]: sparse {e} vs dense {e}\n", .{ what, name, got.val(), want.v });
    \\        std.process.exit(1);
    \\    }
    \\    inline for (0..n_u) |u| {
    \\        const carried = (@TypeOf(got).mask >> u) & 1 != 0;
    \\        const g = got.ddxAt(u);
    \\        const w = want.d[u];
    \\        const same = @as(u64, @bitCast(g)) == @as(u64, @bitCast(w)) or (g == 0.0 and w == 0.0) or
    \\            (std.math.isNan(g) and std.math.isNan(w)) or (!carried and std.math.isNan(w));
    \\        if (hasLane(u) and !same) {
    \\            std.debug.print("sparse_check FAIL: d{s}[{s}]/dx[{s}]: sparse {e} vs dense {e}{s}\n", .{
    \\                what, name, u_names[u], g, w, if (carried) "" else " (no sparse lane)",
    \\            });
    \\            std.process.exit(1);
    \\        }
    \\    }
    \\}
    \\
    \\fn hasLane(u: usize) bool {
    \\    return u >= 64 or (contract.derivReads(D) >> @intCast(u)) & 1 != 0;
    \\}
    \\
    \\/// Column `c`'s unit step moved every row by `r1 - r0`; each must be the
    \\/// `jac_const` entry a host would stamp (0 when there is none), to the
    \\/// rounding of the rows' magnitude.
    \\fn narrowAssert(comptime Dl: type, what: []const u8, react: bool, model: *const D.Model, c: usize, r0: *const [n_u]Dl, r1: *const [n_u]Dl) void {
    \\    for (0..n_u) |i| {
    \\        var k: f64 = 0.0;
    \\        inline for (comptime contract.jacConst(D)) |e| {
    \\            if (@intFromEnum(e.row) == i and @intFromEnum(e.col) == c and
    \\                contract.jacConstApplies(D, e, model, Dl.collapse_applied)) k = if (react) e.c else e.g;
    \\        }
    \\        const moved = r1[i].v - r0[i].v;
    \\        const tol = 1e-9 * @max(@abs(r0[i].v), @abs(r1[i].v)) + 1e-300;
    \\        if (@abs(moved - k) <= tol) continue;
    \\        std.debug.print("narrow_check FAIL: d{s}[{s}]/dx[{s}]: a unit step moves the row by {e}, jac_const says {e}{s}\n", .{
    \\            what, u_names[i], u_names[c], moved, k, if (Dl.collapse_applied) " [collapse applied]" else "",
    \\        });
    \\        std.process.exit(1);
    \\    }
    \\}
    \\
    \\fn patAssert(what: []const u8, pat: [n_u]u64, r: *const [n_u]Dual) void {
    \\    for (0..n_u) |i| for (0..n_u) |j| {
    \\        if (r[i].d[j] == 0.0) continue;
    \\        if ((pat[i] >> @intCast(j)) & 1 != 0) continue;
    \\        std.debug.print("pattern_check FAIL: d{s}[{s}]/dx[{s}] = {e} is outside the declared pattern\n", .{ what, u_names[i], u_names[j], r[i].d[j] });
    \\        std.process.exit(1);
    \\    };
    \\}
    \\
    \\/// The WRITTEN-ROW gate. A host drops a row outside `jac_rows`/`q_rows`
    \\/// entirely — no residual stamp, no charge-tape entry — so a clear bit
    \\/// with anything but a hard zero behind it is a term that vanishes from
    \\/// the netlist with no diagnostic. This is the check that fails if
    \\/// codegen ever writes `res[ru]` without going through `patRow`, and the
    \\/// value, not the derivative, is what it looks at: `isource` writes rows
    \\/// whose every partial is zero.
    \\fn rowAssert(what: []const u8, rows: u64, r: *const [n_u]Dual) void {
    \\    for (0..n_u) |i| {
    \\        if ((rows >> @intCast(i)) & 1 != 0) continue;
    \\        if (r[i].v == 0.0) continue;
    \\        std.debug.print("row_check FAIL: {s}[{s}] = {e} but the row is declared never written\n", .{ what, u_names[i], r[i].v });
    \\        std.process.exit(1);
    \\    }
    \\}
    \\
    \\fn fusedAssert(what: []const u8, i: usize, a: f64, b: f64) void {
    \\    if (@as(u64, @bitCast(a)) == @as(u64, @bitCast(b))) return;
    \\    std.debug.print("fused_check FAIL: {s}[{s}]: evalQ {e} vs split {e}\n", .{ what, u_names[i], a, b });
    \\    std.process.exit(1);
    \\}
    \\
    \\fn fusedAssertSite(what: []const u8, k: usize, a: f64, b: f64) void {
    \\    if (@as(u64, @bitCast(a)) == @as(u64, @bitCast(b))) return;
    \\    std.debug.print("fused_check FAIL: {s} site {d}: evalQ {e} vs split {e}\n", .{ what, k, a, b });
    \\    std.process.exit(1);
    \\}
    \\
    \\/// §5.6.1.2 how many charges `q` returns, and the rows they stamp: `q`
    \\/// returns one per `ddt` site and `contract.qRows` sums them into the
    \\/// reactive residual's rows through `q_stamps`.
    \\const n_q = contract.nQ(D);
    \\
    \\/// For a family whose `Of(_)` is one type (all of this file's).
    \\fn qRowsOf(comptime Sc: type, x: *const [n_u]Sc.V, model: *const D.Model, inst: contract.InstancePtr(D)) [n_u]Sc.Of(0) {
    \\    return contract.qRows(D, Sc, D.q(Sc, x, model, inst, sim_state));
    \\}
    \\
    \\/// The whole local Jacobian a host assembles: the device's lanes on the
    \\/// columns in `deriv_reads`, `jac_const` on the rest (`g` of `eval`, `c`
    \\/// of the reactive rows).
    \\fn withConst(comptime Dl: type, rows: [n_u]Dl, model: *const D.Model, react: bool) [n_u]Dl {
    \\    var out = rows;
    \\    inline for (comptime contract.jacConst(D)) |e| {
    \\        if (contract.jacConstApplies(D, e, model, Dl.collapse_applied))
    \\            out[@intFromEnum(e.row)].d[@intFromEnum(e.col)] = if (react) e.c else e.g;
    \\    }
    \\    return out;
    \\}
    \\
    \\/// §4.5.2 accepted-step bookkeeping. `void` for a module with no stateful
    \\/// operator, which is most of them — codegen emits the state machine only
    \\/// when one is present.
    \\const State = if (@hasDecl(D, "updateState") and @hasDecl(D, "initState")) D.State else void;
    \\
    \\fn newState(model: *const D.Model, inst: *D.Instance) State {
    \\    if (State == void) return {};
    \\    return D.initState(model, inst);
    \\}
    \\
    \\/// Commit the accepted solution, exactly as a transient solver does after
    \\/// a converged step. `eval` READS the history out of `Instance`; this is the
    \\/// only thing that ever writes it, so without this call every §4.5 operator
    \\/// would answer from zero history at every time point and the transcript
    \\/// would claim more than it proves.
    \\fn step(model: *const D.Model, inst: *D.Instance, x: *const [n_u]f64, state: *State) void {
    \\    if (State == void) return;
    \\    _ = D.updateState(Val, model, inst, x.*, state, sim_state);
    \\}
    \\
    \\/// Iteration history advances independently of accepted-time operators.
    \\/// §5.6.1.2 the accepted step's CHARGE, which is the other operand of the
    \\/// backward-Euler difference `solve` forms at the next time point. Taken
    \\/// before `step`, so it is the q of the state `eval` saw while this point
    \\/// was being solved and not of the history `updateState` is about to write.
    \\var q_prev: [n_u]f64 = @splat(0.0);
    \\
    \\fn commitCharge(model: *const D.Model, inst: *D.Instance, x: *const [n_u]f64) void {
    \\    if (comptime !@hasDecl(D, "q")) return;
    \\    const qq = qRowsOf(Dual, x, model, inst);
    \\    for (0..n_u) |i| q_prev[i] = qq[i].v;
    \\}
    \\
    \\/// `acceptQ` is `q` then `updateState` from one core evaluation, so its
    \\/// charge must be `q`'s to the bit, lanes included. Run on copies: the
    \\/// transcript keeps advancing through `updateState` exactly as before.
    \\fn acceptCheck(model: *const D.Model, inst: *const D.Instance, x: *const [n_u]f64, state: *const State) void {
    \\    if (comptime !@hasDecl(D, "acceptQ") or State == void) return;
    \\    var iw = inst.*;
    \\    const want: [n_q]Dual = D.q(Dual, x, model, &iw, sim_state);
    \\    var ic = inst.*;
    \\    var sc = state.*;
    \\    const got: [n_q]Dual = D.acceptQ(Dual, x, model, &ic, &sc, sim_state);
    \\    for (0..n_q) |i| {
    \\        if (@as(u64, @bitCast(got[i].v)) == @as(u64, @bitCast(want[i].v)) and
    \\            std.mem.eql(u8, std.mem.asBytes(&got[i].d), std.mem.asBytes(&want[i].d))) continue;
    \\        std.debug.print("acceptQ FAIL: q site {d} {e} vs q() {e}\n", .{ i, got[i].v, want[i].v });
    \\        std.process.exit(1);
    \\    }
    \\}
    \\
    \\fn stepPost(model: *const D.Model, inst: *D.Instance, x: *const [n_u]f64, state: *State, solved: bool) void {
    \\    acceptCheck(model, inst, x, state);
    \\    commitCharge(model, inst, x);
    \\    if (!solved) {
    \\        // Forced-point fixtures sample both lifetimes, and a forced point
    \\        // is one Newton iteration of an unbroken solve. Both updates read
    \\        // the same evaluated state, even when their inputs depend on one
    \\        // another; `limiter_previous` is the iteration hook's.
    \\        defer sim_state.iteration +|= 1;
    \\        if (@hasDecl(D, "advanceIteration")) {
    \\            var next = inst.*;
    \\            D.advanceIteration(Val, model, &next, x.*, sim_state);
    \\            step(model, inst, x, state);
    \\            if (@hasField(D.Instance, "limiter_previous")) inst.limiter_previous = next.limiter_previous;
    \\            return;
    \\        }
    \\    }
    \\    step(model, inst, x, state);
    \\}
    \\
    \\const u_names = blk: {
    \\    const f = @typeInfo(D.U).@"enum".fields;
    \\    var names: [f.len][]const u8 = undefined;
    \\    for (f, 0..) |e, i| names[i] = e.name;
    \\    break :blk names;
    \\};
    \\
    \\/// One operating point: the bias, then whatever the model prints, then the
    \\/// residual it stamps and the Jacobian the solver would see.
    \\fn point(n: usize, x: *const [n_u]f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    std.debug.print("--- point {d} ---\n", .{n});
    \\    for (0..n_u) |i| std.debug.print("  x[{s}] = {e:.6}\n", .{ u_names[i], x[i] });
    \\    if (sim_state.t != 0.0 or sim_state.dt != 0.0)
    \\        std.debug.print("  t = {e:.6}  dt = {e:.6}\n", .{ sim_state.t, sim_state.dt });
    \\
    \\    // §5.10.5 the host's breakpoint hook, when codegen emitted one (only a
    \\    // module with a `timer` has one). Printed OUTSIDE `print_residual`
    \\    // because it is not part of the residual and the fixtures that test it
    \\    // are `print none`; `@hasDecl` keeps every other transcript unchanged.
    \\    if (@hasDecl(D, "nextBreakpoint")) {
    \\        if (D.nextBreakpoint(model, sim_state.t)) |bp|
    \\            std.debug.print("  next_bp = {e:.6}\n", .{bp})
    \\        else
    \\            std.debug.print("  next_bp = none\n", .{});
    \\    }
    \\
    \\    // Differential gates — silent on success, fail the run loudly.
    \\    laneCheck(x, model, inst);
    \\    fusedCheck(x, model, inst);
    \\    patternCheck(x, model, inst);
    \\    narrowCheck(x, model, inst);
    \\    sparseCheck(x, model, inst);
    \\    constCheck(x, model, inst);
    \\
    \\    // §9.4 the model's own transcript. Runs BEFORE the residual print so a
    \\    // fixture's `$strobe` lines sit next to the bias that produced them.
    \\    if (@hasDecl(D, "display")) D.display(Dual, x, model, inst, sim_state);
    \\    if (!print_residual) return;
    \\
    \\    const res = withConst(Dual, D.eval(Dual, x, model, inst, sim_state), model, false);
    \\    for (0..n_u) |i| {
    \\        std.debug.print("  res[{s}] = {e:.6}\n", .{ u_names[i], res[i].v });
    \\        for (0..n_u) |j| {
    \\            if (res[i].d[j] == 0.0) continue;
    \\            std.debug.print("    d res[{s}]/d x[{s}] = {e:.6}\n", .{ u_names[i], u_names[j], res[i].d[j] });
    \\        }
    \\    }
    \\    // §5.6.1.2 the reactive half, when the model has one. Its derivative is
    \\    // the capacitance/inductance matrix the host multiplies by d/dt.
    \\    if (@hasDecl(D, "q")) {
    \\        const qq = withConst(Dual, qRowsOf(Dual, x, model, inst), model, true);
    \\        for (0..n_u) |i| {
    \\            if (qq[i].v == 0.0 and allZero(qq[i].d)) continue;
    \\            std.debug.print("  q[{s}] = {e:.6}\n", .{ u_names[i], qq[i].v });
    \\            for (0..n_u) |j| {
    \\                if (qq[i].d[j] == 0.0) continue;
    \\                std.debug.print("    d q[{s}]/d x[{s}] = {e:.6}\n", .{ u_names[i], u_names[j], qq[i].d[j] });
    \\            }
    \\        }
    \\    }
    \\}
    \\
    \\fn allZero(v: [n_u]f64) bool {
    \\    for (v) |e| if (e != 0.0) return false;
    \\    return true;
    \\}
    \\
    \\/// Pin an unknown at the value a `//! bias`, `//! sweep` or `//! wave` line
    \\/// gave it: the INITIAL GUESS Newton starts from, and the CONSTRAINT row it
    \\/// keeps. Both, from one directive, because a directive that names a value
    \\/// for an unknown is saying the host drives it.
    \\fn set(x: *[n_u]f64, forced: *[n_u]?f64, comptime name: []const u8, v: f64) void {
    \\    x[ix(name)] = v;
    \\    forced[ix(name)] = v;
    \\}
    \\
    \\/// §3.6.1.2 `abstol` — "the largest signal value that can be safely
    \\/// ignored" — per unknown, which is the absolute half of Newton's stopping
    \\/// test. The device declares it (codegen reads it off the net's discipline,
    \\/// §3.6.2.3 override included); the fallback is annex D's own defaults for
    \\/// `Voltage` and `Current`, for a hand-written device that declares neither
    \\/// table.
    \\const u_abstol: [n_u]f64 = if (@hasDecl(D, "u_abstol")) D.u_abstol else blk: {
    \\    var a: [n_u]f64 = @splat(1e-6);
    \\    if (@hasDecl(D, "u_kinds")) for (D.u_kinds, 0..) |k, i| {
    \\        if (k != .voltage) a[i] = 1e-12;
    \\    };
    \\    break :blk a;
    \\};
    \\
    \\/// The relative half. Tighter than a circuit simulator's default reltol
    \\/// because a fixture asserts a digit derived from the LRM, not a waveform:
    \\/// the systems here are small enough that the extra decades cost nothing.
    \\const solve_reltol = 1e-12;
    \\
    \\/// A cap, not a budget. Every fixture system converges in one step (linear)
    \\/// or a handful; reaching this means the iteration is not converging, and
    \\/// that has to be LOUD — see the exit below.
    \\const solve_max_iter = 100;
    \\
    \\/// §5.6 THE SOLVE, and it is a solve.
    \\///
    \\/// Verilog-A semantics are defined AT A SOLUTION of the nodal equations,
    \\/// never at an arbitrary point. §5.6.7's indirect contribution is a
    \\/// CONSTRAINT the simulator satisfies rather than an assignment — there is
    \\/// no way to express it by evaluating anything — and §5.4.2.2's "the
    \\/// potential of a source branch may be read" is a question about what the
    \\/// solver settled on. A harness that wrote `//! bias` into x[] and stopped
    \\/// could only ever hand a fixture back the number the harness itself just
    \\/// wrote.
    \\///
    \\/// So: Newton-Raphson on the residual the device stamps, with the Jacobian
    \\/// the forward-mode `Dual` above already carries. Dense LU with partial
    \\/// pivoting — a fixture's system is under ~10 unknowns, so a sparse
    \\/// factorisation or an ordering heuristic would be code with nothing to do.
    \\///
    \\/// ONE RULE BEYOND TEXTBOOK NEWTON, and it is what makes an isolated device
    \\/// solvable at all. A .va compiled alone is NOT a circuit. `I(p,n) <+ 0.0`
    \\/// stamps two identically-zero rows; a two-terminal module that never
    \\/// references ground leaves its common mode undetermined however nonlinear
    \\/// it is. Those are free directions of the device's own equations, not
    \\/// solver failures — a host pins them by CONNECTING the device to
    \\/// something. So a column with no usable pivot takes dx = 0 and its unknown
    \\/// HOLDS the operating point the `//!` lines declared, which is exactly the
    \\/// behaviour this harness had before it could solve at all. Convergence is
    \\/// then judged on the unknowns the system does determine, and only those.
    \\///
    \\/// ponytail: no gmin stepping, no source stepping, no continuation. Every
    \\/// system in the suite converges from the declared guess. Add the minimum
    \\/// and name it here if one ever does not.
    \\///
    \\/// §5.6.1.2's reactive half is folded in by BACKWARD EULER, because a
    \\/// fixture finally needed a transient solve: §5.4.3's port current is the
    \\/// whole of what the module stamps at the port, charge included, and
    \\/// `res[flow(<p>)] = x − res[p]` alone can only ever hand back the
    \\/// conduction half (ch05_analog_behavior/a02_06). So the row Newton sees is
    \\///
    \\///     eval(x) + (q(x) − q_prev) / dt
    \\///
    \\/// with `q_prev` the charge of the last accepted point (`commitCharge`).
    \\///
    \\/// ponytail: first order, fixed step, no LTE control and no step rejection
    \\/// — `//! time` states the steps and the suite asserts values a clause
    \\/// derives, not a waveform's accuracy. Trapezoidal or gear-2 is the upgrade
    \\/// if a fixture ever asserts a number the Euler truncation error moves.
    \\///
    \\/// dt = 0 is the DC point that opens a transient (`renderRunner` gives the
    \\/// first time step dt = 0 for exactly this reason, §4.5.3), and there the
    \\/// difference is undefined and the charge contributes nothing — so that
    \\/// point is still the resistive solve it always was.
    \\fn solve(x: *[n_u]f64, forced: *const [n_u]?f64, model: *const D.Model, inst: *D.Instance) bool {
    \\    // Nothing to determine: every unknown is one a `//!` line named, or the
    \\    // reference the harness ties the rest to without `//! solve`. x already
    \\    // holds the answer. Returning here is not only the cheap path — it is
    \\    // what keeps a `//! print none` fixture evaluated exactly as often as it
    \\    // was before there was a solver, so no §9.4 transcript moves.
    \\    for (forced) |f| {
    \\        if (f == null) break;
    \\    } else return false;
    \\    sim_state.iteration = 1;
    \\    var previous = x.*;
    \\    var worst: usize = 0;
    \\    var worst_dx: f64 = 0.0;
    \\    var iter: usize = 0;
    \\    while (iter < solve_max_iter) : (iter += 1) {
    \\        if (iter != 0) {
    \\            if (@hasDecl(D, "advanceIteration")) D.advanceIteration(Val, model, inst, previous, sim_state);
    \\            sim_state.iteration +|= 1;
    \\        }
    \\        previous = x.*;
    \\        var r = withConst(Dual, D.eval(Dual, x, model, inst, sim_state), model, false);
    \\        // §5.6.1.2 backward Euler — see the header. Value and derivative
    \\        // both, so the capacitance matrix reaches the Jacobian too.
    \\        if (comptime @hasDecl(D, "q")) if (sim_state.dt > 0.0) {
    \\            const qq = withConst(Dual, qRowsOf(Dual, x, model, inst), model, true);
    \\            for (0..n_u) |i| {
    \\                r[i].v += (qq[i].v - q_prev[i]) / sim_state.dt;
    \\                for (0..n_u) |j| r[i].d[j] += qq[i].d[j] / sim_state.dt;
    \\            }
    \\        };
    \\        var a: [n_u][n_u]f64 = undefined;
    \\        var b: [n_u]f64 = undefined;
    \\        var scale: f64 = 0.0;
    \\        for (0..n_u) |i| {
    \\            if (forced[i]) |v| {
    \\                // The host drives this one, so its row is the constraint and
    \\                // not the device's KCL. Written as a Newton row (1·dx =
    \\                // v - x) rather than by assignment, so the value survives
    \\                // elimination against every other row exactly.
    \\                a[i] = @splat(0.0);
    \\                a[i][i] = 1.0;
    \\                b[i] = v - x[i];
    \\            } else {
    \\                a[i] = r[i].d;
    \\                b[i] = -r[i].v;
    \\                // A forced column's dx is known, so it moves to the right-
    \\                // hand side. Left in, a large coupling (a charge over dt)
    \\                // wins that column's pivot from the constraint row, and the
    \\                // free column it displaces can fall under `eps`.
    \\                for (0..n_u) |j| if (forced[j]) |v| {
    \\                    b[i] -= a[i][j] * (v - x[j]);
    \\                    a[i][j] = 0.0;
    \\                };
    \\            }
    \\            for (a[i]) |e| scale = @max(scale, @abs(e));
    \\        }
    \\        var dx: [n_u]f64 = undefined;
    \\        var solved: [n_u]bool = undefined;
    \\        luSolve(&a, &b, &dx, &solved, scale);
    \\        var settled = true;
    \\        worst_dx = 0.0;
    \\        for (0..n_u) |i| {
    \\            if (!solved[i]) continue;
    \\            const tol = u_abstol[i] + solve_reltol * @abs(x[i]);
    \\            if (@abs(dx[i]) > tol and @abs(dx[i]) > worst_dx) {
    \\                settled = false;
    \\                worst_dx = @abs(dx[i]);
    \\                worst = i;
    \\            }
    \\        }
    \\        for (0..n_u) |i| x[i] += dx[i];
    \\        const can_converge = if (@hasDecl(D, "checkConvergence")) D.checkConvergence(Val, model, inst, x.*, sim_state) else true;
    \\        if (settled and can_converge) return true;
    \\    }
    \\    // A testbench that does not converge must FAIL, loudly and by exit
    \\    // status, naming the unknown that would not settle. Falling through and
    \\    // letting the model assert against a half-iterated x would report a
    \\    // conformance verdict on arithmetic nobody solved.
    \\    std.debug.print(
    \\        "{s}: did not converge after {d} Newton iterations: x[{s}] still moving {e:.6} per step, tolerance {e:.6}\n",
    \\        .{ title, solve_max_iter, u_names[worst], worst_dx, u_abstol[worst] + solve_reltol * @abs(x[worst]) },
    \\    );
    \\    std.process.exit(1);
    \\}
    \\
    \\/// Dense LU with partial pivoting, rank-revealing exactly as far as `solve`
    \\/// needs: `solved[k]` is false for a column with no usable pivot, and
    \\/// `dx[k]` is then 0. Row `k` of the echelon form lives at `perm[…]`, so
    \\/// nothing is physically moved.
    \\fn luSolve(
    \\    a: *[n_u][n_u]f64,
    \\    b: *[n_u]f64,
    \\    dx: *[n_u]f64,
    \\    solved: *[n_u]bool,
    \\    scale: f64,
    \\) void {
    \\    // "Usable" is relative to the largest entry in the whole system: a
    \\    // structurally absent coupling and one that cancelled to rounding are
    \\    // both absence of information, and treating the second as a pivot is
    \\    // how a solver invents a 1e17 node voltage.
    \\    const eps = 1e-14 * scale;
    \\    var pivot: [n_u]usize = @splat(0);
    \\    var perm: [n_u]usize = undefined;
    \\    for (0..n_u) |i| perm[i] = i;
    \\    var rows: usize = 0; // rows consumed by a pivot so far
    \\    for (0..n_u) |k| {
    \\        var best = rows;
    \\        var best_v: f64 = -1.0;
    \\        for (rows..n_u) |i| {
    \\            const v = @abs(a[perm[i]][k]);
    \\            if (v > best_v) {
    \\                best_v = v;
    \\                best = i;
    \\            }
    \\        }
    \\        if (best_v <= eps) {
    \\            solved[k] = false;
    \\            continue;
    \\        }
    \\        std.mem.swap(usize, &perm[rows], &perm[best]);
    \\        const p = perm[rows];
    \\        pivot[k] = p;
    \\        solved[k] = true;
    \\        for (rows + 1..n_u) |i| {
    \\            const qr = perm[i];
    \\            if (a[qr][k] == 0.0) continue;
    \\            const f = a[qr][k] / a[p][k];
    \\            for (k..n_u) |j| a[qr][j] -= f * a[p][j];
    \\            b[qr] -= f * b[p];
    \\        }
    \\        rows += 1;
    \\    }
    \\    // Back-substitution over the pivoted columns, highest first. A free
    \\    // column contributes nothing to any row above it, because its dx is 0.
    \\    var k = n_u;
    \\    while (k > 0) {
    \\        k -= 1;
    \\        if (!solved[k]) {
    \\            dx[k] = 0.0;
    \\            continue;
    \\        }
    \\        const p = pivot[k];
    \\        var s = b[p];
    \\        for (k + 1..n_u) |j| s -= a[p][j] * dx[j];
    \\        dx[k] = s / a[p][k];
    \\    }
    \\}
    \\
    \\
;

/// `renderVpiLib`'s fixed half: the state one analysis lives in and the
/// exports that do not depend on the directives.
pub const vpi_lib_body =
    \\var g_model: D.Model = .{};
    \\var g_inst: D.Instance = .{};
    \\var g_x: [n_u]f64 = @splat(0.0);
    \\var g_forced: [n_u]?f64 = @splat(null);
    \\var g_state: State = undefined;
    \\var g_solved: bool = false;
    \\/// §12.32 the host's analog system function calls, through a C
    \\/// function: `contract.SystfHost.call` is a Zig-ABI pointer taking slices,
    \\/// which may not cross a shared-library boundary. The library keeps the
    \\/// `SystfHost` the device calls and forwards each call.
    \\const HostCall = *const fn (usize, [*]const f64, usize, [*]f64) callconv(.c) f64;
    \\var host_call: ?HostCall = null;
    \\fn viaHost(_: *anyopaque, k: usize, args: []const f64, partials: []f64) f64 {
    \\    return host_call.?(k, args.ptr, args.len, partials.ptr);
    \\}
    \\var host_systf: contract.SystfHost = .{ .ctx = undefined, .call = viaHost };
    \\const n_systf = if (@hasDecl(D, "systf_calls")) D.systf_calls.len else 0;
    \\export fn vera_vpi_n_systf() callconv(.c) usize {
    \\    return n_systf;
    \\}
    \\/// `systf_calls[k].name`, which is not NUL-terminated.
    \\export fn vera_vpi_systf_name(k: usize, len: *usize) callconv(.c) [*]const u8 {
    \\    if (comptime n_systf == 0) unreachable;
    \\    len.* = D.systf_calls[k].name.len;
    \\    return D.systf_calls[k].name.ptr;
    \\}
    \\
    \\/// A `//! wave` value between the declared times, as the mixed runner
    \\/// reads it: one value per `//! time` point, linear between them.
    \\fn pwl(values: []const f64, t: f64) f64 {
    \\    var k: usize = 0;
    \\    while (k + 1 < times.len and times[k + 1] <= t) k += 1;
    \\    const v0 = values[@min(k, values.len - 1)];
    \\    if (k + 1 >= times.len or k + 1 >= values.len) return v0;
    \\    return v0 + (values[k + 1] - v0) * (t - times[k]) / (times[k + 1] - times[k]);
    \\}
    \\
    \\export fn vera_vpi_systf(h: ?HostCall) callconv(.c) void {
    \\    host_call = h;
    \\}
    \\export fn vera_vpi_n_u() callconv(.c) usize {
    \\    return n_u;
    \\}
    \\/// The solution the last `vera_vpi_solve` reached, tentative or accepted.
    \\export fn vera_vpi_x() callconv(.c) [*]const f64 {
    \\    return &g_x;
    \\}
    \\/// §5.6.1.3/§9.4.6: the last solution is final. The model's own §9.4
    \\/// output for it, then the accepted-step bookkeeping every §4.5 operator
    \\/// reads its history from.
    \\export fn vera_vpi_accept() callconv(.c) void {
    \\    if (@hasDecl(D, "display")) D.display(Dual, &g_x, &g_model, &g_inst, sim_state);
    \\    stepPost(&g_model, &g_inst, &g_x, &g_state, g_solved);
    \\}
    \\const n_rows = if (@hasDecl(D, "vpiContribs")) D.vpi_contrib_access.len else 0;
    \\export fn vera_vpi_n_rows() callconv(.c) usize {
    \\    return n_rows;
    \\}
    \\/// Row k's shape: access (0 potential, 1 flow), the terminal unknowns and
    \\/// a potential source's flow unknown, -1 for ground / none.
    \\export fn vera_vpi_row(k: usize, out: *[4]i32) callconv(.c) void {
    \\    if (comptime n_rows == 0) return;
    \\    out.* = .{ D.vpi_contrib_access[k], D.vpi_contrib_hi[k], D.vpi_contrib_lo[k], D.vpi_contrib_flow_u[k] };
    \\}
    \\/// Every row's (resistive, reactive) value at the current x, into `out`
    \\/// (2 per row).
    \\export fn vera_vpi_rows(out: [*]f64) callconv(.c) void {
    \\    if (comptime n_rows == 0) return;
    \\    const v = D.vpiContribs(Dual, &g_x, &g_model, &g_inst, sim_state);
    \\    for (v, 0..) |r, k| {
    \\        out[2 * k] = r[0];
    \\        out[2 * k + 1] = r[1];
    \\    }
    \\}
    \\
;

/// The mixed-signal runner's fixed text (`renderMixed`): the digital half, the
/// coordinator call, and the two conversions the adapter needs. Only a
/// testbench built with `BuildOptions.mixed` imports `sim` and `diag`.
pub const mixed_body =
    \\const sim = @import("sim");
    \\const diag = @import("diag");
    \\const Timescale = @typeInfo(@FieldType(sim.digital.Mixed, "timescale")).optional.child;
    \\
    \\/// VAMS §7.3.1 Table 7-1: a bit grouping, a net and an `integer` all reach
    \\/// the continuous context as an integer. §7.3.2: "It is an error if these
    \\/// operands return x or z bit values when solved" — and a solve is exactly
    \\/// where this is read, so an x or z bit fails the run by name.
    \\fn mixedInput(dig: *sim.digital.Run, slot: u32, name: []const u8) f64 {
    \\    // Table 7-1's real row: "no conversion".
    \\    if (dig.reals.contains(slot)) return @bitCast(dig.values[slot].values()[0]);
    \\    const v = dig.values[slot].asInt() orelse {
    \\        std.debug.print("{s}: FAIL §7.3.2: the discrete input `{s}` holds an x or z bit when the analog block reads it\n", .{ title, name });
    \\        std.process.exit(1);
    \\    };
    \\    return @floatFromInt(v);
    \\}
    \\
    \\/// The potential of node `n1` (minus `n2`) in `x`; a name that is no
    \\/// unknown of the device is ground.
    \\fn potential(x: *const [n_u]f64, n1: []const u8, n2: ?[]const u8) !f64 {
    \\    return nodeValue(x, n1) - if (n2) |b| nodeValue(x, b) else 0.0;
    \\}
    \\fn nodeValue(x: *const [n_u]f64, name: []const u8) f64 {
    \\    for (u_names, 0..) |u, i| if (std.mem.eql(u8, u, name)) return x[i];
    \\    return 0.0;
    \\}
    \\
    \\/// A `//! wave`, piecewise linear over the declared `//! time`s. At a
    \\/// declared point it is the fixed-grid runner's value, a short list holds its
    \\/// last entry, and an inserted point between two declared ones interpolates.
    \\fn pwl(values: []const f64, t: f64) f64 {
    \\    var k: usize = 0;
    \\    while (k + 1 < times.len and times[k + 1] <= t) k += 1;
    \\    const v0 = values[@min(k, values.len - 1)];
    \\    if (k + 1 >= times.len or k + 1 >= values.len) return v0;
    \\    return v0 + (values[k + 1] - v0) * (t - times[k]) / (times[k + 1] - times[k]);
    \\}
    \\
    \\/// A digital name the device reads, and the `Model` field it arrives in.
    \\const Port = struct { name: []const u8, field: []const u8, xz: ?[]const u8 = null };
    \\/// §8.5 an explicit D2A term: the event it waits on, and its `Model` flag.
    \\const EventPort = struct { name: []const u8, edge: @FieldType(sim.digital.D2aSite, "edge"), field: []const u8 };
    \\
    \\fn setField(model: *D.Model, comptime field: []const u8, v: anytype) void {
    \\    @field(model, field) = std.math.lossyCast(@TypeOf(@field(model, field)), v);
    \\}
    \\
    \\fn mixedSlot(dig: *sim.digital.Run, name: []const u8) u32 {
    \\    return dig.slotOf(name) orelse {
    \\        std.debug.print("{s}: FAIL the digital half holds no `{s}` for the analog block to read\n", .{ title, name });
    \\        std.process.exit(1);
    \\    };
    \\}
    \\
    \\fn mixedFail(bag: *diag.Bag, e: anyerror) noreturn {
    \\    var buf = std.Io.Writer.Allocating.init(std.heap.page_allocator);
    \\    diag.render(bag, &buf.writer, .{ .explain_hint = false, .summary = false }) catch {};
    \\    std.debug.print("{s}FAIL {s}: the digital half did not run: {t}\n", .{ buf.written(), title, e });
    \\    std.process.exit(1);
    \\}
    \\
    \\/// One analysis: elaborate the digital half afresh, bind the inputs, and
    \\/// let `sim.mixed.run` own the global time.
    \\fn runMixed(model: *D.Model, inst: *D.Instance, x: *[n_u]f64, forced: *[n_u]?f64, state: *State, n: *usize) void {
    \\    var arena_state = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    \\    defer arena_state.deinit();
    \\    const arena = arena_state.allocator();
    \\    var bag = diag.Bag.init(arena);
    \\    bag.setSingleFile(title, mixed_source) catch {};
    \\    var dout = std.Io.Writer.Allocating.init(arena);
    \\    var dig = sim.digital.elaborate(arena, mixed_source, .{ .mixed = .{ .top = mixed_top, .timescale = mixed_timescale, .inserts = &mixed_inserts, .reads = &mixed_reads, .params = &mixed_params } }, &bag, &dout.writer) catch |e| mixedFail(&bag, e);
    \\    // VAMS §9.5.1.2 one descriptor table for both contexts: the device's,
    \\    // when it has one, so a descriptor either opens names one file.
    \\    if (comptime contract.fileIo(D)) |f| dig.file_io = f;
    \\    var a: Analog = .{ .model = model, .inst = inst, .x = x, .forced = forced, .state = state, .dout = &dout, .n = n, .slots = undefined, .snap_slots = undefined, .dig = &dig, .a2d_slots = undefined };
    \\    inline for (a2d_ports, 0..) |p, i| a.a2d_slots[i] = mixedSlot(&dig, p.name);
    \\    // §8.4.3.2: an unguarded read makes the block implicitly sensitive.
    \\    inline for (input_ports, 0..) |p, i| {
    \\        a.slots[i] = mixedSlot(&dig, p.name);
    \\        dig.watchAnalog(a.slots[i]);
    \\    }
    \\    inline for (snap_ports, 0..) |p, i| a.snap_slots[i] = mixedSlot(&dig, p.name);
    \\    inline for (event_ports, 0..) |p, k| dig.watchEvent(mixedSlot(&dig, p.name), p.edge, k) catch |e| mixedFail(&bag, e);
    \\    const tick = if (mixed_timescale) |ts| ts.precision else 1.0;
    \\    sim.mixed.run(Analog, &a, &dig, .{ .times = &times, .tick = tick }) catch |e| mixedFail(&bag, e);
    \\    a.flush();
    \\}
    \\
    \\
;
