//! The runner's fixed text: the Newton solver and the `@Vector(NL, f64)` lanes it drives.
//!
//! Zig source text, a template emitted into every generated testbench. Nothing here runs in the
//! compiler.
//!
//! LRM clauses this file's code cites: §1, §2.8.3, §3.4.1, §3.6.1.2, §4.2.1.1, §4.3.1, §4.5, §4.5.2, §5.3.1, §5.6.1.2, §5.10.5, §9.4.
//!
//! Cut verbatim from `tb.zig`.

const std = @import("std");
const tb = @import("../tb.zig");
const naming = @import("../naming.zig");

// ---------------------------------------------------------------------------
// The runner's fixed text
// ---------------------------------------------------------------------------

pub const runner_head =
    \\// GENERATED BY VerA — DO NOT EDIT.
    \\// A runnable Verilog-A testbench: the device's own `$strobe` output plus
    \\// the residual and Jacobian at each `//!`-declared operating point.
    \\
    \\const std = @import("std");
    \\const D = @import("device");
    \\const contract = @import("contract");
    \\
    \\const n_u = @typeInfo(D.U).@"enum".fields.len;
    \\
    \\
;

pub const runner_body =
    \\/// §2.8.3/§12.32: this testbench is a HOST, and a host answers for every
    \\/// `$name` the compiler left to a VPI application. There is no application
    \\/// in a `vera --run` build, so this one answers zero — and that answer is
    \\/// the testbench's, written here where a reader can see it, not a value the
    \\/// compiler substituted behind everyone's back.
    \\///
    \\/// ZERO IS NOT A CLAIM ABOUT THE FUNCTION. §12.32.3's own sampnhold listing
    \\/// never initializes `sampler->value` before its first update callback, so
    \\/// the language fixes no value for an unregistered systf and there is
    \\/// nothing here to be wrong about. What a fixture over one of these may
    \\/// assert is what does NOT depend on the value: that the analog block runs
    \\/// straight through the call (§5.3.1), that the residual is still built.
    \\/// Asserting the 0.0 itself would pin this file's choice as if it were the
    \\/// LRM's, and a host-linked conforming tool would then fail the fixture.
    \\///
    \\/// The partials are zero for the same reason and one more: a systf whose
    \\/// derivative were left undefined would put a number nothing computed into
    \\/// the Jacobian, and Newton would chase it.
    \\fn noVpiApp(_: *anyopaque, _: usize, _: []const f64, partials: []f64) f64 {
    \\    @memset(partials, 0);
    \\    return 0;
    \\}
    \\var no_vpi_app: contract.SystfHost = .{ .ctx = undefined, .call = noVpiApp };
    \\
    \\/// What `contract.validateHost` checks this host by. The testbench is not
    \\/// exempt from it: an exemption for the tool's own host is how a seam stops
    \\/// being tested, and this is the host that runs against every device the
    \\/// torture suite compiles.
    \\pub const iteration_hooks = true;
    \\pub const mutable_eval = true;
    \\/// 4.6.4.3 an array-parameter noise table: this host reads the card's own
    \\/// knots out of `noiseTablePoints`, not the declared defaults that reach
    \\/// `noise_tables`. See `emitNoiseTopology`'s `points=` comparison.
    \\pub const noise_table_points = true;
    \\pub fn systf(_: *const D.Model) ?*const contract.SystfHost {
    \\    return &no_vpi_app;
    \\}
    \\comptime {
    \\    contract.validateHost(@This(), D);
    \\}
    \\
    \\/// §3.4.1: "If the type of the parameter is specified as integer or real,
    \\/// and the value assigned to the parameter conflicts with the type of the
    \\/// parameter, the value is converted to the type of the parameter (see
    \\/// 4.2.1.1)." A `//! param` card is written in reals, like any host's, so
    \\/// an integer parameter is handed one here.
    \\///
    \\/// §4.2.1.1: "Real numbers are converted to integers by rounding the real
    \\/// number to the nearest integer, rather than by truncating it ... If the
    \\/// fractional part of the real number is exactly 0.5, it shall be rounded
    \\/// away from zero." `@round` is exactly that tie rule; `lossyCast` then
    \\/// saturates rather than trapping, which is the model card's own guard
    \\/// against a number outside the field's width.
    \\fn cardValue(comptime T: type, v: f64) T {
    \\    return switch (@typeInfo(T)) {
    \\        .int => std.math.lossyCast(T, @round(v)),
    \\        else => v,
    \\    };
    \\}
    \\
    \\/// Index of the unknown a directive named. A miss is a compile error that
    \\/// names the directive, not a runtime surprise.
    \\fn ix(comptime name: []const u8) usize {
    \\    const u = comptime std.meta.stringToEnum(D.U, name) orelse
    \\        @compileError(title ++ ": `//!` names unknown `" ++ name ++ "`, which this module does not have");
    \\    return @intFromEnum(u);
    \\}
    \\
    \\/// Forward-mode dual: value plus one partial per solver unknown. This is
    \\/// the same scalar the engine instantiates for the Jacobian, written out
    \\/// here so the testbench has no dependency beyond the device itself.
    \\const Dual = struct {
    \\    v: f64,
    \\    d: [n_u]f64 = @splat(0.0),
    \\    const T = @This();
    \\
    \\    pub fn con(c: f64) T { return .{ .v = c }; }
    \\    pub fn val(a: T) f64 { return a.v; }
    \\    pub fn ddxAt(a: T, i: usize) f64 { return a.d[i]; }
    \\
    \\    fn map(a: T, v: f64, k: f64) T { // chain rule: k = df/da at a.v
    \\        var r: T = .{ .v = v };
    \\        for (0..n_u) |i| r.d[i] = k * a.d[i];
    \\        return r;
    \\    }
    \\    fn map2(a: T, b: T, v: f64, ka: f64, kb: f64) T {
    \\        var r: T = .{ .v = v };
    \\        for (0..n_u) |i| r.d[i] = ka * a.d[i] + kb * b.d[i];
    \\        return r;
    \\    }
    \\
    \\    pub fn add(a: T, b: T) T { return map2(a, b, a.v + b.v, 1.0, 1.0); }
    \\    pub fn sub(a: T, b: T) T { return map2(a, b, a.v - b.v, 1.0, -1.0); }
    \\    pub fn mul(a: T, b: T) T { return map2(a, b, a.v * b.v, b.v, a.v); }
    \\    pub fn div(a: T, b: T) T { return map2(a, b, a.v / b.v, 1.0 / b.v, -a.v / (b.v * b.v)); }
    \\    pub fn neg(a: T) T { return map(a, -a.v, -1.0); }
    \\    pub fn scale(a: T, c: f64) T { return map(a, a.v * c, c); }
    \\    pub fn addC(a: T, c: f64) T { return map(a, a.v + c, 1.0); }
    \\    pub fn exp(a: T) T { return map(a, @exp(a.v), @exp(a.v)); }
    \\    pub fn log(a: T) T { return map(a, @log(a.v), 1.0 / a.v); }
    \\    // §4.3.1 Table 4-14: the C forms, because exp(x)-1 and log(1+x) cancel
    \\    // for small x. The DERIVATIVES do not cancel, so they stay exp/1÷(1+x).
    \\    pub fn expm1(a: T) T { return map(a, std.math.expm1(a.v), @exp(a.v)); }
    \\    pub fn log1p(a: T) T { return map(a, std.math.log1p(a.v), 1.0 / (1.0 + a.v)); }
    \\    pub fn sqrt(a: T) T { return map(a, @sqrt(a.v), 0.5 / @sqrt(a.v)); }
    \\    pub fn sin(a: T) T { return map(a, @sin(a.v), @cos(a.v)); }
    \\    pub fn cos(a: T) T { return map(a, @cos(a.v), -@sin(a.v)); }
    \\    pub fn tanh(a: T) T { const t = std.math.tanh(a.v); return map(a, t, 1.0 - t * t); }
    \\    pub fn sinh(a: T) T { return map(a, std.math.sinh(a.v), std.math.cosh(a.v)); }
    \\    pub fn cosh(a: T) T { return map(a, std.math.cosh(a.v), std.math.sinh(a.v)); }
    \\    pub fn atan(a: T) T { return map(a, std.math.atan(a.v), 1.0 / (1.0 + a.v * a.v)); }
    \\    pub fn abs(a: T) T { return map(a, @abs(a.v), if (a.v < 0.0) -1.0 else 1.0); }
    \\    pub fn pow(a: T, c: f64) T {
    \\        return map(a, std.math.pow(f64, a.v, c), c * std.math.pow(f64, a.v, c - 1.0));
    \\    }
    \\    // §4.3.1 min/max are selections: the derivative is the winner's.
    \\    // §4.3.1: equality selects the second operand and its derivative.
    \\    pub fn minC(a: T, c: f64) T { return if (a.v < c) a else con(c); }
    \\    pub fn maxC(a: T, c: f64) T { return if (a.v > c) a else con(c); }
    \\    pub fn min(a: T, b: T) T { return if (a.v < b.v) a else b; }
    \\    pub fn max(a: T, b: T) T { return if (a.v > b.v) a else b; }
    \\    // Contract masks and select. A comparison is piecewise constant, so
    \\    // its derivative is zero (`con`); like min/max, `sel` carries the
    \\    // winner's derivative.
    \\    pub fn lt(a: T, b: T) T { return con(@floatFromInt(@intFromBool(a.v < b.v))); }
    \\    pub fn le(a: T, b: T) T { return con(@floatFromInt(@intFromBool(a.v <= b.v))); }
    \\    pub fn eq(a: T, b: T) T { return con(@floatFromInt(@intFromBool(a.v == b.v))); }
    \\    pub fn sel(c: T, a: T, b: T) T { return if (c.v != 0.0) a else b; }
    \\};
    \\
    \\/// Value-form batch scalar: NL operating points per eval call, one per
    \\/// lane. Only instantiated for a device that declared `lane_clean` —
    \\/// codegen's promise that nothing in eval/q steers on a `.val()` of an
    \\/// x-dependent value, which is what makes `val` returning lane 0 safe:
    \\/// on a lane-clean device it is only ever called on lane-uniform values.
    \\const NL = 4;
    \\const VF = @Vector(NL, f64);
    \\const Vec = struct {
    \\    v: VF,
    \\    const T = @This();
    \\    fn map1(a: T, comptime f: anytype) T { // std.math fns are generic
    \\        var r: VF = undefined;
    \\        inline for (0..NL) |i| r[i] = f(a.v[i]);
    \\        return .{ .v = r };
    \\    }
    \\    pub fn con(c: f64) T { return .{ .v = @splat(c) }; }
    \\    pub fn val(a: T) f64 { return a.v[0]; }
    \\    pub fn ddxAt(_: T, _: usize) f64 { return 0.0; }
    \\    pub fn add(a: T, b: T) T { return .{ .v = a.v + b.v }; }
    \\    pub fn sub(a: T, b: T) T { return .{ .v = a.v - b.v }; }
    \\    pub fn neg(a: T) T { return .{ .v = -a.v }; }
    \\    pub fn mul(a: T, b: T) T { return .{ .v = a.v * b.v }; }
    \\    pub fn div(a: T, b: T) T { return .{ .v = a.v / b.v }; }
    \\    pub fn scale(a: T, c: f64) T { return .{ .v = a.v * @as(VF, @splat(c)) }; }
    \\    pub fn addC(a: T, c: f64) T { return .{ .v = a.v + @as(VF, @splat(c)) }; }
    \\    pub fn exp(a: T) T { return .{ .v = @exp(a.v) }; }
    \\    pub fn log(a: T) T { return .{ .v = @log(a.v) }; }
    \\    pub fn sqrt(a: T) T { return .{ .v = @sqrt(a.v) }; }
    \\    pub fn sin(a: T) T { return .{ .v = @sin(a.v) }; }
    \\    pub fn cos(a: T) T { return .{ .v = @cos(a.v) }; }
    \\    pub fn abs(a: T) T { return .{ .v = @abs(a.v) }; }
    \\    pub fn expm1(a: T) T { return map1(a, std.math.expm1); }
    \\    pub fn log1p(a: T) T { return map1(a, std.math.log1p); }
    \\    pub fn tanh(a: T) T { return map1(a, std.math.tanh); }
    \\    pub fn sinh(a: T) T { return map1(a, std.math.sinh); }
    \\    pub fn cosh(a: T) T { return map1(a, std.math.cosh); }
    \\    pub fn atan(a: T) T { return map1(a, std.math.atan); }
    \\    pub fn minC(a: T, c: f64) T { return .{ .v = @min(a.v, @as(VF, @splat(c))) }; }
    \\    pub fn maxC(a: T, c: f64) T { return .{ .v = @max(a.v, @as(VF, @splat(c))) }; }
    \\    pub fn min(a: T, b: T) T { return .{ .v = @min(a.v, b.v) }; }
    \\    pub fn max(a: T, b: T) T { return .{ .v = @max(a.v, b.v) }; }
    \\    pub fn pow(a: T, c: f64) T {
    \\        var r: VF = undefined;
    \\        inline for (0..NL) |i| r[i] = std.math.pow(f64, a.v[i], c);
    \\        return .{ .v = r };
    \\    }
    \\    const ones: VF = @splat(1.0);
    \\    const zeros: VF = @splat(0.0);
    \\    pub fn lt(a: T, b: T) T { return .{ .v = @select(f64, a.v < b.v, ones, zeros) }; }
    \\    pub fn le(a: T, b: T) T { return .{ .v = @select(f64, a.v <= b.v, ones, zeros) }; }
    \\    pub fn eq(a: T, b: T) T { return .{ .v = @select(f64, a.v == b.v, ones, zeros) }; }
    \\    pub fn sel(c: T, a: T, b: T) T { return .{ .v = @select(f64, c.v != zeros, a.v, b.v) }; }
    \\};
    \\
    \\comptime { // pinned to the contract's list, so a new primitive cannot miss one
    \\    contract.checkScalar(Dual);
    \\    contract.checkScalar(Vec);
    \\}
    \\
    \\/// The batch differential gate (ref/SIMD-Strategies T8): one vector eval
    \\/// over NL perturbed copies of the operating point must agree with NL
    \\/// scalar evals, lane by lane. Bit equality is the expectation — the same
    \\/// IEEE ops run in the same order per lane — with a 1e-12 relative escape
    \\/// for a vectorizer that contracts differently than the scalar pipeline.
    \\/// Prints nothing on success, so transcripts never move; a mismatch is a
    \\/// loud failure of the run.
    \\fn laneCheck(x: *const [n_u]f64, t: f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    if (comptime !(@hasDecl(D, "lane_clean") and D.lane_clean)) return;
    \\    var xs: [NL][n_u]f64 = undefined;
    \\    var xv: [n_u]Vec = undefined;
    \\    for (0..NL) |k| {
    \\        const s = 1.0 + 1.0e-3 * @as(f64, @floatFromInt(k));
    \\        for (0..n_u) |i| xs[k][i] = x[i] * s + 1.0e-3 * @as(f64, @floatFromInt(k));
    \\    }
    \\    for (0..n_u) |i| {
    \\        // Through an array: a vector index must be comptime-known.
    \\        var lanes: [NL]f64 = undefined;
    \\        for (0..NL) |k| lanes[k] = xs[k][i];
    \\        xv[i] = .{ .v = lanes };
    \\    }
    \\    const rv = D.eval(Vec, xv, model, inst, t);
    \\    for (0..NL) |k| {
    \\        var xd: [n_u]Dual = undefined;
    \\        for (0..n_u) |i| {
    \\            xd[i] = .{ .v = xs[k][i] };
    \\            xd[i].d[i] = 1.0;
    \\        }
    \\        const rs = D.eval(Dual, xd, model, inst, t);
    \\        for (0..n_u) |i| {
    \\            const lanes: [NL]f64 = rv[i].v;
    \\            laneAssert("res", i, k, lanes[k], rs[i].v);
    \\        }
    \\    }
    \\    if (comptime @hasDecl(D, "q")) {
    \\        const qv = D.q(Vec, xv, model, inst, t);
    \\        for (0..NL) |k| {
    \\            var xd: [n_u]Dual = undefined;
    \\            for (0..n_u) |i| xd[i] = .{ .v = xs[k][i] };
    \\            const qs = D.q(Dual, xd, model, inst, t);
    \\            for (0..n_u) |i| {
    \\                const lanes: [NL]f64 = qv[i].v;
    \\                laneAssert("q", i, k, lanes[k], qs[i].v);
    \\            }
    \\        }
    \\    }
    \\}
    \\
    \\/// The fused differential gate: `evalQ` shares ONE core call between the
    \\/// two halves, so it must return exactly what the separate `eval` and `q`
    \\/// return. Same ops, same order, same core — bit equality, no epsilon.
    \\/// A mismatch means the shared-core hoist changed the physics, which is
    \\/// the only way this refactor can be wrong.
    \\fn fusedCheck(x: *const [n_u]f64, t: f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    if (comptime !@hasDecl(D, "evalQ")) return;
    \\    const xd = seed(x);
    \\    const both = D.evalQ(Dual, xd, model, inst, t);
    \\    const res = D.eval(Dual, xd, model, inst, t);
    \\    const qq = D.q(Dual, xd, model, inst, t);
    \\    for (0..n_u) |i| {
    \\        fusedAssert("res", i, both.res[i].v, res[i].v);
    \\        fusedAssert("q", i, both.q[i].v, qq[i].v);
    \\        for (0..n_u) |j| {
    \\            fusedAssert("dres", i, both.res[i].d[j], res[i].d[j]);
    \\            fusedAssert("dq", i, both.q[i].d[j], qq[i].d[j]);
    \\        }
    \\    }
    \\}
    \\
    \\/// The structural-Jacobian gate. `jac_pattern`/`q_pattern` tell a host
    \\/// which local matrix entries this device can fill, and the host DELETES
    \\/// the stamps for the rest — it does not even reserve the matrix entry.
    \\/// So a cleared bit with a nonzero partial behind it is a silently missing
    \\/// Jacobian entry, and that is the one way the declaration can be wrong.
    \\/// The converse is legal: the pattern over-approximates on purpose, and a
    \\/// set bit that happens to be zero at this bias costs one stamp.
    \\fn patternCheck(x: *const [n_u]f64, t: f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    const xd = seed(x);
    \\    const r = D.eval(Dual, xd, model, inst, t);
    \\    if (comptime @hasDecl(D, "jac_pattern")) patAssert("res", D.jac_pattern, &r);
    \\    if (comptime @hasDecl(D, "jac_rows")) rowAssert("res", D.jac_rows, &r);
    \\    if (comptime @hasDecl(D, "q")) {
    \\        const qr = D.q(Dual, xd, model, inst, t);
    \\        if (comptime @hasDecl(D, "q_pattern")) patAssert("q", D.q_pattern, &qr);
    \\        if (comptime @hasDecl(D, "q_rows")) rowAssert("q", D.q_rows, &qr);
    \\    }
    \\}
    \\
    \\/// The narrow-lane gate, the one a host relies on when it seeds a Dual only
    \\/// for `contract.derivReads(D)` and stamps `contract.jacConst(D)` for every
    \\/// other column. The Jacobian is computed twice at this point:
    \\///   WIDE    every unknown seeded, as `seed` does;
    \\///   NARROW  lanes seeded only for deriv_reads, jac_const for the rest;
    \\/// and the two must agree BIT FOR BIT, value and every partial, eval and q.
    \\/// A lane this Dual keeps for an unseeded unknown is simply zero, so a
    \\/// seeded lane runs the same IEEE ops as the wide one and any difference
    \\/// is the device's claim being wrong — a column it called constant that is
    \\/// not, or a `ddxAt` it reads without declaring.
    \\///
    \\/// ONE ESCAPE, and it is not a tolerance: on a constant column a zero
    \\/// matches a zero of either sign. jac_const cannot carry a signed zero —
    \\/// an absent entry is 0 by contract — while the wide Dual writes −0.0
    \\/// wherever a `neg` meets an empty lane. Every nonzero compares by bits.
    \\///
    \\/// Always on, not behind a flag: it is two more evals of a fixture-sized
    \\/// device, and a gate that has to be asked for is one somebody forgets.
    \\fn narrowCheck(x: *const [n_u]f64, t: f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    const wide = seed(x);
    \\    var narrow: [n_u]Dual = undefined;
    \\    for (0..n_u) |i| {
    \\        narrow[i] = .{ .v = x[i] };
    \\        if (hasLane(i)) narrow[i].d[i] = 1.0;
    \\    }
    \\    narrowAssert("res", false, &D.eval(Dual, wide, model, inst, t), &D.eval(Dual, narrow, model, inst, t));
    \\    if (comptime @hasDecl(D, "q"))
    \\        narrowAssert("q", true, &D.q(Dual, wide, model, inst, t), &D.q(Dual, narrow, model, inst, t));
    \\}
    \\
    \\fn hasLane(u: usize) bool {
    \\    return u >= 64 or (contract.derivReads(D) >> @intCast(u)) & 1 != 0;
    \\}
    \\
    \\fn narrowAssert(what: []const u8, react: bool, w: *const [n_u]Dual, nr: *const [n_u]Dual) void {
    \\    for (0..n_u) |i| {
    \\        if (@as(u64, @bitCast(w[i].v)) != @as(u64, @bitCast(nr[i].v))) {
    \\            std.debug.print("narrow_check FAIL: {s}[{s}]: wide {e} vs narrow {e}\n", .{ what, u_names[i], w[i].v, nr[i].v });
    \\            std.process.exit(1);
    \\        }
    \\        for (0..n_u) |j| {
    \\            var k: f64 = nr[i].d[j];
    \\            if (!hasLane(j)) {
    \\                k = 0.0;
    \\                for (contract.jacConst(D)) |e| {
    \\                    if (@intFromEnum(e.row) == i and @intFromEnum(e.col) == j) k = if (react) e.c else e.g;
    \\                }
    \\                if (k == 0.0 and w[i].d[j] == 0.0) continue;
    \\            }
    \\            if (@as(u64, @bitCast(w[i].d[j])) == @as(u64, @bitCast(k))) continue;
    \\            std.debug.print("narrow_check FAIL: d{s}[{s}]/dx[{s}]: wide {e} vs narrow {e}{s}\n", .{
    \\                what, u_names[i], u_names[j], w[i].d[j], k, if (hasLane(j)) "" else " (jac_const)",
    \\            });
    \\            std.process.exit(1);
    \\        }
    \\    }
    \\}
    \\
    \\fn patAssert(what: []const u8, pat: [n_u]u64, r: *const [n_u]Dual) void {
    \\    for (0..n_u) |i| for (0..n_u) |j| {
    \\        if (r[i].d[j] == 0.0) continue;
    \\        if ((pat[i] >> @intCast(j)) & 1 != 0) continue;
    \\        std.debug.print("pattern_check FAIL: d{s}[{s}]/dx[{s}] = {e} is outside the declared pattern\n", .{ what, u_names[i], u_names[j], r[i].d[j] });
    \\        std.process.exit(1);
    \\    };
    \\}
    \\
    \\/// The WRITTEN-ROW gate. A host drops a row outside `jac_rows`/`q_rows`
    \\/// entirely — no residual stamp, no charge-tape entry — so a clear bit
    \\/// with anything but a hard zero behind it is a term that vanishes from
    \\/// the netlist with no diagnostic. This is the check that fails if
    \\/// codegen ever writes `res[ru]` without going through `patRow`, and the
    \\/// value, not the derivative, is what it looks at: `isource` writes rows
    \\/// whose every partial is zero.
    \\fn rowAssert(what: []const u8, rows: u64, r: *const [n_u]Dual) void {
    \\    for (0..n_u) |i| {
    \\        if ((rows >> @intCast(i)) & 1 != 0) continue;
    \\        if (r[i].v == 0.0) continue;
    \\        std.debug.print("row_check FAIL: {s}[{s}] = {e} but the row is declared never written\n", .{ what, u_names[i], r[i].v });
    \\        std.process.exit(1);
    \\    }
    \\}
    \\
    \\fn fusedAssert(what: []const u8, i: usize, a: f64, b: f64) void {
    \\    if (@as(u64, @bitCast(a)) == @as(u64, @bitCast(b))) return;
    \\    std.debug.print("fused_check FAIL: {s}[{s}]: evalQ {e} vs split {e}\n", .{ what, u_names[i], a, b });
    \\    std.process.exit(1);
    \\}
    \\
    \\/// Bit equality is the expectation — the same IEEE ops run in the same
    \\/// order per lane — with a 1e-12 relative escape for a vectorizer that
    \\/// contracts differently than the scalar pipeline.
    \\fn laneAssert(what: []const u8, i: usize, k: usize, a: f64, b: f64) void {
    \\    if (@as(u64, @bitCast(a)) == @as(u64, @bitCast(b))) return;
    \\    if (@abs(a - b) <= 1.0e-12 * @max(@abs(a), @abs(b))) return;
    \\    std.debug.print("lane_check FAIL: {s}[{s}] lane {d}: batch {e} vs scalar {e}\n", .{ what, u_names[i], k, a, b });
    \\    std.process.exit(1);
    \\}
    \\
    \\/// §4.5.2 accepted-step bookkeeping. `void` for a module with no stateful
    \\/// operator, which is most of them — codegen emits the state machine only
    \\/// when one is present.
    \\const State = if (@hasDecl(D, "updateState") and @hasDecl(D, "initState")) D.State else void;
    \\
    \\fn newState(model: *const D.Model, inst: *D.Instance) State {
    \\    if (State == void) return {};
    \\    return D.initState(model, inst);
    \\}
    \\
    \\/// Commit the accepted solution, exactly as a transient solver does after
    \\/// a converged step. `eval` READS the history out of `Instance`; this is the
    \\/// only thing that ever writes it, so without this call every §4.5 operator
    \\/// would answer from zero history at every time point and the transcript
    \\/// would claim more than it proves.
    \\fn step(model: *const D.Model, inst: *D.Instance, x: *const [n_u]f64, state: *State) void {
    \\    if (State == void) return;
    \\    _ = D.updateState(model, inst, x.*, state);
    \\}
    \\
    \\/// Iteration history advances independently of accepted-time operators.
    \\/// §5.6.1.2 the accepted step's CHARGE, which is the other operand of the
    \\/// backward-Euler difference `solve` forms at the next time point. Taken
    \\/// before `step`, so it is the q of the state `eval` saw while this point
    \\/// was being solved and not of the history `updateState` is about to write.
    \\var q_prev: [n_u]f64 = @splat(0.0);
    \\
    \\fn commitCharge(model: *const D.Model, inst: *D.Instance, x: *const [n_u]f64) void {
    \\    if (comptime !@hasDecl(D, "q")) return;
    \\    const qq = D.q(Dual, seed(x), model, inst, inst.abstime);
    \\    for (0..n_u) |i| q_prev[i] = qq[i].v;
    \\}
    \\
    \\/// `acceptQ` is `q` then `updateState` from one core evaluation, so its
    \\/// charge must be `q`'s to the bit, lanes included. Run on copies: the
    \\/// transcript keeps advancing through `updateState` exactly as before.
    \\fn acceptCheck(model: *const D.Model, inst: *const D.Instance, x: *const [n_u]f64, state: *const State) void {
    \\    if (comptime !@hasDecl(D, "acceptQ") or State == void) return;
    \\    var iw = inst.*;
    \\    const want = D.q(Dual, seed(x), model, &iw, inst.abstime);
    \\    var ic = inst.*;
    \\    var sc = state.*;
    \\    const got = D.acceptQ(Dual, seed(x), model, &ic, &sc);
    \\    for (0..n_u) |i| {
    \\        if (@as(u64, @bitCast(got[i].v)) == @as(u64, @bitCast(want[i].v)) and
    \\            std.mem.eql(u8, std.mem.asBytes(&got[i].d), std.mem.asBytes(&want[i].d))) continue;
    \\        std.debug.print("acceptQ FAIL: q[{s}] {e} vs q() {e}\n", .{ u_names[i], got[i].v, want[i].v });
    \\        std.process.exit(1);
    \\    }
    \\}
    \\
    \\fn stepPost(model: *const D.Model, inst: *D.Instance, x: *const [n_u]f64, state: *State, solved: bool) void {
    \\    acceptCheck(model, inst, x, state);
    \\    commitCharge(model, inst, x);
    \\    if (@hasDecl(D, "advanceIteration")) if (!solved) {
    \\        // Forced-point fixtures sample both lifetimes. Both updates must
    \\        // read the same evaluated state, even when their inputs depend
    \\        // on one another. These two fields are owned by iteration hooks.
    \\        var next = inst.*;
    \\        D.advanceIteration(model, &next, x.*);
    \\        step(model, inst, x, state);
    \\        if (@hasField(D.Instance, "limiter_previous")) inst.limiter_previous = next.limiter_previous;
    \\        if (@hasField(D.Instance, "newton_iteration")) inst.newton_iteration = next.newton_iteration;
    \\        return;
    \\    };
    \\    step(model, inst, x, state);
    \\}
    \\
    \\fn seed(x: *const [n_u]f64) [n_u]Dual {
    \\    var out: [n_u]Dual = undefined;
    \\    for (0..n_u) |i| {
    \\        out[i] = .{ .v = x[i] };
    \\        out[i].d[i] = 1.0;
    \\    }
    \\    return out;
    \\}
    \\
    \\const u_names = blk: {
    \\    const f = @typeInfo(D.U).@"enum".fields;
    \\    var names: [f.len][]const u8 = undefined;
    \\    for (f, 0..) |e, i| names[i] = e.name;
    \\    break :blk names;
    \\};
    \\
    \\/// One operating point: the bias, then whatever the model prints, then the
    \\/// residual it stamps and the Jacobian the solver would see.
    \\fn point(n: usize, x: *const [n_u]f64, t: f64, model: *const D.Model, inst: contract.InstancePtr(D)) void {
    \\    std.debug.print("--- point {d} ---\n", .{n});
    \\    for (0..n_u) |i| std.debug.print("  x[{s}] = {e:.6}\n", .{ u_names[i], x[i] });
    \\    if (inst.abstime != 0.0 or inst.dt != 0.0)
    \\        std.debug.print("  t = {e:.6}  dt = {e:.6}\n", .{ inst.abstime, inst.dt });
    \\
    \\    // §5.10.5 the host's breakpoint hook, when codegen emitted one (only a
    \\    // module with a `timer` has one). Printed OUTSIDE `print_residual`
    \\    // because it is not part of the residual and the fixtures that test it
    \\    // are `print none`; `@hasDecl` keeps every other transcript unchanged.
    \\    if (@hasDecl(D, "nextBreakpoint")) {
    \\        if (D.nextBreakpoint(model, t)) |bp|
    \\            std.debug.print("  next_bp = {e:.6}\n", .{bp})
    \\        else
    \\            std.debug.print("  next_bp = none\n", .{});
    \\    }
    \\
    \\    // Differential gates — silent on success, fail the run loudly.
    \\    laneCheck(x, t, model, inst);
    \\    fusedCheck(x, t, model, inst);
    \\    patternCheck(x, t, model, inst);
    \\    narrowCheck(x, t, model, inst);
    \\
    \\    const xd = seed(x);
    \\    // §9.4 the model's own transcript. Runs BEFORE the residual print so a
    \\    // fixture's `$strobe` lines sit next to the bias that produced them.
    \\    if (@hasDecl(D, "display")) D.display(Dual, xd, model, inst, t);
    \\    if (!print_residual) return;
    \\
    \\    const res = D.eval(Dual, xd, model, inst, t);
    \\    for (0..n_u) |i| {
    \\        std.debug.print("  res[{s}] = {e:.6}\n", .{ u_names[i], res[i].v });
    \\        for (0..n_u) |j| {
    \\            if (res[i].d[j] == 0.0) continue;
    \\            std.debug.print("    d res[{s}]/d x[{s}] = {e:.6}\n", .{ u_names[i], u_names[j], res[i].d[j] });
    \\        }
    \\    }
    \\    // §5.6.1.2 the reactive half, when the model has one. Its derivative is
    \\    // the capacitance/inductance matrix the host multiplies by d/dt.
    \\    if (@hasDecl(D, "q")) {
    \\        const qq = D.q(Dual, xd, model, inst, t);
    \\        for (0..n_u) |i| {
    \\            if (qq[i].v == 0.0 and allZero(qq[i].d)) continue;
    \\            std.debug.print("  q[{s}] = {e:.6}\n", .{ u_names[i], qq[i].v });
    \\            for (0..n_u) |j| {
    \\                if (qq[i].d[j] == 0.0) continue;
    \\                std.debug.print("    d q[{s}]/d x[{s}] = {e:.6}\n", .{ u_names[i], u_names[j], qq[i].d[j] });
    \\            }
    \\        }
    \\    }
    \\}
    \\
    \\fn allZero(v: [n_u]f64) bool {
    \\    for (v) |e| if (e != 0.0) return false;
    \\    return true;
    \\}
    \\
    \\/// Pin an unknown at the value a `//! bias`, `//! sweep` or `//! wave` line
    \\/// gave it: the INITIAL GUESS Newton starts from, and the CONSTRAINT row it
    \\/// keeps. Both, from one directive, because a directive that names a value
    \\/// for an unknown is saying the host drives it.
    \\fn set(x: *[n_u]f64, forced: *[n_u]?f64, comptime name: []const u8, v: f64) void {
    \\    x[ix(name)] = v;
    \\    forced[ix(name)] = v;
    \\}
    \\
    \\/// §3.6.1.2 `abstol` — "the largest signal value that can be safely
    \\/// ignored" — per unknown, which is the absolute half of Newton's stopping
    \\/// test. The device declares it (codegen reads it off the net's discipline,
    \\/// §3.6.2.3 override included); the fallback is annex D's own defaults for
    \\/// `Voltage` and `Current`, for a hand-written device that declares neither
    \\/// table.
    \\const u_abstol: [n_u]f64 = if (@hasDecl(D, "u_abstol")) D.u_abstol else blk: {
    \\    var a: [n_u]f64 = @splat(1e-6);
    \\    if (@hasDecl(D, "u_kinds")) for (D.u_kinds, 0..) |k, i| {
    \\        if (k != .voltage) a[i] = 1e-12;
    \\    };
    \\    break :blk a;
    \\};
    \\
    \\/// The relative half. Tighter than a circuit simulator's default reltol
    \\/// because a fixture asserts a digit derived from the LRM, not a waveform:
    \\/// the systems here are small enough that the extra decades cost nothing.
    \\const solve_reltol = 1e-12;
    \\
    \\/// A cap, not a budget. Every fixture system converges in one step (linear)
    \\/// or a handful; reaching this means the iteration is not converging, and
    \\/// that has to be LOUD — see the exit below.
    \\const solve_max_iter = 100;
    \\
    \\/// §5.6 THE SOLVE, and it is a solve.
    \\///
    \\/// Verilog-A semantics are defined AT A SOLUTION of the nodal equations,
    \\/// never at an arbitrary point. §5.6.7's indirect contribution is a
    \\/// CONSTRAINT the simulator satisfies rather than an assignment — there is
    \\/// no way to express it by evaluating anything — and §5.4.2.2's "the
    \\/// potential of a source branch may be read" is a question about what the
    \\/// solver settled on. A harness that wrote `//! bias` into x[] and stopped
    \\/// could only ever hand a fixture back the number the harness itself just
    \\/// wrote.
    \\///
    \\/// So: Newton-Raphson on the residual the device stamps, with the Jacobian
    \\/// the forward-mode `Dual` above already carries. Dense LU with partial
    \\/// pivoting — a fixture's system is under ~10 unknowns, so a sparse
    \\/// factorisation or an ordering heuristic would be code with nothing to do.
    \\///
    \\/// ONE RULE BEYOND TEXTBOOK NEWTON, and it is what makes an isolated device
    \\/// solvable at all. A .va compiled alone is NOT a circuit. `I(p,n) <+ 0.0`
    \\/// stamps two identically-zero rows; a two-terminal module that never
    \\/// references ground leaves its common mode undetermined however nonlinear
    \\/// it is. Those are free directions of the device's own equations, not
    \\/// solver failures — a host pins them by CONNECTING the device to
    \\/// something. So a column with no usable pivot takes dx = 0 and its unknown
    \\/// HOLDS the operating point the `//!` lines declared, which is exactly the
    \\/// behaviour this harness had before it could solve at all. Convergence is
    \\/// then judged on the unknowns the system does determine, and only those.
    \\///
    \\/// ponytail: no gmin stepping, no source stepping, no continuation. Every
    \\/// system in the suite converges from the declared guess. Add the minimum
    \\/// and name it here if one ever does not.
    \\///
    \\/// §5.6.1.2's reactive half is folded in by BACKWARD EULER, because a
    \\/// fixture finally needed a transient solve: §5.4.3's port current is the
    \\/// whole of what the module stamps at the port, charge included, and
    \\/// `res[flow(<p>)] = x − res[p]` alone can only ever hand back the
    \\/// conduction half (ch05_analog_behavior/a02_06). So the row Newton sees is
    \\///
    \\///     eval(x) + (q(x) − q_prev) / dt
    \\///
    \\/// with `q_prev` the charge of the last accepted point (`commitCharge`).
    \\///
    \\/// ponytail: first order, fixed step, no LTE control and no step rejection
    \\/// — `//! time` states the steps and the suite asserts values a clause
    \\/// derives, not a waveform's accuracy. Trapezoidal or gear-2 is the upgrade
    \\/// if a fixture ever asserts a number the Euler truncation error moves.
    \\///
    \\/// dt = 0 is the DC point that opens a transient (`renderRunner` gives the
    \\/// first time step dt = 0 for exactly this reason, §4.5.3), and there the
    \\/// difference is undefined and the charge contributes nothing — so that
    \\/// point is still the resistive solve it always was.
    \\fn solve(x: *[n_u]f64, forced: *const [n_u]?f64, model: *const D.Model, inst: *D.Instance) bool {
    \\    // Nothing to determine: every unknown is one a `//!` line named, or the
    \\    // reference the harness ties the rest to without `//! solve`. x already
    \\    // holds the answer. Returning here is not only the cheap path — it is
    \\    // what keeps a `//! print none` fixture evaluated exactly as often as it
    \\    // was before there was a solver, so no §9.4 transcript moves.
    \\    for (forced) |f| {
    \\        if (f == null) break;
    \\    } else return false;
    \\    if (@hasDecl(D, "beginSolve")) D.beginSolve(inst);
    \\    var previous = x.*;
    \\    var worst: usize = 0;
    \\    var worst_dx: f64 = 0.0;
    \\    var iter: usize = 0;
    \\    while (iter < solve_max_iter) : (iter += 1) {
    \\        if (@hasDecl(D, "advanceIteration")) if (iter != 0) D.advanceIteration(model, inst, previous);
    \\        previous = x.*;
    \\        const xd = seed(x);
    \\        var r = D.eval(Dual, xd, model, inst, inst.abstime);
    \\        // §5.6.1.2 backward Euler — see the header. Value and derivative
    \\        // both, so the capacitance matrix reaches the Jacobian too.
    \\        if (comptime @hasDecl(D, "q")) if (inst.dt > 0.0) {
    \\            const qq = D.q(Dual, xd, model, inst, inst.abstime);
    \\            for (0..n_u) |i| {
    \\                r[i].v += (qq[i].v - q_prev[i]) / inst.dt;
    \\                for (0..n_u) |j| r[i].d[j] += qq[i].d[j] / inst.dt;
    \\            }
    \\        };
    \\        var a: [n_u][n_u]f64 = undefined;
    \\        var b: [n_u]f64 = undefined;
    \\        var scale: f64 = 0.0;
    \\        for (0..n_u) |i| {
    \\            if (forced[i]) |v| {
    \\                // The host drives this one, so its row is the constraint and
    \\                // not the device's KCL. Written as a Newton row (1·dx =
    \\                // v - x) rather than by assignment, so the value survives
    \\                // elimination against every other row exactly.
    \\                a[i] = @splat(0.0);
    \\                a[i][i] = 1.0;
    \\                b[i] = v - x[i];
    \\            } else {
    \\                a[i] = r[i].d;
    \\                b[i] = -r[i].v;
    \\            }
    \\            for (a[i]) |e| scale = @max(scale, @abs(e));
    \\        }
    \\        var dx: [n_u]f64 = undefined;
    \\        var solved: [n_u]bool = undefined;
    \\        luSolve(&a, &b, &dx, &solved, scale);
    \\        var settled = true;
    \\        worst_dx = 0.0;
    \\        for (0..n_u) |i| {
    \\            if (!solved[i]) continue;
    \\            const tol = u_abstol[i] + solve_reltol * @abs(x[i]);
    \\            if (@abs(dx[i]) > tol and @abs(dx[i]) > worst_dx) {
    \\                settled = false;
    \\                worst_dx = @abs(dx[i]);
    \\                worst = i;
    \\            }
    \\        }
    \\        for (0..n_u) |i| x[i] += dx[i];
    \\        const can_converge = if (@hasDecl(D, "checkConvergence")) D.checkConvergence(model, inst, x.*) else true;
    \\        if (settled and can_converge) return true;
    \\    }
    \\    // A testbench that does not converge must FAIL, loudly and by exit
    \\    // status, naming the unknown that would not settle. Falling through and
    \\    // letting the model assert against a half-iterated x would report a
    \\    // conformance verdict on arithmetic nobody solved.
    \\    std.debug.print(
    \\        "{s}: did not converge after {d} Newton iterations: x[{s}] still moving {e:.6} per step, tolerance {e:.6}\n",
    \\        .{ title, solve_max_iter, u_names[worst], worst_dx, u_abstol[worst] + solve_reltol * @abs(x[worst]) },
    \\    );
    \\    std.process.exit(1);
    \\}
    \\
    \\/// Dense LU with partial pivoting, rank-revealing exactly as far as `solve`
    \\/// needs: `solved[k]` is false for a column with no usable pivot, and
    \\/// `dx[k]` is then 0. Row `k` of the echelon form lives at `perm[…]`, so
    \\/// nothing is physically moved.
    \\fn luSolve(
    \\    a: *[n_u][n_u]f64,
    \\    b: *[n_u]f64,
    \\    dx: *[n_u]f64,
    \\    solved: *[n_u]bool,
    \\    scale: f64,
    \\) void {
    \\    // "Usable" is relative to the largest entry in the whole system: a
    \\    // structurally absent coupling and one that cancelled to rounding are
    \\    // both absence of information, and treating the second as a pivot is
    \\    // how a solver invents a 1e17 node voltage.
    \\    const eps = 1e-14 * scale;
    \\    var pivot: [n_u]usize = @splat(0);
    \\    var perm: [n_u]usize = undefined;
    \\    for (0..n_u) |i| perm[i] = i;
    \\    var rows: usize = 0; // rows consumed by a pivot so far
    \\    for (0..n_u) |k| {
    \\        var best = rows;
    \\        var best_v: f64 = -1.0;
    \\        for (rows..n_u) |i| {
    \\            const v = @abs(a[perm[i]][k]);
    \\            if (v > best_v) {
    \\                best_v = v;
    \\                best = i;
    \\            }
    \\        }
    \\        if (best_v <= eps) {
    \\            solved[k] = false;
    \\            continue;
    \\        }
    \\        std.mem.swap(usize, &perm[rows], &perm[best]);
    \\        const p = perm[rows];
    \\        pivot[k] = p;
    \\        solved[k] = true;
    \\        for (rows + 1..n_u) |i| {
    \\            const qr = perm[i];
    \\            if (a[qr][k] == 0.0) continue;
    \\            const f = a[qr][k] / a[p][k];
    \\            for (k..n_u) |j| a[qr][j] -= f * a[p][j];
    \\            b[qr] -= f * b[p];
    \\        }
    \\        rows += 1;
    \\    }
    \\    // Back-substitution over the pivoted columns, highest first. A free
    \\    // column contributes nothing to any row above it, because its dx is 0.
    \\    var k = n_u;
    \\    while (k > 0) {
    \\        k -= 1;
    \\        if (!solved[k]) {
    \\            dx[k] = 0.0;
    \\            continue;
    \\        }
    \\        const p = pivot[k];
    \\        var s = b[p];
    \\        for (k + 1..n_u) |j| s -= a[p][j] * dx[j];
    \\        dx[k] = s / a[p][k];
    \\    }
    \\}
    \\
    \\
;

/// The mixed-signal runner's fixed text (`renderMixed`): the digital half, the
/// coordinator call, and the two conversions the adapter needs. Only a
/// testbench built with `BuildOptions.mixed` imports `sim` and `diag`.
pub const mixed_body =
    \\const sim = @import("sim");
    \\const diag = @import("diag");
    \\const Timescale = @typeInfo(@FieldType(sim.digital.Mixed, "timescale")).optional.child;
    \\
    \\/// VAMS §7.3.1 Table 7-1: a bit grouping, a net and an `integer` all reach
    \\/// the continuous context as an integer. §7.3.2: "It is an error if these
    \\/// operands return x or z bit values when solved" — and a solve is exactly
    \\/// where this is read, so an x or z bit fails the run by name.
    \\fn mixedInput(dig: *sim.digital.Run, slot: u32, name: []const u8) i64 {
    \\    return dig.values[slot].asInt() orelse {
    \\        std.debug.print("{s}: FAIL §7.3.2: the discrete input `{s}` holds an x or z bit when the analog block reads it\n", .{ title, name });
    \\        std.process.exit(1);
    \\    };
    \\}
    \\
    \\/// A `//! wave`, piecewise linear over the declared `//! time`s. At a
    \\/// declared point it is the fixed-grid runner's value, a short list holds its
    \\/// last entry, and an inserted point between two declared ones interpolates.
    \\fn pwl(values: []const f64, t: f64) f64 {
    \\    var k: usize = 0;
    \\    while (k + 1 < times.len and times[k + 1] <= t) k += 1;
    \\    const v0 = values[@min(k, values.len - 1)];
    \\    if (k + 1 >= times.len or k + 1 >= values.len) return v0;
    \\    return v0 + (values[k + 1] - v0) * (t - times[k]) / (times[k + 1] - times[k]);
    \\}
    \\
    \\/// A digital name the device reads, and the `Model` field it arrives in.
    \\const Port = struct { name: []const u8, field: []const u8, xz: ?[]const u8 = null };
    \\/// §8.5 an explicit D2A term: the event it waits on, and its `Model` flag.
    \\const EventPort = struct { name: []const u8, edge: @FieldType(sim.digital.D2aSite, "edge"), field: []const u8 };
    \\
    \\fn setField(model: *D.Model, comptime field: []const u8, v: anytype) void {
    \\    @field(model, field) = std.math.lossyCast(@TypeOf(@field(model, field)), v);
    \\}
    \\
    \\fn mixedSlot(dig: *sim.digital.Run, name: []const u8) u32 {
    \\    return dig.slotOf(name) orelse {
    \\        std.debug.print("{s}: FAIL the digital half holds no `{s}` for the analog block to read\n", .{ title, name });
    \\        std.process.exit(1);
    \\    };
    \\}
    \\
    \\fn mixedFail(bag: *diag.Bag, e: anyerror) noreturn {
    \\    var buf = std.Io.Writer.Allocating.init(std.heap.page_allocator);
    \\    diag.render(bag, &buf.writer, .{ .explain_hint = false, .summary = false }) catch {};
    \\    std.debug.print("{s}FAIL {s}: the digital half did not run: {t}\n", .{ buf.written(), title, e });
    \\    std.process.exit(1);
    \\}
    \\
    \\/// One analysis: elaborate the digital half afresh, bind the inputs, and
    \\/// let `sim.mixed.run` own the global time.
    \\fn runMixed(model: *D.Model, inst: *D.Instance, x: *[n_u]f64, forced: *[n_u]?f64, state: *State, n: *usize) void {
    \\    var arena_state = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    \\    defer arena_state.deinit();
    \\    const arena = arena_state.allocator();
    \\    var bag = diag.Bag.init(arena);
    \\    bag.setSingleFile(title, mixed_source, 0) catch {};
    \\    var dout = std.Io.Writer.Allocating.init(arena);
    \\    var dig = sim.digital.elaborate(arena, mixed_source, .{ .mixed = .{ .top = mixed_top, .timescale = mixed_timescale } }, &bag, &dout.writer) catch |e| mixedFail(&bag, e);
    \\    var a: Analog = .{ .model = model, .inst = inst, .x = x, .forced = forced, .state = state, .dout = &dout, .n = n, .slots = undefined, .snap_slots = undefined };
    \\    // §8.4.3.2: an unguarded read makes the block implicitly sensitive.
    \\    inline for (input_ports, 0..) |p, i| {
    \\        a.slots[i] = mixedSlot(&dig, p.name);
    \\        dig.watchAnalog(a.slots[i]);
    \\    }
    \\    inline for (snap_ports, 0..) |p, i| a.snap_slots[i] = mixedSlot(&dig, p.name);
    \\    inline for (event_ports, 0..) |p, k| dig.watchEvent(mixedSlot(&dig, p.name), p.edge, k) catch |e| mixedFail(&bag, e);
    \\    const tick = if (mixed_timescale) |ts| ts.precision else 1.0;
    \\    sim.mixed.run(Analog, &a, &dig, .{ .times = &times, .tick = tick }) catch |e| mixedFail(&bag, e);
    \\    a.flush();
    \\}
    \\
    \\
;
