//! The runtime kernels a device carries, as Zig source text: §4.3 math, §4.5
//! operators, the scalar-family helpers and Clause 9 kernels. `emitFile`
//! splices them into device.zig and `buildPrelude` into `h.zig`; the text runs
//! in the host's Newton loop, never in the compiler.
//! LRM: §2.9, §4.3, §4.3.1, §4.3.2, §4.5, §4.5.7, §4.5.15, §5.10.3.1, §5.10.5, §9.4.3,
//! §9.5, §9.13, §9.21.

const std = @import("std");
const codegen = @import("../codegen.zig");
const naming = @import("../naming.zig");

// ===========================================================================
// Fixed emitted text
// ===========================================================================

/// NaN and +inf as bit-pattern literals, the values `std.math.nan(f64)` and
/// `std.math.inf(f64)` return. Those are comptime loops, and every Instance
/// field default is evaluated in one comptime context, so a device with
/// ~140 timer/setup defaults exceeded the 1000-branch quota.
pub const nan_lit = "@as(f64, @bitCast(@as(u64, 0x7ff8000000000000)))";
pub const inf_lit = "@as(f64, @bitCast(@as(u64, 0x7ff0000000000000)))";

/// The device.zig header: the generated-file banner and its imports.
pub const header_txt =
    \\// GENERATED BY VerA — DO NOT EDIT.
    \\// The model is ONE declaration; its name is the structural key from
    \\// naming.zig, so an unchanged model is byte-identical across rebuilds and
    \\// `zig -fincremental` skips it.
    \\
    \\const std = @import("std");
    \\const contract = @import("contract");
    \\const Self = @This();
    \\
    \\
;

/// LRM Tables 4-14/4-15 in value form: every function the scalar family does
/// not provide (`contract.family_primitives`) is composed from the ones it
/// does, so forward-mode autodiff carries the analytic derivative.
/// File-scope helpers run in the default (strict) float mode, since
/// `@setFloatMode` does not cross a call: a `.optimized` unit loses fast-math
/// inside a helper and never gains unsound fast-math.
pub const math_txt =
    \\// ---- §4.3 math, value form (derivative propagates by composition) ----
    \\
    \\// §4.3.1 defines the derivative at equality using strict comparisons:
    \\// min(a,b) = (a < b) ? a : b; max(a,b) = (a > b) ? a : b.
    \\// Compose the contract's masks and winner-derivative selection rather
    \\// than inheriting a host min/max primitive's possibly different tie rule.
    \\fn zMin(comptime S: type, a: S, b: S) S { return a.lt(b).sel(a, b); }
    \\fn zMax(comptime S: type, a: S, b: S) S { return b.lt(a).sel(a, b); }
    \\
    \\// ---- per-operating-point decisions (`batch_lead`, contract.zig) ----
    \\// A real compared, rounded to an integer or stripped of its lanes is one
    \\// decision per call. A scalar family has one operating point and these
    \\// are the plain value forms. A batch family (`V` a vector of points)
    \\// implements the lead protocol: the leader point decides, every other
    \\// point that would have decided otherwise is marked diverged, and the
    \\// entry points re-run until every point has run on its own path.
    \\fn zCmp(comptime S: type, comptime op: std.math.CompareOperator, a: anytype, b: anytype) bool {
    \\    if (comptime @hasDecl(S, "decide")) return S.decide(op, a, b);
    \\    return std.math.compare(a.val(), op, b.val());
    \\}
    \\fn zRoundI(comptime S: type, a: anytype) i64 {
    \\    if (comptime @hasDecl(S, "decideI")) return S.decideI(a);
    \\    return std.math.lossyCast(i64, @round(a.val()));
    \\}
    \\fn zStrip(comptime S: type, a: anytype) @TypeOf(S.con(0.0)) {
    \\    if (comptime @hasDecl(S, "strip")) return S.strip(a);
    \\    return S.con(a.val());
    \\}
    \\/// `a * k`, `a + k`, `a - k` for a derivative-free `k` that differs per
    \\/// point: `scale`/`addC` of its value in a one-point family, which is
    \\/// what the device always emitted; in a batch, the same arithmetic per
    \\/// point (`sub` of `-k` keeps a -0 lane that `add` of a zero lane would not).
    \\fn zMulP(comptime S: type, a: anytype, k: anytype) @TypeOf(a) {
    \\    if (comptime @typeInfo(S.V) == .vector) return a.mul(k);
    \\    return a.scale(k.val());
    \\}
    \\fn zAddP(comptime S: type, a: anytype, k: anytype) @TypeOf(a) {
    \\    if (comptime @typeInfo(S.V) == .vector) return a.sub(k.neg());
    \\    return a.addC(k.val());
    \\}
    \\fn zSubP(comptime S: type, a: anytype, k: anytype) @TypeOf(a) {
    \\    if (comptime @typeInfo(S.V) == .vector) return a.sub(k);
    \\    return a.addC(-(k.val()));
    \\}
    \\/// Field `f` of the `Instance`, as a value: per point in a batch, whose
    \\/// points each have their own instance (`S.instLane(T, w)`, contract.zig
    \\/// `batch_inst`); a one-point family reads `inst`.
    \\fn zInst(comptime S: type, inst: anytype, comptime f: []const u8) @TypeOf(S.con(0.0)) {
    \\    if (comptime contract.instLanes(S)) {
    \\        var ls: [S.lane_count]@TypeOf(S.Lane.con(0.0)) = undefined;
    \\        inline for (0..S.lane_count) |w| ls[w] = S.Lane.con(@field(S.instLane(@TypeOf(inst.*), w), f));
    \\        return S.fromLanes(0, ls);
    \\    }
    \\    return S.con(@field(inst, f));
    \\}
    \\/// Integer field `f` of the `Instance`: one value per call, so in a batch
    \\/// a decision (the lead protocol) over each point's own instance.
    \\fn zInstI(comptime S: type, inst: anytype, comptime f: []const u8) i64 {
    \\    if (comptime contract.instLanes(S)) {
    \\        var ls: [S.lane_count]@TypeOf(S.Lane.con(0.0)) = undefined;
    \\        inline for (0..S.lane_count) |w| ls[w] = S.Lane.con(@floatFromInt(@field(S.instLane(@TypeOf(inst.*), w), f)));
    \\        return S.decideI(S.fromLanes(0, ls));
    \\    }
    \\    if (comptime @hasDecl(S, "decideI")) return S.decideI(S.con(@floatFromInt(@field(inst, f)))); // `region` hashes it
    \\    return @field(inst, f);
    \\}
    \\/// Whether `S` runs the lead protocol; a vector family that cannot is
    \\/// refused, since its points would follow point 0's branches.
    \\fn zLeads(comptime S: type) bool {
    \\    return contract.leads(S);
    \\}
    \\
    \\/// Device-routed f64 transcendentals for the SCALAR paths (the
    \\/// §4.5.15 limiters, zLimexp's clamp constant). Generated devices also
    \\/// compile for NVPTX/AMDGCN (the engine's GPU eval and StateKernel), and
    \\/// those targets have no libm — `@exp`/`@log` on an f64 die at PTX
    \\/// assembly with "no libcall available for fexp". `contract.gm`'s host
    \\/// branch IS the builtin, so host emission is numerically unchanged; its
    \\/// device branch is a self-contained soft port. sin/cos joined when the
    \\/// bjt reached tan through the StateKernel's scalar core (`fsin` cannot
    \\/// select on NVPTX); log1p stays on std.math (pure Zig).
    \\///
    \\/// expm1 and atan are routed too, and NOT for a missing libcall -- NVPTX
    \\/// takes both. Both raise the subnormal underflow flag through
    \\/// `std.mem.doNotOptimizeAway`, which for a float is
    \\/// `asm volatile ("" :: "rm" (v))`, and AMDGPU cannot match the `m`
    \\/// alternative: "Could not match memory address. Inline asm failure!".
    \\/// AMD-only, so a CUDA-only check never sees it.
    \\inline fn zDevExp(x: f64) f64 {
    \\    return contract.gm.exp(x);
    \\}
    \\inline fn zDevExpm1(x: f64) f64 {
    \\    return contract.gm.expm1(x);
    \\}
    \\inline fn zDevAtan(x: f64) f64 {
    \\    return contract.gm.atan(x);
    \\}
    \\inline fn zDevLog(x: f64) f64 {
    \\    return contract.gm.log(x);
    \\}
    \\inline fn zDevPow(x: f64, y: f64) f64 {
    \\    return contract.gm.pow(x, y);
    \\}
    \\inline fn zDevSin(x: f64) f64 {
    \\    return contract.gm.sin(x);
    \\}
    \\inline fn zDevCos(x: f64) f64 {
    \\    return contract.gm.cos(x);
    \\}
    \\inline fn zDevTanh(x: f64) f64 {
    \\    return contract.gm.tanh(x);
    \\}
    \\inline fn zDevSinh(x: f64) f64 {
    \\    return contract.gm.sinh(x);
    \\}
    \\inline fn zDevCosh(x: f64) f64 {
    \\    return contract.gm.cosh(x);
    \\}
    \\
    \\fn zTan(comptime S: type, a: S) S { // §4.3.2 tan = sin/cos
    \\    return a.sin().div(a.cos());
    \\}
    \\fn zLog10(comptime S: type, a: S) S { // §4.3.1 log() is base 10
    \\    return a.log().scale(0.4342944819032518);
    \\}
    \\/// §4.3.1 Table 4-14 hypot names the C library function, which is
    \\/// overflow-free — a²+b² composed in S overflowed for legs ≳1e154. The
    \\/// value is the libm one; the derivative (a/h)·da + (b/h)·db is grafted on
    \\/// through zero-valued carriers, `a.addC(-av)` being an S whose VALUE is
    \\/// exactly 0 and whose derivative is da — the same idiom the §12.32 systf
    \\/// reassembly uses. Guarded: at h = 0 hypot has no derivative (a cone tip),
    \\/// and a non-finite h has no slope worth propagating.
    \\fn zHypot(comptime S: type, a: S, b: S) S {
    \\    const av = a.val();
    \\    const bv = b.val();
    \\    const h = std.math.hypot(av, bv);
    \\    var r = S.con(h);
    \\    if (h != 0.0 and std.math.isFinite(h))
    \\        r = r.add(a.addC(-av).scale(av / h)).add(b.addC(-bv).scale(bv / h));
    \\    return r;
    \\}
    \\fn zAsin(comptime S: type, a: S) S { // §4.3.2 asin = atan(x/sqrt(1-x^2))
    \\    const v = a.val();
    \\    zDomain("asin", "-1 <= x <= 1", v, v >= -1.0 and v <= 1.0);
    \\    return a.div(a.mul(a).neg().addC(1.0).sqrt()).atan();
    \\}
    \\fn zAcos(comptime S: type, a: S) S { // §4.3.2
    \\    const v = a.val();
    \\    zDomain("acos", "-1 <= x <= 1", v, v >= -1.0 and v <= 1.0);
    \\    return S.con(1.5707963267948966).sub(zAsin(S, a));
    \\}
    \\fn zAsinh(comptime S: type, a: S) S { // §4.3.2 ln(x + sqrt(x^2+1))
    \\    return a.add(a.mul(a).addC(1.0).sqrt()).log();
    \\}
    \\fn zAcosh(comptime S: type, a: S) S { // §4.3.2 ln(x + sqrt(x^2-1))
    \\    const v = a.val();
    \\    zDomain("acosh", "x >= 1", v, v >= 1.0);
    \\    return a.add(a.mul(a).addC(-1.0).sqrt()).log();
    \\}
    \\fn zAtanh(comptime S: type, a: S) S { // §4.3.2 0.5*ln((1+x)/(1-x))
    \\    const v = a.val();
    \\    zDomain("atanh", "-1 < x < 1", v, v > -1.0 and v < 1.0);
    \\    return a.addC(1.0).div(a.neg().addC(1.0)).log().scale(0.5);
    \\}
    \\fn zAtan2(comptime S: type, y: S, x: S) S { // §4.3.2
    \\    // Value-level branch only: every arm is atan(y/x) plus a CONSTANT, so
    \\    // each arm carries the exact derivative of atan2 on its quadrant.
    \\    const xv = x.val();
    \\    if (xv > 0.0) return y.div(x).atan();
    \\    if (xv < 0.0) {
    \\        const c: f64 = if (y.val() >= 0.0) 3.141592653589793 else -3.141592653589793;
    \\        return y.div(x).atan().addC(c);
    \\    }
    \\    const yv = y.val();
    \\    return S.con(if (yv > 0.0) 1.5707963267948966 else if (yv < 0.0) -1.5707963267948966 else 0.0);
    \\}
    \\fn zFloor(comptime S: type, a: S) S { // §4.3.1 — derivative 0 a.e.
    \\    return S.con(@floor(a.val()));
    \\}
    \\fn zCeil(comptime S: type, a: S) S { // §4.3.1 — derivative 0 a.e.
    \\    return S.con(@ceil(a.val()));
    \\}
    \\/// §4.2.4 `%` keeps the sign of the first operand — C's fmod, which `@rem`
    \\/// on f64 is, EXACTLY. The composed `a − b·trunc(a/b)` this replaces lost
    \\/// the whole remainder to the subtraction's rounding once |a| ≳ 2^53·|b|.
    \\/// The derivative treatment is unchanged (k = trunc(a/b) is constant a.e.,
    \\/// so d = da − k·db), carried by zero-valued grafts so the exact value
    \\/// survives; a non-finite k (b = 0, or a/b overflowed) has no slope worth
    \\/// propagating and degrades to da alone.
    \\fn zFmod(comptime S: type, a: S, b: S) S {
    \\    const av = a.val();
    \\    const bv = b.val();
    \\    const k = @trunc(av / bv);
    \\    var r = S.con(@rem(av, bv)).add(a.addC(-av));
    \\    if (std.math.isFinite(k)) r = r.sub(b.addC(-bv).scale(k));
    \\    return r;
    \\}
    \\/// §4.3.1 pow with a non-constant exponent. The exp(y·ln x) composition
    \\/// this replaces was NaN on the clause's own legal domain "if x < 0, all
    \\/// integer y". The value is S's own pow, which handles the negative-base
    \\/// integral-y sign itself; the derivatives are grafted on zero-valued
    \\/// carriers:
    \\///   ∂/∂x = y·x^(y−1)  — valid for x > 0 and for integral y of either sign;
    \\///   ∂/∂y = x^y·ln(x)  — only for x > 0. For x ≤ 0 the legal y move in
    \\///   integer steps, so no continuous ∂/∂y exists and 0 is the honest slope.
    \\/// Non-finite slopes (x = 0 with y < 1, domain-error NaNs) are dropped the
    \\/// same way zHypot drops its cone tip.
    \\/// Both transcendentals go through `S.con(x)`, not `std.math.pow` and
    \\/// `@log`, for the reason `devSafe` exists: a unit body also compiles
    \\/// for nvptx, which has no libm, and a raw one is "no libcall available
    \\/// for flog/fexp" at PTX assembly. On a host S it is the same libm call,
    \\/// bit for bit, and the zero-derivative carriers fold away.
    \\fn zPow(comptime S: type, a: S, b: S, comptime varying_exponent: bool) S {
    \\    const x = a.val();
    \\    const y = b.val();
    \\    const v = S.con(x).pow(y).val();
    \\    // y·x^(y−1) = y·v/x — algebraically exact for x != 0, the negative-base
    \\    // integral-y clause included, and ONE pow instead of two. A second
    \\    // `S.con(x).pow(y - 1.0)` was half of the 828k pow calls on
    \\    // tran/fourbitadder and half of the 51% of instructions mos6_inverter
    \\    // spent under pow (callgrind, 2026-09-07): every junction exponent in
    \\    // every SPICE model is a model PARAMETER, so codegen's `.pow` arm sends
    \\    // all of them here rather than down `Dual.pow`'s own c·p/x.
    \\    //
    \\    // x == 0 keeps the second pow, and is NOT a rounding concern: at y == 1
    \\    // the true slope is 1, but v/x is 0/0 = NaN and the gate below would
    \\    // drop the term and flatten the Jacobian row. `mjs` defaults to 0 in
    \\    // bjt.va, so `1 - mjs` is exactly that exponent and the substrate base
    \\    // `1 - v/ps` reaches exactly 0 at v == ps. The branch is never taken on
    \\    // a normal bias point, so the hot path is still one pow, and where it
    \\    // IS taken the expression is the old one character for character.
    \\    // Elsewhere the two forms sit within 6 ulp of a 60-digit reference and
    \\    // neither is uniformly closer; the result is a Jacobian entry, and
    \\    // Newton converges to the accuracy of the RESIDUAL.
    \\    const gx = if (x != 0.0) y * v / x else y * S.con(x).pow(y - 1.0).val();
    \\    const gy: f64 = if (varying_exponent and x > 0.0) v * S.con(x).log().val() else 0.0;
    \\    var r = S.con(v);
    \\    if (std.math.isFinite(gx) and gx != 0.0) r = r.add(a.addC(-x).scale(gx));
    \\    if (std.math.isFinite(gy) and gy != 0.0) r = r.add(b.addC(-y).scale(gy));
    \\    return r;
    \\}
    \\/// §9.17.3 `$limit(access, user_function, args…)`: the value is what the
    \\/// user limiter returned, the DERIVATIVE is the access function's.
    \\///
    \\/// SPICE evaluates the device at the limited bias and stamps
    \\/// `I(vlim) + g(vlim)·(v − vlim)`, so the residual stays linear in the
    \\/// true unknown past the clamp point and the Jacobian entry never
    \\/// vanishes. Differentiating the limiter instead gives dv_lim/dv = 0
    \\/// inside the clamped region — a device contributing no conductance,
    \\/// which is a singular row for a floating internal node. So: shift the
    \\/// probe by the constant the clamp moved it, rather than replace it.
    \\fn zLimitUf(comptime S: type, vnew: S, vlim: S) S {
    \\    return vnew.addC(vlim.val() - vnew.val());
    \\}
    \\fn zIabs(a: i64) i64 { // §4.3.1 integer abs, §3.2's 32-bit result
    \\    return @as(i32, @truncate(if (a < 0) -%a else a));
    \\}
    \\/// §4.2.11 the shift COUNT reads as unsigned: a negative i64 count is a
    \\/// reinterpreted value ≥ 2^63, which vacates every one of §3.2.1's 32 bits
    \\/// — so the answer is 0, exactly like any other over-wide count. Without
    \\/// the guard `std.math.shl`/`shr` take a negative count as "shift the
    \\/// OTHER way" (8 << -1 came out 4, 8 >> -1 came out 16). Positive counts
    \\/// keep the std functions' verified over-wide-is-0 semantics untouched.
    \\fn zShl(a: i64, n: i64) i64 {
    \\    return if (n < 0) 0 else std.math.shl(i64, a, n);
    \\}
    \\fn zShr(a: i64, n: i64) i64 {
    \\    if (n == 0) return a; // preserve signed/unsigned operand identity
    \\    const bits: u32 = @bitCast(@as(i32, @truncate(a)));
    \\    return if (n < 0) 0 else std.math.shr(u32, bits, n);
    \\}
    \\fn zClog2(a: i64, width: i64) i64 { // §9.14 / IEEE 1364-2005 §17.11.1
    \\    if (width > 64 and a < 0) return width;
    \\    const mask: u64 = if (width >= 64) std.math.maxInt(u64) else (@as(u64, 1) << @intCast(width)) - 1;
    \\    const bits = @as(u64, @bitCast(a)) & mask;
    \\    return if (bits <= 1) 0 else 64 - @as(i64, @clz(bits - 1));
    \\}
    \\fn zStrCmp(a: []const u8, b: []const u8) i64 { // §3.3.1 string relations
    \\    return switch (std.mem.order(u8, a, b)) { .lt => -1, .eq => 0, .gt => 1 };
    \\}
    \\fn zLimexp(comptime S: type, a: S) S { // §4.5.13 — user-invoked ONLY
    \\    const lim = 80.0;
    \\    if (a.val() > lim) return a.addC(1.0 - lim).scale(zDevExp(lim));
    \\    return a.exp();
    \\}
    \\
    \\
;

/// `zDomain` for a solver device: an empty guard. §4.3.2: "Input values
/// outside of the valid range for the operator shall report an error."
/// `proof.checkDomain` refuses what it can prove from the source
/// (E0605/E0606/E0607); `math_txt`'s restricted-domain functions call
/// `zDomain` for the rest. A device has no transcript (it also compiles for
/// NVPTX), so only the executable reports; one call site keeps both artifacts
/// agreeing on which values are out of range.
pub const domain_quiet_txt =
    \\fn zDomain(comptime _: []const u8, comptime _: []const u8, _: f64, _: bool) void {}
    \\
    \\
;

/// `zDomain` for the printing executable: reports and stops, on the §9.21.2
/// `E` precedent, since the clause names no in-range value and libm's quiet
/// NaN would look like a converged answer. A NaN argument reports too. `tan`
/// is unguarded: its poles are irrational, so no f64 is ever at one.
pub const domain_report_txt =
    \\fn zDomain(comptime name: []const u8, comptime rule: []const u8, x: f64, in_range: bool) void {
    \\    if (in_range) return;
    \\    std.debug.print(
    \\        "error: LRM 4.3.2: " ++ name ++ "() input value is outside the valid range " ++ rule ++ ": {d}\n",
    \\        .{x},
    \\    );
    \\    std.process.exit(1);
    \\}
    \\
    \\
;

/// The scalar-family helpers (`codegen/family.zig`), emitted after `ops_txt`:
/// how every body and kernel reaches a family. Masks are narrowed by `zdr`,
/// the device's `deriv_reads` (declared by `family_dev_txt` in device.zig and
/// by the `h.zig` head), so no mask names a lane the host did not ask for.
pub const family_txt =
    \\// ---- the scalar family (`contract.family_fns`) ----
    \\//
    \\// A real is typed `zOf(S, m)`, `m` the unknowns it may depend on.
    \\
    \\fn zOf(comptime S: type, comptime m: u64) type {
    \\    @setEvalBranchQuota(1_000_000);
    \\    return S.Of(m & zdr);
    \\}
    \\/// `a` widened to `zOf(S, m)`: a compile error when `a` carries a lane
    \\/// `m` does not name.
    \\fn zTo(comptime S: type, comptime m: u64, a: anytype) zOf(S, m) {
    \\    return a.to(m & zdr);
    \\}
    \\fn zV(a: anytype) f64 {
    \\    return a.val();
    \\}
    \\/// §4.3.1 "abs(x) is equivalent to (x > 0) x : -x": a family carries no
    \\/// `abs`, so the conditional is spelled here.
    \\fn zAbs(comptime S: type, a: anytype) @TypeOf(a) {
    \\    return S.sel(S.con(0.0).lt(a), a, a.neg());
    \\}
    \\/// `zOf(S, m)` as one scalar type, for the kernels above, which are
    \\/// written against one: every operation of the kernel runs at mask `m`.
    \\/// min, max, abs and the slew clamps are §4.3.1's conditionals.
    \\fn zL(comptime S: type, comptime m: u64) type {
    \\    return struct {
    \\        v: zOf(S, m),
    \\        const T = @This();
    \\        fn w(a: anytype) T { return .{ .v = zTo(S, m, a) }; }
    \\        pub fn con(c: f64) T { return w(S.con(c)); }
    \\        pub fn val(a: T) f64 { return a.v.val(); }
    \\        pub fn ddxAt(a: T, comptime u: usize) f64 { return a.v.ddxAt(u); }
    \\        pub fn add(a: T, b: T) T { return .{ .v = a.v.add(b.v) }; }
    \\        pub fn sub(a: T, b: T) T { return .{ .v = a.v.sub(b.v) }; }
    \\        pub fn mul(a: T, b: T) T { return .{ .v = a.v.mul(b.v) }; }
    \\        pub fn div(a: T, b: T) T { return .{ .v = a.v.div(b.v) }; }
    \\        pub fn neg(a: T) T { return .{ .v = a.v.neg() }; }
    \\        pub fn scale(a: T, c: f64) T { return .{ .v = a.v.scale(c) }; }
    \\        pub fn addC(a: T, c: f64) T { return .{ .v = a.v.addC(c) }; }
    \\        pub fn exp(a: T) T { return .{ .v = a.v.exp() }; }
    \\        pub fn log(a: T) T { return .{ .v = a.v.log() }; }
    \\        pub fn expm1(a: T) T { return .{ .v = a.v.expm1() }; }
    \\        pub fn log1p(a: T) T { return .{ .v = a.v.log1p() }; }
    \\        pub fn sqrt(a: T) T { return .{ .v = a.v.sqrt() }; }
    \\        pub fn sin(a: T) T { return .{ .v = a.v.sin() }; }
    \\        pub fn cos(a: T) T { return .{ .v = a.v.cos() }; }
    \\        pub fn tanh(a: T) T { return .{ .v = a.v.tanh() }; }
    \\        pub fn sinh(a: T) T { return .{ .v = a.v.sinh() }; }
    \\        pub fn cosh(a: T) T { return .{ .v = a.v.cosh() }; }
    \\        pub fn atan(a: T) T { return .{ .v = a.v.atan() }; }
    \\        pub fn pow(a: T, c: f64) T { return .{ .v = a.v.pow(c) }; }
    \\        pub fn lt(a: T, b: T) T { return w(a.v.lt(b.v)); }
    \\        pub fn le(a: T, b: T) T { return w(a.v.le(b.v)); }
    \\        pub fn eq(a: T, b: T) T { return w(a.v.eq(b.v)); }
    \\        pub fn sel(c: T, a: T, b: T) T { return .{ .v = S.sel(c.v, a.v, b.v) }; }
    \\        pub fn min(a: T, b: T) T { return a.lt(b).sel(a, b); }
    \\        pub fn max(a: T, b: T) T { return b.lt(a).sel(a, b); }
    \\        pub fn abs(a: T) T { return con(0.0).lt(a).sel(a, a.neg()); }
    \\        pub fn minC(a: T, c: f64) T { return con(c).lt(a).sel(con(c), a); }
    \\        pub fn maxC(a: T, c: f64) T { return a.lt(con(c)).sel(con(c), a); }
    \\    };
    \\}
    \\/// `zPow` at mask `m`; a batch family (`batch_lead`) runs it once per
    \\/// point on its scalar `Lane` family, since it steers on both values.
    \\fn zPowL(comptime S: type, comptime m: u64, a: zOf(S, m), b: zOf(S, m), comptime ve: bool) zOf(S, m) {
    \\    if (comptime @hasDecl(S, "Lane")) {
    \\        var ls: [S.lane_count]zOf(S.Lane, m) = undefined;
    \\        inline for (0..S.lane_count) |w| ls[w] = zPowL(S.Lane, m, S.laneOf(a, w), S.laneOf(b, w), ve);
    \\        return S.fromLanes(m & zdr, ls);
    \\    }
    \\    return zLu(S, m, zPow(zL(S, m), zLw(S, m, a), zLw(S, m, b), ve));
    \\}
    \\fn zLw(comptime S: type, comptime m: u64, a: anytype) zL(S, m) {
    \\    return .{ .v = zTo(S, m, a) };
    \\}
    \\fn zLu(comptime S: type, comptime m: u64, a: zL(S, m)) zOf(S, m) {
    \\    return a.v;
    \\}
    \\
    \\
;

/// device.zig's half of the family helpers: `zdr`, a row as the family
/// returns it, and the unknowns an entry point hands its core.
pub const family_dev_txt =
    \\const zdr = contract.derivReads(Self);
    \\fn zRow(comptime S: type, comptime r: U, a: anytype) zOf(S, contract.rowMask(Self, @intFromEnum(r))) {
    \\    return zTo(S, contract.rowMask(Self, @intFromEnum(r)), a);
    \\}
    \\fn zRowsZero(comptime S: type) contract.Rows(Self, S) {
    \\    var r: contract.Rows(Self, S) = undefined;
    \\    inline for (0..n_u) |u| r[u] = zTo(S, contract.rowMask(Self, u), S.con(0.0));
    \\    return r;
    \\}
    \\/// The unknowns as an entry point's core reads them: a probe for each
    \\/// lane the device reads, a constant for every other.
    \\fn zX(comptime S: type) type {
    \\    @setEvalBranchQuota(1_000_000);
    \\    var ts: [n_u]type = undefined;
    \\    for (&ts, 0..) |*t, u| t.* = zOf(S, if (u < 64) @as(u64, 1) << u else ~@as(u64, 0));
    \\    return @Tuple(&ts);
    \\}
    \\fn zProbe(comptime S: type, x: *const [n_u]S.V) zX(S) {
    \\    var p: zX(S) = undefined;
    \\    inline for (0..n_u) |u| p[u] = if (comptime u >= 64 or (zdr >> u) & 1 != 0) S.probe(u, x[u]) else if (S.V == f64) S.con(x[u]) else S.lift(x[u]);
    \\    return p;
    \\}
    \\/// The unknowns as values only, for the entry points that read the core
    \\/// without lanes.
    \\fn zVals(comptime S: type, x: *const [n_u]f64) [n_u]zOf(S, 0) {
    \\    var p: [n_u]zOf(S, 0) = undefined;
    \\    for (&p, x) |*o, v| o.* = S.con(v);
    \\    return p;
    \\}
    \\
    \\
;

/// The §4.5 operator kernels. Each takes the current S-valued input plus the
/// accepted state, so the companion model's Jacobian is analytic.
pub const ops_txt =
    \\// ---- §4.5 analog operator kernels ----
    \\
    \\fn zIdt(comptime S: type, v: S, acc: f64, dt: f64, ic: f64) S { // §4.5.4
    \\    if (dt <= 0.0) return S.con(ic); // §4.5.4 DC value is the initial condition
    \\    return v.scale(dt).addC(acc);
    \\}
    \\fn zIdtHold(comptime S: type, v: S, off: f64, ic: f64, assert_: f64) S { // §4.5.4
    \\    // "idt() returns the initial conditions ... whenever assert is nonzero."
    \\    if (assert_ != 0.0) return S.con(ic);
    \\    return v.addC(-off);
    \\}
    \\fn zIdtAcc(v: f64, acc: f64, dt: f64, ic: f64) f64 {
    \\    if (dt <= 0.0) return ic;
    \\    return acc + v * dt;
    \\}
    \\fn zIdtmod(comptime S: type, v: S, acc: f64, dt: f64, ic: f64, m: f64, o: f64) S { // §4.5.5
    \\    const raw = zIdt(S, v, acc, dt, ic);
    \\    if (!(m > 0.0)) return raw;
    \\    // The wrap subtracts a piecewise-CONSTANT multiple of the modulus, so
    \\    // the derivative of the wrapped integral is the derivative of the raw one.
    \\    return raw.addC(-m * @floor((raw.val() - o) / m));
    \\}
    \\fn zWrap(x: f64, modulus: f64, offset: f64) f64 { // §4.5.5 idtmod
    \\    if (!(modulus > 0.0)) return x;
    \\    return x - modulus * @floor((x - offset) / modulus);
    \\}
    \\fn zSlew(comptime S: type, v: S, prev: f64, dt: f64, rise: f64, fall: f64) S { // §4.5.9
    \\    if (dt <= 0.0) return v;
    \\    return v.minC(prev + rise * dt).maxC(prev - fall * dt);
    \\}
    \\/// §5.10.3.1/§4.5.10 the crossing test for a direction that is a PARAMETER
    \\/// (a constant_expression the model card owns, so codegen cannot pick the
    \\/// comparison at emit time): +1 rising only, -1 falling only, anything
    \\/// else either — the EXACT decode `Gen.crossTest` applies to a folded one,
    \\/// so overriding the parameter to the value the default had changes nothing.
    \\fn zCrossDir(dir: f64, prev: f64, in: f64) bool {
    \\    if (dir == 1.0) return prev <= 0.0 and in > 0.0;
    \\    if (dir == -1.0) return prev >= 0.0 and in < 0.0;
    \\    if (dir != 0.0) return false; // §5.10.3.1 any other dir disables cross()
    \\    return (prev <= 0.0 and in > 0.0) or (prev >= 0.0 and in < 0.0);
    \\}
    \\/// §4.5.8 the fraction of the current excursion the ramp has traversed.
    \\/// "transition() forces all positive transitions of expr to occur over
    \\/// rise_time and all negative transitions to occur in fall_time", and the
    \\/// result "describes a piecewise linear function over time" — so the shape
    \\/// is (t - t0)/tt clamped into [0, 1], with tt picked by the DIRECTION of
    \\/// the excursion and t0 the time the excursion began.
    \\///
    \\/// A zero transition time is §4.5.8's own degenerate case ("If neither
    \\/// rise_time nor fall_time are specified or are equal to zero (0.0) …"),
    \\/// left to `default_transition and, with no directive, to the simulator:
    \\/// here that is an instantaneous edge, fraction 1.
    \\fn zTransFrac(target: f64, from: f64, t0: f64, t: f64, rise: f64, fall: f64) f64 {
    \\    const tt = if (target >= from) rise else fall;
    \\    if (!(tt > 0.0)) return 1.0;
    \\    return @min(@max((t - t0) / tt, 0.0), 1.0);
    \\}
    \\fn zTransition(comptime S: type, v: S, from: f64, to: f64, t0: f64, t: f64, dt: f64, rise: f64, fall: f64) S { // §4.5.8
    \\    // "In DC analysis, transition() passes the value of the expr directly
    \\    // to its output." There is no elapsed time to ramp over.
    \\    if (dt <= 0.0) return v;
    \\    // In a transient the output is a function of the input's PAST alone:
    \\    // the excursion in flight was armed by the accepted step that SAW the
    \\    // input change, "after an initial delay of td". Taking the CURRENT
    \\    // input as the ramp's target — which this did — armed every ramp at the
    \\    // previous accepted timepoint, so the output was already part-way up it
    \\    // at the corner itself and no td could have shifted that.
    \\    return S.con(from + (to - from) * zTransFrac(to, from, t0, t, rise, fall));
    \\}
    \\/// §4.5.8 accepted-step bookkeeping. "A transition is created when the
    \\/// input expression changes, and at this point it uses the value of td,
    \\/// rise_time, fall_time and time_tol to determine the new pending
    \\/// transition operator." `to` is the armed destination and so also the last
    \\/// ACCEPTED input, which makes `in != to` that sentence's test.
    \\///
    \\/// LEAVING THE EXCURSION ALONE is the important half: while the input has
    \\/// not changed the excursion is the one that started at `from`, and
    \\/// re-arming the origin every step would shrink the remaining distance by
    \\/// the same factor each time — an exponential decay wearing a ramp's
    \\/// coefficients, which is the bug this operator used to have.
    \\fn zTransStep(in: f64, from: *f64, to: *f64, t0: *f64, t: f64, dt: f64, td: f64, rise: f64, fall: f64) void {
    \\    if (dt <= 0.0) { // the DC point: the output IS the input, so sit on it
    \\        from.* = in;
    \\        to.* = in;
    \\        t0.* = t;
    \\        return;
    \\    }
    \\    if (in == to.*) return;
    \\    // "td models transport delay": the ramp begins td after the change and
    \\    // the output stays on its old trajectory until then, so it leaves from
    \\    // where that trajectory will be at t + td, not from where it is now.
    \\    const te = t + td;
    \\    const f = zTransFrac(to.*, from.*, t0.*, te, rise, fall);
    \\    const vi = from.* + (to.* - from.*) * f;
    \\    // §4.5.8's four interruption paragraphs (Figures 4-7 … 4-12): an input
    \\    // that changes inside the active region is "not ... a new transition,
    \\    // but rather a readjustment", whose slope uses "either the original
    \\    // transition's origin or destination as the new origin". One rule, four
    \\    // figures — the reference is the DESTINATION when the new direction
    \\    // opposes the original and the ORIGIN when it agrees:
    \\    //   rising,  v3 < vi -> opposes -> (v3-v2)/tf3    rising,  v3 > vi -> (v3-v1)/tr3
    \\    //   falling, v3 > vi -> opposes -> (v3-v2)/tr3    falling, v3 < vi -> (v3-v1)/tf3
    \\    // "applied from the point of interruption (ti,vi)", spelled here as the
    \\    // shifted origin (t4,v4) those paragraphs also name: v4 is the reference
    \\    // level, t4 where the slope line through (te,vi) reaches it. The arrival
    \\    // t3 = ti + (v3-vi)/slope then falls out of zTransFrac.
    \\    //
    \\    // NOT active is a new transition from where the output is — the branch
    \\    // this took unconditionally, which is the reading the four paragraphs
    \\    // exist to rule out.
    \\    if (f < 1.0 and in != vi) {
    \\        const tt3 = if (in > vi) rise else fall;
    \\        const vref = if ((in > vi) != (to.* > from.*)) to.* else from.*;
    \\        const slope = if (tt3 > 0.0) (in - vref) / tt3 else 0.0;
    \\        if (slope != 0.0) {
    \\            from.* = vref;
    \\            to.* = in;
    \\            t0.* = te + (vref - vi) / slope;
    \\            return;
    \\        }
    \\    }
    \\    from.* = vi;
    \\    to.* = in;
    \\    t0.* = te;
    \\}
    \\
;

/// VerA's `vera_timepoint` cache key. Emitted only for a device with one
/// (`Lowered.timepoints`).
pub const tp_txt =
    \\// ---- VerA's `vera_timepoint` (§2.9) cache key ----
    \\
    \\/// What a per-timepoint cache is keyed on beside `sim.t`: the analysis
    \\/// (§4.6.1) and the two §5.10.2 step flags, which a statement may read
    \\/// through a variable assigned under them.
    \\fn zTpKey(sim: contract.SimState) u8 {
    \\    return @intFromEnum(sim.kind) | @as(u8, @intFromBool(sim.initial_step)) << 4 | @as(u8, @intFromBool(sim.final_step)) << 5;
    \\}
    \\
    \\/// Is a cache filled at `t` under key `k` current for `sim`? A dropped
    \\/// cache holds NaN, which equals nothing.
    \\fn zTpHit(t: f64, k: u8, sim: contract.SimState) bool {
    \\    return t == sim.t and k == zTpKey(sim);
    \\}
    \\
;

/// §5.10.3.3 timer scheduling, shared with the mixed coordinator.
pub const timer_txt = "// ---- §5.10.3.3 timer schedule ----\n\n" ++
    timer_src[std.mem.indexOf(u8, timer_src, "\n\n").? + 2 ..];
// A file-level //! header cannot be spliced into the middle of device.zig.
const timer_src = @embedFile("../timer_kernels.zig");

/// §9.5.3/§9.5.4.2 the string formatter's scratch and the scanner, embedded
/// verbatim from `str_kernels.zig` so codegen's tests exercise the device's
/// own bytes. Carried by devices that format strings or print.
pub const str_txt = "// ---- §9.5.3/§9.5.4.2 string kernels (lib/backend/str_kernels.zig) ----\n\n" ++
    @embedFile("../str_kernels.zig");

/// §9.13 the probabilistic distribution kernels, embedded verbatim from
/// `rng_kernels.zig`. Carried only by devices that call a Table 9-10 function.
pub const rng_txt = "// ---- §9.13 probabilistic distribution kernels (lib/backend/rng_kernels.zig) ----\n\n" ++
    @embedFile("../rng_kernels.zig");

/// §9.21 the table-model interpolator, embedded verbatim from
/// `table_kernels.zig`. Carried only by devices that call `$table_model`.
pub const table_txt = "// ---- §9.21 table model kernels (lib/backend/table_kernels.zig) ----\n\n" ++
    @embedFile("../table_kernels.zig");

/// §9.5 the file-descriptor table and its operations, embedded verbatim from
/// `file_kernels.zig`. Carried only by a device that calls the family and is
/// built `display == .emit`, the artifact whose host runs side effects. A
/// solver device has no table, so §9.5.1's "a zero is returned for the mcd or
/// fd" is its answer to `$fopen`.
pub const file_txt = "// ---- §9.5 file descriptor I/O kernels (lib/backend/file_kernels.zig) ----\n\n" ++
    @embedFile("../file_kernels.zig");

/// §4.5.15 the SPICE limiters, embedded verbatim from `limit_kernels.zig`.
/// Carried only by a device with an honoured `$limit` call; no unit body
/// reaches them, since `$limit` renders as its probe there (`cg_limit.zig`).
pub const limit_txt = "// ---- §4.5.15 SPICE limiting kernels (lib/backend/limit_kernels.zig) ----\n\n" ++
    @embedFile("../limit_kernels.zig");

/// §4.5.11/§4.5.12 the filter kernels, embedded verbatim from
/// `filter_kernels.zig`. Carried only by devices that use a filter.
pub const filt_txt = "// ---- §4.5.11/§4.5.12 filter kernels (src/filter_kernels.zig) ----\n\n" ++
    @embedFile("../filter_kernels.zig");

/// The small-signal side of the operators whose response depends on frequency
/// (`ir.op.acDynamic`): §4.5.7 `absdelay`, §4.5.11 `laplace_*`, §4.5.12
/// `zi_*`. At a small-signal point `eval` keeps their value and drops their
/// lanes (`zSs`), and `acDyn` supplies those slots: it evaluates the core with
/// `zAc(F)` (`ac_fam_txt`), whose operators multiply the lanes by H(jω) here.
/// `K` is a kernel scalar, `zL(zAc(F), m)`; `F` is `f64` or a vector of
/// frequencies. At ω = 0 each H is computed in the order the DC branch scales
/// by, so `acDyn` reads back exactly the static partial.
pub const ac_txt =
    \\// ---- §4.5.7/§4.5.11/§4.5.12 small-signal response ----
    \\
    \\/// An operator's output as `eval` sees it: under `.ac`/`.noise` the value
    \\/// alone, since `acDyn` supplies the operator's slots whole.
    \\fn zSs(comptime K: type, kind: contract.AnalysisKind, y: K) K {
    \\    return if (kind == .ac or kind == .noise) K.con(y.val()) else y;
    \\}
    \\/// §4.5.7 "Output(ω) = Input(ω) · e^(−jωtd)".
    \\fn zAcDelay(comptime K: type, vin: K, td: f64) K {
    \\    const A = @TypeOf(vin.v);
    \\    const p = vin.v.omega() * A.splat(td);
    \\    return .{ .v = vin.v.acMul(vin.val(), .init(@cos(p), -@sin(p))) };
    \\}
    \\/// §4.5.11 the cascade at s = jω, one section at a time as `zLaplace`'s
    \\/// DC branch scales, so ω = 0 is that branch's H(0) to the bit. `h0` is
    \\/// `zLaplaceH0(sec)`, passed in because this text also serves devices
    \\/// with no filter kernels.
    \\fn zAcLaplace(comptime K: type, comptime NS: usize, comptime D: usize, uin: K, sec: [NS][2][D + 1]f64, h0: [NS][2]f64) K {
    \\    const A = @TypeOf(uin.v);
    \\    const s: std.math.Complex(A.F) = .init(A.splat(0.0), uin.v.omega());
    \\    var y = uin.v;
    \\    var v = uin.val();
    \\    for (sec, h0) |sc, h| {
    \\        v *= h[0] / h[1];
    \\        y = y.acMul(v, zCDiv(A.F, zPolyC(A.F, D, sc[0], s), zPolyC(A.F, D, sc[1], s)));
    \\    }
    \\    return .{ .v = y };
    \\}
    \\/// §4.5.12 the cascade on the unit circle, z = e^(jωT), one section at a
    \\/// time as `zZiEval`'s DC branch scales, so ω = 0 is its H(1) to the bit.
    \\fn zAcZi(comptime K: type, comptime NS: usize, comptime D: usize, uin: K, sec: [NS][2][D + 1]f64, period: f64) K {
    \\    const A = @TypeOf(uin.v);
    \\    const p = uin.v.omega() * A.splat(period);
    \\    const zinv: std.math.Complex(A.F) = .init(@cos(p), -@sin(p));
    \\    var y = uin.v;
    \\    var v = uin.val();
    \\    for (sec) |sc| {
    \\        var num: f64 = 0.0;
    \\        var den: f64 = 0.0;
    \\        for (sc[0]) |c| num += c;
    \\        for (sc[1]) |c| den += c;
    \\        v *= num / den;
    \\        y = y.acMul(v, zCDiv(A.F, zPolyC(A.F, D, sc[0], zinv), zPolyC(A.F, D, sc[1], zinv)));
    \\    }
    \\    return .{ .v = y };
    \\}
    \\/// Σ p[k]·c^k, summed from 0 in ascending k: at c = 0 it is p[0], and at
    \\/// c = 1 the DC branches' own sum.
    \\fn zPolyC(comptime F: type, comptime D: usize, p: [D + 1]f64, c: std.math.Complex(F)) std.math.Complex(F) {
    \\    const zero: F = if (@typeInfo(F) == .vector) @splat(0.0) else 0.0;
    \\    const one: F = if (@typeInfo(F) == .vector) @splat(1.0) else 1.0;
    \\    var acc: std.math.Complex(F) = .init(zero, zero);
    \\    var ck: std.math.Complex(F) = .init(one, zero);
    \\    for (p) |pk| {
    \\        const k: F = if (@typeInfo(F) == .vector) @splat(pk) else pk;
    \\        acc = acc.add(.init(ck.re * k, ck.im * k));
    \\        ck = ck.mul(c);
    \\    }
    \\    return acc;
    \\}
    \\/// a/b by Smith's rule, the lane's larger part of b as divisor: a real b
    \\/// gives a.re/b.re exactly, and |b|² is never formed.
    \\fn zCDiv(comptime F: type, a: std.math.Complex(F), b: std.math.Complex(F)) std.math.Complex(F) {
    \\    const r1 = b.im / b.re;
    \\    const d1 = b.re + b.im * r1;
    \\    const r2 = b.re / b.im;
    \\    const d2 = b.im + b.re * r2;
    \\    const big = @abs(b.re) >= @abs(b.im);
    \\    const re1 = (a.re + a.im * r1) / d1;
    \\    const im1 = (a.im - a.re * r1) / d1;
    \\    const re2 = (a.re * r2 + a.im) / d2;
    \\    const im2 = (a.im * r2 - a.re) / d2;
    \\    if (@typeInfo(F) == .vector) return .init(@select(f64, big, re1, re2), @select(f64, big, im1, im2));
    \\    return if (big) .init(re1, im1) else .init(re2, im2);
    \\}
    \\
    \\
;

/// `zAc`, the family `acDyn` evaluates the core with. device.zig only: no unit
/// names it, and it reads `n_u`.
pub const ac_fam_txt =
    \\/// A dense family whose lanes are three blocks: `n_u` direct partials, then
    \\/// the real and imaginary parts of `n_u` complex partials, each an `F` of
    \\/// frequencies. `w` points at the ω `acDyn` probed with. A probe seeds the
    \\/// direct block and every operation but `acMul` scales the blocks alike, so
    \\/// after the core the complex blocks hold exactly the Jacobian that flowed
    \\/// through a frequency-dependent operator, times that operator's H(jω).
    \\fn zAc(comptime Fw: type) type {
    \\    return struct {
    \\        pub const V = f64;
    \\        const W = if (@typeInfo(Fw) == .vector) @typeInfo(Fw).vector.len else 1;
    \\        const N = n_u * (1 + 2 * W);
    \\        const Lanes = @Vector(N, f64);
    \\        pub fn Of(comptime _: u64) type {
    \\            return T;
    \\        }
    \\        pub fn con(c: f64) T {
    \\            return .{ .v = c };
    \\        }
    \\        pub fn probe(comptime u: usize, v: f64) T {
    \\            var t: T = .{ .v = v };
    \\            t.d[u] = 1.0;
    \\            return t;
    \\        }
    \\        pub fn sel(c: T, a: T, b: T) T {
    \\            return if (c.v != 0.0) a else b;
    \\        }
    \\        pub const T = struct {
    \\            v: f64,
    \\            d: [N]f64 = @splat(0.0),
    \\            /// Null on a value no probe reached, which has no lanes to rotate.
    \\            w: ?*const Fw = null,
    \\            pub const F = Fw;
    \\            pub fn splat(c: f64) F {
    \\                return if (@typeInfo(F) == .vector) @splat(c) else c;
    \\            }
    \\            pub fn omega(a: T) F {
    \\                return if (a.w) |p| p.* else splat(0.0);
    \\            }
    \\            fn k(c: f64) Lanes {
    \\                return @splat(c);
    \\            }
    \\            fn lv(a: T) Lanes {
    \\                return a.d;
    \\            }
    \\            fn mk(v: f64, d: Lanes, a: T, b: T) T {
    \\                return .{ .v = v, .d = d, .w = a.w orelse b.w };
    \\            }
    \\            fn map(a: T, v: f64, c: f64) T {
    \\                return .{ .v = v, .d = lv(a) * k(c), .w = a.w };
    \\            }
    \\            fn at(a: T, o: usize) F {
    \\                if (@typeInfo(F) == .vector) return a.d[o..][0..W].*;
    \\                return a.d[o];
    \\            }
    \\            fn put(a: *T, o: usize, x: F) void {
    \\                if (@typeInfo(F) == .vector) a.d[o..][0..W].* = x else a.d[o] = x;
    \\            }
    \\            /// The complex partial by unknown `u`, real and imaginary part.
    \\            pub fn acRe(a: T, u: usize) F {
    \\                return a.at(n_u + u * W);
    \\            }
    \\            pub fn acIm(a: T, u: usize) F {
    \\                return a.at(n_u * (1 + W) + u * W);
    \\            }
    \\            /// An operator output `y` whose small-signal response is `h`: the
    \\            /// input's direct and complex blocks, summed, times `h`.
    \\            pub fn acMul(a: T, y: f64, h: std.math.Complex(F)) T {
    \\                var o: T = .{ .v = y, .w = a.w };
    \\                for (0..n_u) |u| {
    \\                    const re = splat(a.d[u]) + a.acRe(u);
    \\                    const im = a.acIm(u);
    \\                    o.put(n_u + u * W, h.re * re - h.im * im);
    \\                    o.put(n_u * (1 + W) + u * W, h.re * im + h.im * re);
    \\                }
    \\                return o;
    \\            }
    \\            pub fn to(a: T, comptime _: u64) T {
    \\                return a;
    \\            }
    \\            pub fn val(a: T) f64 {
    \\                return a.v;
    \\            }
    \\            pub fn ddxAt(a: T, comptime u: usize) f64 {
    \\                return a.d[u];
    \\            }
    \\            pub fn add(a: T, b: T) T {
    \\                return mk(a.v + b.v, lv(a) + lv(b), a, b);
    \\            }
    \\            pub fn sub(a: T, b: T) T {
    \\                return mk(a.v - b.v, lv(a) - lv(b), a, b);
    \\            }
    \\            pub fn mul(a: T, b: T) T {
    \\                return mk(a.v * b.v, @mulAdd(Lanes, lv(b), k(a.v), lv(a) * k(b.v)), a, b);
    \\            }
    \\            pub fn div(a: T, b: T) T {
    \\                const qt = a.v / b.v;
    \\                return mk(qt, @mulAdd(Lanes, lv(b), k(-qt), lv(a)) * k(1.0 / b.v), a, b);
    \\            }
    \\            pub fn neg(a: T) T {
    \\                return .{ .v = -a.v, .d = -lv(a), .w = a.w };
    \\            }
    \\            pub fn scale(a: T, c: f64) T {
    \\                return map(a, a.v * c, c);
    \\            }
    \\            pub fn addC(a: T, c: f64) T {
    \\                return .{ .v = a.v + c, .d = a.d, .w = a.w };
    \\            }
    \\            pub fn exp(a: T) T {
    \\                const e = contract.gm.exp(a.v);
    \\                return map(a, e, e);
    \\            }
    \\            pub fn log(a: T) T {
    \\                return map(a, contract.gm.log(a.v), 1.0 / a.v);
    \\            }
    \\            pub fn expm1(a: T) T {
    \\                return map(a, contract.gm.expm1(a.v), contract.gm.exp(a.v));
    \\            }
    \\            pub fn log1p(a: T) T {
    \\                return map(a, std.math.log1p(a.v), 1.0 / (1.0 + a.v));
    \\            }
    \\            pub fn sqrt(a: T) T {
    \\                const s = @sqrt(a.v);
    \\                return map(a, s, if (s > 0.0) 0.5 / s else 0.0);
    \\            }
    \\            pub fn sin(a: T) T {
    \\                return map(a, contract.gm.sin(a.v), contract.gm.cos(a.v));
    \\            }
    \\            pub fn cos(a: T) T {
    \\                return map(a, contract.gm.cos(a.v), -contract.gm.sin(a.v));
    \\            }
    \\            pub fn tanh(a: T) T {
    \\                const th = contract.gm.tanh(a.v);
    \\                return map(a, th, 1.0 - th * th);
    \\            }
    \\            pub fn sinh(a: T) T {
    \\                return map(a, contract.gm.sinh(a.v), contract.gm.cosh(a.v));
    \\            }
    \\            pub fn cosh(a: T) T {
    \\                return map(a, contract.gm.cosh(a.v), contract.gm.sinh(a.v));
    \\            }
    \\            pub fn atan(a: T) T {
    \\                return map(a, contract.gm.atan(a.v), 1.0 / (1.0 + a.v * a.v));
    \\            }
    \\            pub fn pow(a: T, c: f64) T {
    \\                const p = contract.gm.pow(a.v, c);
    \\                const s = if (a.v != 0.0) c * p / a.v else c * contract.gm.pow(a.v, c - 1.0);
    \\                return map(a, p, if (std.math.isFinite(s)) s else 0.0);
    \\            }
    \\            pub fn lt(a: T, b: T) T {
    \\                return con(@floatFromInt(@intFromBool(a.v < b.v)));
    \\            }
    \\            pub fn le(a: T, b: T) T {
    \\                return con(@floatFromInt(@intFromBool(a.v <= b.v)));
    \\            }
    \\            pub fn eq(a: T, b: T) T {
    \\                return con(@floatFromInt(@intFromBool(a.v == b.v)));
    \\            }
    \\        };
    \\    };
    \\}
    \\
    \\
;

/// §3.2.2 memory-backed arrays (`Lowered.mem_arrays`): one storage per array,
/// indexed at run time. Only devices with one carry these.
pub const arr_txt =
    \\// ---- §3.2.2 memory-backed arrays ----
    \\
    \\/// Element `i` of `a`, or `z` for an index outside it: §3.2.2 names no
    \\/// element there, and the read gives the element type's zero. The load is
    \\/// clamped into bounds and the pick is a select, so it never branches.
    \\fn zArrLd(comptime T: type, a: []const T, i: i64, z: T) T {
    \\    const k: u64 = @bitCast(i);
    \\    const v = a[@intCast(@min(k, a.len - 1))];
    \\    return if (k < a.len) v else z;
    \\}
    \\
    \\/// Store `v` at `i`; an index outside the array writes nothing.
    \\fn zArrSt(comptime T: type, a: []T, i: i64, v: T) void {
    \\    const k: u64 = @bitCast(i);
    \\    if (k < a.len) a[@intCast(k)] = v;
    \\}
    \\
    \\/// Store `v` at `i` in an in-place held array and widen `d`, the index
    \\/// range written since the last `stateCtl` (`zArrSync`).
    \\fn zArrStD(comptime T: type, a: []T, d: *[2]i64, i: i64, v: T) void {
    \\    const k: u64 = @bitCast(i);
    \\    if (k < a.len) {
    \\        a[@intCast(k)] = v;
    \\        d.* = .{ @min(d[0], i), @max(d[1], i) };
    \\    }
    \\}
    \\
    \\/// §5.10 `stateCtl` for an in-place held array: copy the elements written
    \\/// since the last commit or revert (`d`, inclusive; empty when d[0] >
    \\/// d[1]) from `src` to `dst`; then the two agree everywhere and `d` is
    \\/// empty. A step appending one sample to a 2048-deep history copies one.
    \\fn zArrSync(comptime T: type, dst: anytype, src: anytype, d: *[2]i64) void {
    \\    if (d[0] <= d[1]) {
    \\        const lo: usize = @intCast(d[0]);
    \\        const hi: usize = @intCast(d[1] + 1);
    \\        @memcpy(@as([]T, dst[lo..hi]), @as([]const T, src[lo..hi]));
    \\    }
    \\    d.* = .{ std.math.maxInt(i64), -1 };
    \\}
    \\
    \\/// §5.10 the storage a held array's store writes: `a`, holding what `p`
    \\/// read until now — the `Instance` field, copied in by the first store.
    \\fn zArrW(comptime T: type, comptime n: usize, a: *[n]T, p: **const [n]T) *[n]T {
    \\    if (p.* != a) {
    \\        a.* = p.*.*;
    \\        p.* = a;
    \\    }
    \\    return a;
    \\}
    \\
    \\/// Every element of `a` set to `v`, the per-evaluation §3.2 start. Past a
    \\/// few stores LLVM lowers `@memset` to a `memset` call, and Zig 0.16's
    \\/// compiler_rt `memset` stores ONE BYTE per iteration (a 1.5 KB
    \\/// derivative stack took ~800 cycles). Read through a volatile, `v` is
    \\/// no constant LLVM can turn back into a memset, so the loop below stays
    \\/// explicit 4-lane stores (a plain `f64`/`i64` array) or one element per
    \\/// store. The stored bits are `v`'s either way.
    \\fn zFill(comptime T: type, comptime n: usize, a: *[n]T, v: T) void {
    \\    if (@sizeOf([n]T) <= 128) return @memset(a, v);
    \\    var o = v;
    \\    const z = @as(*volatile T, &o).*;
    \\    if (T == f64 or T == i64) {
    \\        const k = n / 4;
    \\        const vs: *align(@alignOf(T)) [k]@Vector(4, T) = @ptrCast(a);
    \\        for (vs) |*e| e.* = @splat(z);
    \\        for (a[k * 4 ..]) |*e| e.* = z;
    \\    } else for (a) |*e| {
    \\        e.* = z;
    \\    }
    \\}
    \\
    \\/// The values of an `S` array: what a held array's `f64` `Instance`
    \\/// field keeps.
    \\fn zArrVal(comptime S: type, comptime n: usize, a: *const [n]S) [n]f64 {
    \\    var o: [n]f64 = undefined;
    \\    for (&o, a) |*d, s| d.* = s.val();
    \\    return o;
    \\}
    \\
    \\
;

/// The §4.5.7 `absdelay` history ring and its linear interpolation
/// (`zAbsdelay`, `zHistAt`). Emitted only when `usesOp(.absdelay)`.
pub const hist_txt =
    \\/// §4.5.7 the delayed value, as the residual sees it: Output(t) = Input(t − td).
    \\///
    \\/// Two edges are decided HERE rather than by the ring scan below:
    \\///
    \\///  · dt ≤ 0 is a static analysis — "In DC and operating point analyses,
    \\///    absdelay() returns the value of its input" — so `vin` passes through,
    \\///    derivative and all, exactly like `zTransition`'s DC branch.
    \\///  · a td SHORTER than the step the host just took queries past the newest
    \\///    accepted sample. The only data covering (ts[newest], now] is the
    \\///    CURRENT in-flight value, so the answer interpolates between the newest
    \\///    sample and `vin` — the same linear reading `zHistAt` applies inside
    \\///    the history. That keeps the output continuous in t and carries the
    \\///    f·∂vin derivative the td → 0 (identity) limit requires. The scan used
    \\///    to fall through to the newest sample here, which silently stretched
    \\///    every delay shorter than a step to the step itself. (Clamping was the
    \\///    other candidate; it answers a PAST query with a value from the wrong
    \\///    time and keeps the Jacobian blind to an input the output already
    \\///    partially tracks, so interpolation is the sound choice.)
    \\///
    \\/// Inside the history the delayed value has no dependence on the current
    \\/// unknowns, so it is injected as a constant (derivative 0) — the correct
    \\/// companion model for a pure transport delay. The f ≤ 1 clamp covers a
    \\/// runtime-negative td, which lowering rejects where it can fold.
    \\fn zAbsdelay(comptime S: type, vin: S, ts: []const f64, vs: []const f64, head: u64, now: f64, dt: f64, td: f64) S {
    \\    if (dt <= 0.0) return vin;
    \\    // §4.5.15 "no state history prior to time t == 0": nothing has been
    \\    // accepted yet, so the input IS the output. The ring used to be SEEDED
    \\    // full on the first push, which made this unreachable; `head` is a
    \\    // count now, so the empty ring has to answer for itself.
    \\    if (head == 0) return vin;
    \\    const t = now - td;
    \\    const newest: usize = @intCast((head + ts.len - 1) % ts.len);
    \\    if (t > ts[newest]) {
    \\        const span = now - ts[newest];
    \\        if (span <= 0.0) return vin;
    \\        const f = @min((t - ts[newest]) / span, 1.0);
    \\        return vin.scale(f).addC(vs[newest] * (1.0 - f));
    \\    }
    \\    return S.con(zHistAt(ts, vs, head, t));
    \\}
    \\/// §4.5.7 absdelay history: a fixed ring of (t, v) samples, linearly
    \\/// interpolated. `head` is the TOTAL number of accepted samples pushed, not
    \\/// a wrapped index — the ring slot is `head % n`. That one extra fact is
    \\/// what separates the two queries that used to answer the same way: a
    \\/// query before recorded history began, which §4.5.15 settles ("all analog
    \\/// operators are considered to have no state history prior to time t == 0")
    \\/// and `Output(t) = Input(max(t − td, 0))` answers with Input(0); and a
    \\/// query the ring has FORGOTTEN, which the clause settles not at all.
    \\fn zHistAt(ts: []const f64, vs: []const f64, head: u64, t: f64) f64 {
    \\    const n = ts.len;
    \\    const wrapped = head > n;
    \\    const oldest: usize = if (wrapped) @intCast(head % n) else 0;
    \\    // O(1) for a query at or before the oldest sample — the scan would walk
    \\    // all n entries to reach the same answer.
    \\    if (t <= ts[oldest]) {
    \\        // Before the first sample the operator HAS no history, and Input(0)
    \\        // is the value the formula's max(t − td, 0) floor asks for.
    \\        if (!wrapped) return vs[oldest];
    \\        // Older than the whole ring. There is no honest answer here: the
    \\        // clause bounds no lookback, so shortening the delay to whatever the
    \\        // ring still holds is not an implementation-defined limit, it is a
    \\        // different transport delay reported as this one. E1012 ends the
    \\        // run instead.
    \\        std.debug.print("error[E1012]: absdelay needs a sample older than its " ++
    \\            "{d}-sample history holds; see `vera --explain E1012`\n", .{n});
    \\        std.process.exit(1);
    \\    }
    \\    // Binary search in age order (c = 0 is the oldest live sample): `lo`
    \\    // ends at the newest sample at or before t, so the bracket is the
    \\    // NEWEST interval holding t, the one a scan from the newest end finds
    \\    // first. O(log n): a 5 ns line at 1 ps looks 5000 samples back.
    \\    // `zAbsdelay` covers t > newest, so t ≤ ts[newest] here.
    \\    const count: usize = @intCast(@min(head, n));
    \\    if (count < 2) return vs[oldest]; // only a NaN t gets here
    \\    var lo: usize = 0;
    \\    var hi: usize = count;
    \\    while (hi - lo > 1) {
    \\        const mid = lo + (hi - lo) / 2;
    \\        if (ts[(oldest + mid) % n] <= t) lo = mid else hi = mid;
    \\    }
    \\    const c = @min(lo + 1, count - 1);
    \\    const older = (oldest + c - 1) % n;
    \\    const newer = (oldest + c) % n;
    \\    const span = ts[newer] - ts[older];
    \\    if (span <= 0.0) return vs[newer];
    \\    const f = (t - ts[older]) / span;
    \\    return vs[older] + (vs[newer] - vs[older]) * f;
    \\}
    \\fn zHistPush(ts: []f64, vs: []f64, head: *u64, t: f64, v: f64) void {
    \\    const at: usize = @intCast(head.* % ts.len);
    \\    ts[at] = t;
    \\    vs[at] = v;
    \\    // `head` is a COUNT, and zHistAt reads `head > n` as "the ring has
    \\    // overwritten its oldest sample"; a u64 of accepted steps never wraps.
    \\    head.* += 1;
    \\}
;

/// `zAbsdelay` and `zHistAt` under VerA's `(* vera_interp = 2 *)`: 3-point
/// Lagrange instead of §4.5.7's linear reading, as SPICE's lossless
/// transmission line does. Emitted after `hist_txt`, only for a device that
/// asks.
pub const hist_quad_txt =
    \\
    \\/// `zAbsdelay` read quadratically. Every edge `zAbsdelay` decides for itself
    \\/// — a static analysis, an empty ring, a query past `now` — is its answer
    \\/// here too, and so is a single accepted sample.
    \\///
    \\/// Past the newest sample the parabola runs through the last two samples
    \\/// and the in-flight (now, vin), so the output carries ∂/∂vin, the
    \\/// Lagrange weight of `now`.
    \\fn zAbsdelayQ(comptime S: type, vin: S, ts: []const f64, vs: []const f64, head: u64, now: f64, dt: f64, td: f64) S {
    \\    const t = now - td;
    \\    if (dt <= 0.0 or head < 2 or !(t < now)) return zAbsdelay(S, vin, ts, vs, head, now, dt, td);
    \\    const b: usize = @intCast((head + ts.len - 1) % ts.len);
    \\    const a: usize = @intCast((head + ts.len - 2) % ts.len);
    \\    if (t <= ts[b]) return S.con(zHistAtQ(ts, vs, head, t));
    \\    const dab = ts[b] - ts[a];
    \\    const dan = now - ts[a];
    \\    const dbn = now - ts[b];
    \\    if (!(dab > 0.0 and dbn > 0.0)) return zAbsdelay(S, vin, ts, vs, head, now, dt, td);
    \\    const wa = (t - ts[b]) * (t - now) / (dab * dan);
    \\    const wb = -(t - ts[a]) * (t - now) / (dab * dbn);
    \\    const wn = (t - ts[a]) * (t - ts[b]) / (dan * dbn);
    \\    return vin.scale(wn).addC(vs[a] * wa + vs[b] * wb);
    \\}
    \\/// `zHistAt` read quadratically: the parabola through the two samples
    \\/// bracketing `t` and the one before them (the first three, in the first
    \\/// interval). Fewer than three samples, a query at or before the oldest,
    \\/// or two samples at one time is `zHistAt`'s linear answer.
    \\fn zHistAtQ(ts: []const f64, vs: []const f64, head: u64, t: f64) f64 {
    \\    const n = ts.len;
    \\    const count: usize = @intCast(@min(head, n));
    \\    const oldest: usize = if (head > n) @intCast(head % n) else 0;
    \\    if (count < 3 or t <= ts[oldest]) return zHistAt(ts, vs, head, t);
    \\    // The ring is monotone in time, so the samples at or before `t` count
    \\    // out the older end of its interval; `zHistAt`'s binary search in age
    \\    // order finds that count in O(log n).
    \\    var lo: usize = 0;
    \\    var hi: usize = count;
    \\    while (hi - lo > 1) {
    \\        const mid = lo + (hi - lo) / 2;
    \\        if (ts[(oldest + mid) % n] <= t) lo = mid else hi = mid;
    \\    }
    \\    const m = lo + 1;
    \\    const w = oldest + @min(m - 1 -| 1, count - 3);
    \\    const i_0 = w % n;
    \\    const i_1 = (w + 1) % n;
    \\    const i_2 = (w + 2) % n;
    \\    const d01 = ts[i_1] - ts[i_0];
    \\    const d12 = ts[i_2] - ts[i_1];
    \\    if (!(d01 > 0.0 and d12 > 0.0)) return zHistAt(ts, vs, head, t);
    \\    const d02 = ts[i_2] - ts[i_0];
    \\    return vs[i_0] * (t - ts[i_1]) * (t - ts[i_2]) / (d01 * d02) -
    \\        vs[i_1] * (t - ts[i_0]) * (t - ts[i_2]) / (d01 * d12) +
    \\        vs[i_2] * (t - ts[i_0]) * (t - ts[i_1]) / (d02 * d12);
    \\}
;

// ---- the `u/<key>.zig` file-scope prologue (see `Output.prelude`) ----------
//
// A unit file is a separate Zig file with none of device.zig's helpers in
// scope, so these blocks alias them from `h.zig` (derived by `appendAliases`).
// `..` is the work_dir: `u/<key>.zig` sits one level under `device.zig`.

/// The `h.zig` header: banner and imports ahead of the public helper text.
pub const helpers_head_txt =
    \\// GENERATED BY VerA — DO NOT EDIT.
    \\// The §4.3/§4.5 kernels, public so `u/<key>.zig` can alias them. device.zig
    \\// carries the same text privately: it must stay a valid stand-alone device.
    \\const std = @import("std");
    \\const contract = @import("contract");
    \\
    \\
;

/// The unit-file prologue head: imports and aliases of the device's types.
/// The helper import is `zh`, not `h`: a unit body's hoist array is `var h`,
/// and Zig refuses a local that shadows a file-scope name.
pub const prelude_head_txt =
    \\// GENERATED BY VerA — DO NOT EDIT.
    \\const std = @import("std");
    \\const contract = @import("contract");
    \\const dev = @import("../device.zig");
    \\const zh = @import("../h.zig");
    \\const U = dev.U;
    \\const Model = dev.Model;
    \\const Instance = dev.Instance;
    \\const InstancePtr = contract.InstancePtr(dev);
    \\const n_u = contract.nU(dev);
    \\
;

/// Appends a `const zFoo = zh.zFoo;` alias for each top-level `z*` helper
/// `src` declares, so a helper that is emitted is aliased by construction. A
/// line is a declaration by `publish`'s predicate (`fn ` or `const `,
/// optionally `pub `), and the name must be `z` plus an uppercase letter: the
/// spelling of every helper an emitted body calls, which keeps a kernel's
/// internals (`zstd`, `zfIo`, `zf_max`, `ZScan`) out.
pub fn appendAliases(out: *std.ArrayList(u8), gpa: std.mem.Allocator, src: []const u8) std.mem.Allocator.Error!void {
    var it = std.mem.splitScalar(u8, src, '\n');
    while (it.next()) |line| {
        const decl = if (std.mem.startsWith(u8, line, "pub ")) line[4..] else line;
        const at: usize = if (std.mem.startsWith(u8, decl, "fn "))
            "fn ".len
        else if (std.mem.startsWith(u8, decl, "const "))
            "const ".len
        else
            continue;
        const rest = decl[at..];
        var n: usize = 0;
        while (n < rest.len and (std.ascii.isAlphanumeric(rest[n]) or rest[n] == '_')) n += 1;
        const name = rest[0..n];
        if (name.len < 2 or name[0] != 'z' or !std.ascii.isUpper(name[1])) continue;
        try out.print(gpa, "const {0s} = zh.{0s};\n", .{name});
    }
}

/// §9.4.3 integer padding, for a printing artifact or a device that formats
/// into a string. `std.fmt` writes `+42` for `{d:>5}`; §9.4.3 (like C's
/// `%5d`) writes ` 42`, so the rendered decimal is padded instead.
// ponytail: 24 bytes is i64's widest decimal (20 chars) plus slack, so the
// `catch unreachable` cannot fire. Zero-padding a negative number yields
// `00-42` where C yields `-0042`; fixing it means reimplementing the sign
// placement here.
pub const display_txt =
    \\fn zPadInt(buf: []u8, v: i64) []const u8 { // §9.4.3 %<width>d
    \\    return std.fmt.bufPrint(buf, "{d}", .{v}) catch unreachable;
    \\}
    \\
    \\/// §9.7 simulation control: the run ends here. Declared `f64` and not
    \\/// `noreturn` ON PURPOSE: statements after a §9.7.3 `$fatal` are legal
    \\/// dead code (exhaustive/011 writes `$finish; $stop;` after one), and a
    \\/// noreturn-typed call site would make Zig refuse the block for
    \\/// unreachable code. The value is never produced.
    \\fn zHalt(code: u8) f64 {
    \\    std.process.exit(code);
    \\}
    \\
;
