//! Fixed emitted text: the runtime kernels every device carries (§4.3 math, §4.5 operators, Clause 9).
//!
//! Zig source text, spliced verbatim into device.zig by `buildPrelude`. Nothing here runs in the
//! compiler; it runs inside the host's Newton loop.
//!
//! LRM clauses this file's code cites: §4.3, §4.3.1, §4.3.2, §4.5, §4.5.4, §4.5.5, §4.5.8, §4.5.15, §5.10.3.1, §9.4.3, §9.5.3, §9.21.
//!
//! Cut verbatim from `codegen.zig`.

const std = @import("std");
const codegen = @import("../codegen.zig");
const naming = @import("../naming.zig");
const assert = codegen.assert;
const Output = codegen.Output;
const Gen = codegen.Gen;
const devSafe = codegen.devSafe;

// ===========================================================================
// Fixed emitted text
// ===========================================================================

pub const header_txt =
    \\// GENERATED BY VerA — DO NOT EDIT.
    \\// The model is ONE declaration; its name is the structural key from
    \\// naming.zig, so an unchanged model is byte-identical across rebuilds and
    \\// `zig -fincremental` skips it.
    \\
    \\const std = @import("std");
    \\const contract = @import("contract");
    \\const Self = @This();
    \\
    \\
;

/// LRM Tables 4-14 / 4-15 in VALUE FORM: every function the scalar interface S
/// does not provide natively is composed out of the ones it does, so forward-mode
/// autodiff propagates the ANALYTIC derivative instead of a finite difference.
/// S provides: con addC scale add sub neg mul div exp log sqrt pow(a,f64)
/// sin cos tanh sinh cosh atan abs minC maxC min max val.
///
/// These are FILE-scope helpers, so they run in the default (strict) float
/// mode; `@setFloatMode` is per-unit and does not cross a call. That is the
/// conservative direction — a `.optimized` unit loses fast-math inside a helper,
/// it never gains unsound fast-math.
pub const math_txt =
    \\// ---- §4.3 math, value form (derivative propagates by composition) ----
    \\
    \\// §4.3.1 defines the derivative at equality using strict comparisons:
    \\// min(a,b) = (a < b) ? a : b; max(a,b) = (a > b) ? a : b.
    \\// Compose the contract's masks and winner-derivative selection rather
    \\// than inheriting a host min/max primitive's possibly different tie rule.
    \\fn zMin(comptime S: type, a: S, b: S) S { return a.lt(b).sel(a, b); }
    \\fn zMax(comptime S: type, a: S, b: S) S { return b.lt(a).sel(a, b); }
    \\
    \\/// Device-routed f64 transcendentals for the SCALAR paths (`R`, the
    \\/// §4.5.15 limiters, zLimexp's clamp constant). Generated devices also
    \\/// compile for NVPTX/AMDGCN (the engine's GPU eval and StateKernel), and
    \\/// those targets have no libm — `@exp`/`@log` on an f64 die at PTX
    \\/// assembly with "no libcall available for fexp". `contract.gm`'s host
    \\/// branch IS the builtin, so host emission is numerically unchanged; its
    \\/// device branch is a self-contained soft port. sin/cos joined when the
    \\/// bjt reached tan through the StateKernel's scalar core (`fsin` cannot
    \\/// select on NVPTX); log1p stays on std.math (pure Zig).
    \\///
    \\/// expm1 and atan are routed too, and NOT for a missing libcall -- NVPTX
    \\/// takes both. Both raise the subnormal underflow flag through
    \\/// `std.mem.doNotOptimizeAway`, which for a float is
    \\/// `asm volatile ("" :: "rm" (v))`, and AMDGPU cannot match the `m`
    \\/// alternative: "Could not match memory address. Inline asm failure!".
    \\/// AMD-only, so a CUDA-only check never sees it.
    \\inline fn zDevExp(x: f64) f64 {
    \\    return contract.gm.exp(x);
    \\}
    \\inline fn zDevExpm1(x: f64) f64 {
    \\    return contract.gm.expm1(x);
    \\}
    \\inline fn zDevAtan(x: f64) f64 {
    \\    return contract.gm.atan(x);
    \\}
    \\inline fn zDevLog(x: f64) f64 {
    \\    return contract.gm.log(x);
    \\}
    \\inline fn zDevPow(x: f64, y: f64) f64 {
    \\    return contract.gm.pow(x, y);
    \\}
    \\inline fn zDevSin(x: f64) f64 {
    \\    return contract.gm.sin(x);
    \\}
    \\inline fn zDevCos(x: f64) f64 {
    \\    return contract.gm.cos(x);
    \\}
    \\inline fn zDevTanh(x: f64) f64 {
    \\    return contract.gm.tanh(x);
    \\}
    \\inline fn zDevSinh(x: f64) f64 {
    \\    return contract.gm.sinh(x);
    \\}
    \\inline fn zDevCosh(x: f64) f64 {
    \\    return contract.gm.cosh(x);
    \\}
    \\
    \\fn zTan(comptime S: type, a: S) S { // §4.3.2 tan = sin/cos
    \\    return a.sin().div(a.cos());
    \\}
    \\fn zLog10(comptime S: type, a: S) S { // §4.3.1 log() is base 10
    \\    return a.log().scale(0.4342944819032518);
    \\}
    \\/// §4.3.1 Table 4-14 hypot names the C library function, which is
    \\/// overflow-free — a²+b² composed in S overflowed for legs ≳1e154. The
    \\/// value is the libm one; the derivative (a/h)·da + (b/h)·db is grafted on
    \\/// through zero-valued carriers, `a.addC(-av)` being an S whose VALUE is
    \\/// exactly 0 and whose derivative is da — the same idiom the §12.32 systf
    \\/// reassembly uses. Guarded: at h = 0 hypot has no derivative (a cone tip),
    \\/// and a non-finite h has no slope worth propagating.
    \\fn zHypot(comptime S: type, a: S, b: S) S {
    \\    const av = a.val();
    \\    const bv = b.val();
    \\    const h = std.math.hypot(av, bv);
    \\    var r = S.con(h);
    \\    if (h != 0.0 and std.math.isFinite(h))
    \\        r = r.add(a.addC(-av).scale(av / h)).add(b.addC(-bv).scale(bv / h));
    \\    return r;
    \\}
    \\fn zAsin(comptime S: type, a: S) S { // §4.3.2 asin = atan(x/sqrt(1-x^2))
    \\    const v = a.val();
    \\    zDomain("asin", "-1 <= x <= 1", v, v >= -1.0 and v <= 1.0);
    \\    return a.div(a.mul(a).neg().addC(1.0).sqrt()).atan();
    \\}
    \\fn zAcos(comptime S: type, a: S) S { // §4.3.2
    \\    const v = a.val();
    \\    zDomain("acos", "-1 <= x <= 1", v, v >= -1.0 and v <= 1.0);
    \\    return S.con(1.5707963267948966).sub(zAsin(S, a));
    \\}
    \\fn zAsinh(comptime S: type, a: S) S { // §4.3.2 ln(x + sqrt(x^2+1))
    \\    return a.add(a.mul(a).addC(1.0).sqrt()).log();
    \\}
    \\fn zAcosh(comptime S: type, a: S) S { // §4.3.2 ln(x + sqrt(x^2-1))
    \\    const v = a.val();
    \\    zDomain("acosh", "x >= 1", v, v >= 1.0);
    \\    return a.add(a.mul(a).addC(-1.0).sqrt()).log();
    \\}
    \\fn zAtanh(comptime S: type, a: S) S { // §4.3.2 0.5*ln((1+x)/(1-x))
    \\    const v = a.val();
    \\    zDomain("atanh", "-1 < x < 1", v, v > -1.0 and v < 1.0);
    \\    return a.addC(1.0).div(a.neg().addC(1.0)).log().scale(0.5);
    \\}
    \\fn zAtan2(comptime S: type, y: S, x: S) S { // §4.3.2
    \\    // Value-level branch only: every arm is atan(y/x) plus a CONSTANT, so
    \\    // each arm carries the exact derivative of atan2 on its quadrant.
    \\    const xv = x.val();
    \\    if (xv > 0.0) return y.div(x).atan();
    \\    if (xv < 0.0) {
    \\        const c: f64 = if (y.val() >= 0.0) 3.141592653589793 else -3.141592653589793;
    \\        return y.div(x).atan().addC(c);
    \\    }
    \\    const yv = y.val();
    \\    return S.con(if (yv > 0.0) 1.5707963267948966 else if (yv < 0.0) -1.5707963267948966 else 0.0);
    \\}
    \\fn zFloor(comptime S: type, a: S) S { // §4.3.1 — derivative 0 a.e.
    \\    return S.con(@floor(a.val()));
    \\}
    \\fn zCeil(comptime S: type, a: S) S { // §4.3.1 — derivative 0 a.e.
    \\    return S.con(@ceil(a.val()));
    \\}
    \\/// §4.2.4 `%` keeps the sign of the first operand — C's fmod, which `@rem`
    \\/// on f64 is, EXACTLY. The composed `a − b·trunc(a/b)` this replaces lost
    \\/// the whole remainder to the subtraction's rounding once |a| ≳ 2^53·|b|.
    \\/// The derivative treatment is unchanged (k = trunc(a/b) is constant a.e.,
    \\/// so d = da − k·db), carried by zero-valued grafts so the exact value
    \\/// survives; a non-finite k (b = 0, or a/b overflowed) has no slope worth
    \\/// propagating and degrades to da alone.
    \\fn zFmod(comptime S: type, a: S, b: S) S {
    \\    const av = a.val();
    \\    const bv = b.val();
    \\    const k = @trunc(av / bv);
    \\    var r = S.con(@rem(av, bv)).add(a.addC(-av));
    \\    if (std.math.isFinite(k)) r = r.sub(b.addC(-bv).scale(k));
    \\    return r;
    \\}
    \\/// §4.3.1 pow with a non-constant exponent. The exp(y·ln x) composition
    \\/// this replaces was NaN on the clause's own legal domain "if x < 0, all
    \\/// integer y". The value is S's own pow, which handles the negative-base
    \\/// integral-y sign itself; the derivatives are grafted on zero-valued
    \\/// carriers:
    \\///   ∂/∂x = y·x^(y−1)  — valid for x > 0 and for integral y of either sign;
    \\///   ∂/∂y = x^y·ln(x)  — only for x > 0. For x ≤ 0 the legal y move in
    \\///   integer steps, so no continuous ∂/∂y exists and 0 is the honest slope.
    \\/// Non-finite slopes (x = 0 with y < 1, domain-error NaNs) are dropped the
    \\/// same way zHypot drops its cone tip.
    \\/// Both transcendentals go through `S.con(x)`, not `std.math.pow` and
    \\/// `@log`, for the reason `devSafe` exists: a unit body also compiles
    \\/// for nvptx, which has no libm, and a raw one is "no libcall available
    \\/// for flog/fexp" at PTX assembly. On a host S it is the same libm call,
    \\/// bit for bit, and the zero-derivative carriers fold away.
    \\fn zPow(comptime S: type, a: S, b: S, comptime varying_exponent: bool) S {
    \\    const x = a.val();
    \\    const y = b.val();
    \\    const v = S.con(x).pow(y).val();
    \\    // y·x^(y−1) = y·v/x — algebraically exact for x != 0, the negative-base
    \\    // integral-y clause included, and ONE pow instead of two. A second
    \\    // `S.con(x).pow(y - 1.0)` was half of the 828k pow calls on
    \\    // tran/fourbitadder and half of the 51% of instructions mos6_inverter
    \\    // spent under pow (callgrind, 2026-09-07): every junction exponent in
    \\    // every SPICE model is a model PARAMETER, so codegen's `.pow` arm sends
    \\    // all of them here rather than down `Dual.pow`'s own c·p/x.
    \\    //
    \\    // x == 0 keeps the second pow, and is NOT a rounding concern: at y == 1
    \\    // the true slope is 1, but v/x is 0/0 = NaN and the gate below would
    \\    // drop the term and flatten the Jacobian row. `mjs` defaults to 0 in
    \\    // bjt.va, so `1 - mjs` is exactly that exponent and the substrate base
    \\    // `1 - v/ps` reaches exactly 0 at v == ps. The branch is never taken on
    \\    // a normal bias point, so the hot path is still one pow, and where it
    \\    // IS taken the expression is the old one character for character.
    \\    // Elsewhere the two forms sit within 6 ulp of a 60-digit reference and
    \\    // neither is uniformly closer; the result is a Jacobian entry, and
    \\    // Newton converges to the accuracy of the RESIDUAL.
    \\    const gx = if (x != 0.0) y * v / x else y * S.con(x).pow(y - 1.0).val();
    \\    const gy: f64 = if (varying_exponent and x > 0.0) v * S.con(x).log().val() else 0.0;
    \\    var r = S.con(v);
    \\    if (std.math.isFinite(gx) and gx != 0.0) r = r.add(a.addC(-x).scale(gx));
    \\    if (std.math.isFinite(gy) and gy != 0.0) r = r.add(b.addC(-y).scale(gy));
    \\    return r;
    \\}
    \\/// §9.17.3 `$limit(access, user_function, args…)`: the value is what the
    \\/// user limiter returned, the DERIVATIVE is the access function's.
    \\///
    \\/// SPICE evaluates the device at the limited bias and stamps
    \\/// `I(vlim) + g(vlim)·(v − vlim)`, so the residual stays linear in the
    \\/// true unknown past the clamp point and the Jacobian entry never
    \\/// vanishes. Differentiating the limiter instead gives dv_lim/dv = 0
    \\/// inside the clamped region — a device contributing no conductance,
    \\/// which is a singular row for a floating internal node. So: shift the
    \\/// probe by the constant the clamp moved it, rather than replace it.
    \\fn zLimitUf(comptime S: type, vnew: S, vlim: S) S {
    \\    return vnew.addC(vlim.val() - vnew.val());
    \\}
    \\fn zIabs(a: i64) i64 { // §4.3.1 integer abs, §3.2's 32-bit result
    \\    return @as(i32, @truncate(if (a < 0) -%a else a));
    \\}
    \\/// §4.2.11 the shift COUNT reads as unsigned: a negative i64 count is a
    \\/// reinterpreted value ≥ 2^63, which vacates every one of §3.2.1's 32 bits
    \\/// — so the answer is 0, exactly like any other over-wide count. Without
    \\/// the guard `std.math.shl`/`shr` take a negative count as "shift the
    \\/// OTHER way" (8 << -1 came out 4, 8 >> -1 came out 16). Positive counts
    \\/// keep the std functions' verified over-wide-is-0 semantics untouched.
    \\fn zShl(a: i64, n: i64) i64 {
    \\    return if (n < 0) 0 else std.math.shl(i64, a, n);
    \\}
    \\fn zShr(a: i64, n: i64) i64 {
    \\    if (n == 0) return a; // preserve signed/unsigned operand identity
    \\    const bits: u32 = @bitCast(@as(i32, @truncate(a)));
    \\    return if (n < 0) 0 else std.math.shr(u32, bits, n);
    \\}
    \\fn zClog2(a: i64) i64 { // §9.11 $clog2
    \\    if (a <= 1) return 0;
    \\    const m: u64 = @intCast(a - 1);
    \\    return 64 - @as(i64, @clz(m));
    \\}
    \\fn zStrCmp(a: []const u8, b: []const u8) i64 { // §3.3.1 string relations
    \\    return switch (std.mem.order(u8, a, b)) { .lt => -1, .eq => 0, .gt => 1 };
    \\}
    \\fn zLimexp(comptime S: type, a: S) S { // §4.5.13 — user-invoked ONLY
    \\    const lim = 80.0;
    \\    if (a.val() > lim) return a.addC(1.0 - lim).scale(zDevExp(lim));
    \\    return a.exp();
    \\}
    \\
    \\
;

/// §4.3.2's last sentence of prose: "Input values outside of the valid range
/// for the operator shall report an error." `proof.checkDomain` answers only
/// the half it can PROVE from the source (E0605/E0606/E0607) and deliberately
/// accepts an undecidable range; `math_txt`'s four restricted-domain functions
/// call `zDomain` for the rest.
///
/// TWO VARIANTS, for the reason §9.4's display family has two: a DEVICE has no
/// transcript and may not contain one — `zDev*` exists because a device also
/// compiles for NVPTX, and a print is what a `$fatal` is already dropped for.
/// So the report is the EXECUTABLE's, and the device keeps the empty guard: it
/// costs nothing, and having the call site in one place means the two artifacts
/// cannot disagree about WHICH values are out of range.
pub const domain_quiet_txt =
    \\fn zDomain(comptime _: []const u8, comptime _: []const u8, _: f64, _: bool) void {}
    \\
    \\
;

/// The reporting half. Fatal, on the §9.21.2 `E` precedent: the clause names no
/// in-range value to return, and libm's quiet NaN reaches the residual as a
/// converged-looking wrong answer. A NaN argument reports too — it is inside no
/// range of Table 4-15. `tan` is unguarded: its poles are irrational, so no f64
/// is ever at one, which is why E0608 was retired.
pub const domain_report_txt =
    \\fn zDomain(comptime name: []const u8, comptime rule: []const u8, x: f64, in_range: bool) void {
    \\    if (in_range) return;
    \\    std.debug.print(
    \\        "error: LRM 4.3.2: " ++ name ++ "() input value is outside the valid range " ++ rule ++ ": {d}\n",
    \\        .{x},
    \\    );
    \\    std.process.exit(1);
    \\}
    \\
    \\
;

/// §4.5.2 the operator kernels. All take the CURRENT (S-valued) operator input
/// plus the accepted state, so the Jacobian of the companion model is analytic.
pub const ops_txt =
    \\// ---- §4.5 analog operator kernels ----
    \\
    \\fn zDdt(comptime S: type, v: S, prev: f64, dt: f64) S { // §4.5.3
    \\    if (dt <= 0.0) return S.con(0.0); // no time derivative in a static analysis
    \\    return v.addC(-prev).scale(1.0 / dt);
    \\}
    \\fn zIdt(comptime S: type, v: S, acc: f64, dt: f64, ic: f64) S { // §4.5.4
    \\    if (dt <= 0.0) return S.con(ic); // §4.5.4 DC value is the initial condition
    \\    return v.scale(dt).addC(acc);
    \\}
    \\fn zIdtReset(comptime S: type, v: S, acc: f64, dt: f64, ic: f64, assert_: f64) S { // §4.5.4
    \\    // "idt() returns the initial conditions during DC and IC analyses,
    \\    // and whenever assert is nonzero."
    \\    if (assert_ != 0.0) return S.con(ic);
    \\    return zIdt(S, v, acc, dt, ic);
    \\}
    \\fn zIdtAcc(v: f64, acc: f64, dt: f64, ic: f64) f64 {
    \\    if (dt <= 0.0) return ic;
    \\    return acc + v * dt;
    \\}
    \\fn zIdtmod(comptime S: type, v: S, acc: f64, dt: f64, ic: f64, m: f64, o: f64) S { // §4.5.5
    \\    const raw = zIdt(S, v, acc, dt, ic);
    \\    if (!(m > 0.0)) return raw;
    \\    // The wrap subtracts a piecewise-CONSTANT multiple of the modulus, so
    \\    // the derivative of the wrapped integral is the derivative of the raw one.
    \\    return raw.addC(-m * @floor((raw.val() - o) / m));
    \\}
    \\fn zWrap(x: f64, modulus: f64, offset: f64) f64 { // §4.5.5 idtmod
    \\    if (!(modulus > 0.0)) return x;
    \\    return x - modulus * @floor((x - offset) / modulus);
    \\}
    \\fn zSlew(comptime S: type, v: S, prev: f64, dt: f64, rise: f64, fall: f64) S { // §4.5.9
    \\    if (dt <= 0.0) return v;
    \\    return v.minC(prev + rise * dt).maxC(prev - fall * dt);
    \\}
    \\/// §5.10.3.1/§4.5.10 the crossing test for a direction that is a PARAMETER
    \\/// (a constant_expression the model card owns, so codegen cannot pick the
    \\/// comparison at emit time): +1 rising only, -1 falling only, anything
    \\/// else either — the EXACT decode `Gen.crossTest` applies to a folded one,
    \\/// so overriding the parameter to the value the default had changes nothing.
    \\fn zCrossDir(dir: f64, prev: f64, in: f64) bool {
    \\    if (dir == 1.0) return prev <= 0.0 and in > 0.0;
    \\    if (dir == -1.0) return prev >= 0.0 and in < 0.0;
    \\    if (dir != 0.0) return false; // §5.10.3.1 any other dir disables cross()
    \\    return (prev <= 0.0 and in > 0.0) or (prev >= 0.0 and in < 0.0);
    \\}
    \\/// §4.5.8 the fraction of the current excursion the ramp has traversed.
    \\/// "transition() forces all positive transitions of expr to occur over
    \\/// rise_time and all negative transitions to occur in fall_time", and the
    \\/// result "describes a piecewise linear function over time" — so the shape
    \\/// is (t - t0)/tt clamped into [0, 1], with tt picked by the DIRECTION of
    \\/// the excursion and t0 the time the excursion began.
    \\///
    \\/// A zero transition time is §4.5.8's own degenerate case ("If neither
    \\/// rise_time nor fall_time are specified or are equal to zero (0.0) …"),
    \\/// left to `default_transition and, with no directive, to the simulator:
    \\/// here that is an instantaneous edge, fraction 1.
    \\fn zTransFrac(target: f64, from: f64, t0: f64, t: f64, rise: f64, fall: f64) f64 {
    \\    const tt = if (target >= from) rise else fall;
    \\    if (!(tt > 0.0)) return 1.0;
    \\    return @min(@max((t - t0) / tt, 0.0), 1.0);
    \\}
    \\fn zTransition(comptime S: type, v: S, from: f64, to: f64, t0: f64, t: f64, dt: f64, rise: f64, fall: f64) S { // §4.5.8
    \\    // "In DC analysis, transition() passes the value of the expr directly
    \\    // to its output." There is no elapsed time to ramp over.
    \\    if (dt <= 0.0) return v;
    \\    // In a transient the output is a function of the input's PAST alone:
    \\    // the excursion in flight was armed by the accepted step that SAW the
    \\    // input change, "after an initial delay of td". Taking the CURRENT
    \\    // input as the ramp's target — which this did — armed every ramp at the
    \\    // previous accepted timepoint, so the output was already part-way up it
    \\    // at the corner itself and no td could have shifted that.
    \\    return S.con(from + (to - from) * zTransFrac(to, from, t0, t, rise, fall));
    \\}
    \\/// §4.5.8 accepted-step bookkeeping. "A transition is created when the
    \\/// input expression changes, and at this point it uses the value of td,
    \\/// rise_time, fall_time and time_tol to determine the new pending
    \\/// transition operator." `to` is the armed destination and so also the last
    \\/// ACCEPTED input, which makes `in != to` that sentence's test.
    \\///
    \\/// LEAVING THE EXCURSION ALONE is the important half: while the input has
    \\/// not changed the excursion is the one that started at `from`, and
    \\/// re-arming the origin every step would shrink the remaining distance by
    \\/// the same factor each time — an exponential decay wearing a ramp's
    \\/// coefficients, which is the bug this operator used to have.
    \\fn zTransStep(in: f64, from: *f64, to: *f64, t0: *f64, t: f64, dt: f64, td: f64, rise: f64, fall: f64) void {
    \\    if (dt <= 0.0) { // the DC point: the output IS the input, so sit on it
    \\        from.* = in;
    \\        to.* = in;
    \\        t0.* = t;
    \\        return;
    \\    }
    \\    if (in == to.*) return;
    \\    // "td models transport delay": the ramp begins td after the change and
    \\    // the output stays on its old trajectory until then, so it leaves from
    \\    // where that trajectory will be at t + td, not from where it is now.
    \\    const te = t + td;
    \\    const f = zTransFrac(to.*, from.*, t0.*, te, rise, fall);
    \\    const vi = from.* + (to.* - from.*) * f;
    \\    // §4.5.8's four interruption paragraphs (Figures 4-7 … 4-12): an input
    \\    // that changes inside the active region is "not ... a new transition,
    \\    // but rather a readjustment", whose slope uses "either the original
    \\    // transition's origin or destination as the new origin". One rule, four
    \\    // figures — the reference is the DESTINATION when the new direction
    \\    // opposes the original and the ORIGIN when it agrees:
    \\    //   rising,  v3 < vi -> opposes -> (v3-v2)/tf3    rising,  v3 > vi -> (v3-v1)/tr3
    \\    //   falling, v3 > vi -> opposes -> (v3-v2)/tr3    falling, v3 < vi -> (v3-v1)/tf3
    \\    // "applied from the point of interruption (ti,vi)", spelled here as the
    \\    // shifted origin (t4,v4) those paragraphs also name: v4 is the reference
    \\    // level, t4 where the slope line through (te,vi) reaches it. The arrival
    \\    // t3 = ti + (v3-vi)/slope then falls out of zTransFrac.
    \\    //
    \\    // NOT active is a new transition from where the output is — the branch
    \\    // this took unconditionally, which is the reading the four paragraphs
    \\    // exist to rule out.
    \\    if (f < 1.0 and in != vi) {
    \\        const tt3 = if (in > vi) rise else fall;
    \\        const vref = if ((in > vi) != (to.* > from.*)) to.* else from.*;
    \\        const slope = if (tt3 > 0.0) (in - vref) / tt3 else 0.0;
    \\        if (slope != 0.0) {
    \\            from.* = vref;
    \\            to.* = in;
    \\            t0.* = te + (vref - vi) / slope;
    \\            return;
    \\        }
    \\    }
    \\    from.* = vi;
    \\    to.* = in;
    \\    t0.* = te;
    \\}
    \\
;

/// §5.10.5 the `nextBreakpoint` kernel. Its own block, gated on `usesOp(.timer)`
/// like the history and filter kernels, so the 36 foundry models — none of which
/// uses `timer` — keep a byte-identical device.zig.
pub const timer_txt =
    \\// ---- §5.10.5 timer breakpoints ----
    \\
    \\/// The next time a `timer(start, period)` fires, STRICTLY after `t`.
    \\/// The only source in Verilog-A that means "put a timepoint here" — see
    \\/// `emitNextBreakpoint`. Must agree exactly with the `.timer` arm of
    \\/// `updateState`, which is the code that actually raises `__hit`.
    \\fn zNextTimer(start: f64, period: f64, t: f64) ?f64 {
    \\    // `updateState` clamps `__next` UP from its 0.0 initialiser, so a start
    \\    // before the origin fires at the origin — already a timepoint.
    \\    const s = @max(start, 0.0);
    \\    if (s > t) return s;
    \\    if (!(period > 0.0)) return null; // one-shot, and its single fire is behind us
    \\    // Fire k is s + k*period. Take the first k past `t`, then repair the
    \\    // two one-ulp outcomes of the division: landing high SKIPS a fire,
    \\    // landing low returns `t` itself and the transient walk stops advancing.
    \\    var n = @floor((t - s) / period) + 1.0;
    \\    if (n > 1.0 and s + (n - 1.0) * period > t) n -= 1.0;
    \\    if (s + n * period <= t) n += 1.0;
    \\    const next = s + n * period;
    \\    // Strictly `> t`, never `>=`: a host that re-asks from the breakpoint it
    \\    // was just handed (analysis/src/tran/matex.zig walks exactly that way)
    \\    // spins forever on an equal answer. When `period` is so small beside `t`
    \\    // that no later time is representable, "no breakpoint" is the honest —
    \\    // and terminating — answer.
    \\    return if (next > t and std.math.isFinite(next)) next else null;
    \\}
    \\
;

/// §9.5.3/§9.5.4.2 the string formatter's scratch and the scanner, emitted
/// VERBATIM from `str_kernels.zig` for the same reason `filt_txt` is: the rows
/// codegen's tests scan are byte-for-byte the ones the device scans. Only
/// devices that actually call `$sformat`/`$swrite`/`$sscanf` carry them.
pub const str_txt = "// ---- §9.5.3/§9.5.4.2 string kernels (lib/backend/str_kernels.zig) ----\n\n" ++
    @embedFile("../str_kernels.zig");

/// §9.13 the probabilistic distribution kernels, emitted VERBATIM from
/// `rng_kernels.zig` on the same terms as `str_txt`: the stream codegen's tests
/// exercise is byte-for-byte the stream the device draws from. Only devices that
/// call one of Table 9-10's 17 names carry it.
pub const rng_txt = "// ---- §9.13 probabilistic distribution kernels (lib/backend/rng_kernels.zig) ----\n\n" ++
    @embedFile("../rng_kernels.zig");

/// §9.21 the table-model interpolator, emitted VERBATIM from
/// `table_kernels.zig` on the same terms. Only devices that call
/// `$table_model` carry it.
pub const table_txt = "// ---- §9.21 table model kernels (lib/backend/table_kernels.zig) ----\n\n" ++
    @embedFile("../table_kernels.zig");

/// §9.5 the file-descriptor table and its operations, emitted VERBATIM from
/// `file_kernels.zig` on the same terms. Carried ONLY by a device that both calls
/// the family and is built `display == .emit` — the artifact that has a host
/// willing to run side effects. A device compiled for a solver has no `display`
/// decl to sequence them in, so it has no table, so §9.5.1's "a zero is returned
/// for the mcd or fd" is its truthful answer to `$fopen`.
pub const file_txt = "// ---- §9.5 file descriptor I/O kernels (lib/backend/file_kernels.zig) ----\n\n" ++
    @embedFile("../file_kernels.zig");

/// §4.5.15 the SPICE limiters, emitted VERBATIM from `limit_kernels.zig` on the
/// same terms. Carried only by a device with an honoured `$limit` call — no unit
/// body can reach them, because `$limit` renders as the identity of its probe
/// there (`cg_limit.zig`'s header says why).
pub const limit_txt = "// ---- §4.5.15 SPICE limiting kernels (lib/backend/limit_kernels.zig) ----\n\n" ++
    @embedFile("../limit_kernels.zig");

/// §4.5.11/§4.5.12 the filter kernels, emitted VERBATIM from `filter_kernels.zig`
/// so the numerics codegen's tests exercise are byte-for-byte the numerics the
/// device runs. Only devices that actually use a filter carry them.
pub const filt_txt = "// ---- §4.5.11/§4.5.12 filter kernels (src/filter_kernels.zig) ----\n\n" ++
    @embedFile("../filter_kernels.zig");

pub const hist_txt =
    \\/// §4.5.7 the delayed value, as the residual sees it: Output(t) = Input(t − td).
    \\///
    \\/// Two edges are decided HERE rather than by the ring scan below:
    \\///
    \\///  · dt ≤ 0 is a static analysis — "In DC and operating point analyses,
    \\///    absdelay() returns the value of its input" — so `vin` passes through,
    \\///    derivative and all, exactly like `zTransition`'s DC branch.
    \\///  · a td SHORTER than the step the host just took queries past the newest
    \\///    accepted sample. The only data covering (ts[newest], now] is the
    \\///    CURRENT in-flight value, so the answer interpolates between the newest
    \\///    sample and `vin` — the same linear reading `zHistAt` applies inside
    \\///    the history. That keeps the output continuous in t and carries the
    \\///    f·∂vin derivative the td → 0 (identity) limit requires. The scan used
    \\///    to fall through to the newest sample here, which silently stretched
    \\///    every delay shorter than a step to the step itself. (Clamping was the
    \\///    other candidate; it answers a PAST query with a value from the wrong
    \\///    time and keeps the Jacobian blind to an input the output already
    \\///    partially tracks, so interpolation is the sound choice.)
    \\///
    \\/// Inside the history the delayed value has no dependence on the current
    \\/// unknowns, so it is injected as a constant (derivative 0) — the correct
    \\/// companion model for a pure transport delay. The f ≤ 1 clamp covers a
    \\/// runtime-negative td, which lowering rejects where it can fold.
    \\fn zAbsdelay(comptime S: type, vin: S, ts: []const f64, vs: []const f64, head: u32, now: f64, dt: f64, td: f64) S {
    \\    if (dt <= 0.0) return vin;
    \\    // §4.5.15 "no state history prior to time t == 0": nothing has been
    \\    // accepted yet, so the input IS the output. The ring used to be SEEDED
    \\    // full on the first push, which made this unreachable; `head` is a
    \\    // count now, so the empty ring has to answer for itself.
    \\    if (head == 0) return vin;
    \\    const t = now - td;
    \\    const newest = (head + ts.len - 1) % ts.len;
    \\    if (t > ts[newest]) {
    \\        const span = now - ts[newest];
    \\        if (span <= 0.0) return vin;
    \\        const f = @min((t - ts[newest]) / span, 1.0);
    \\        return vin.scale(f).addC(vs[newest] * (1.0 - f));
    \\    }
    \\    return S.con(zHistAt(ts, vs, head, t));
    \\}
    \\/// §4.5.7 absdelay history: a fixed ring of (t, v) samples, linearly
    \\/// interpolated. `head` is the TOTAL number of accepted samples pushed, not
    \\/// a wrapped index — the ring slot is `head % n`. That one extra fact is
    \\/// what separates the two queries that used to answer the same way: a
    \\/// query before recorded history began, which §4.5.15 settles ("all analog
    \\/// operators are considered to have no state history prior to time t == 0")
    \\/// and `Output(t) = Input(max(t − td, 0))` answers with Input(0); and a
    \\/// query the ring has FORGOTTEN, which the clause settles not at all.
    \\fn zHistAt(ts: []const f64, vs: []const f64, head: u32, t: f64) f64 {
    \\    const n: u32 = @intCast(ts.len);
    \\    const wrapped = head > n;
    \\    const oldest: usize = if (wrapped) head % n else 0;
    \\    // O(1) for a query at or before the oldest sample — the scan would walk
    \\    // all n entries to reach the same answer.
    \\    if (t <= ts[oldest]) {
    \\        // Before the first sample the operator HAS no history, and Input(0)
    \\        // is the value the formula's max(t − td, 0) floor asks for.
    \\        if (!wrapped) return vs[oldest];
    \\        // Older than the whole ring. There is no honest answer here: the
    \\        // clause bounds no lookback, so shortening the delay to whatever the
    \\        // ring still holds is not an implementation-defined limit, it is a
    \\        // different transport delay reported as this one. This used to
    \\        // `return vs[head]` and say nothing.
    \\        @panic("VerA: absdelay history underrun — td spans more accepted timepoints than " ++
    \\            "the per-site history ring holds (codegen.hist_len); the host must take " ++
    \\            "fewer, larger steps across the delay");
    \\    }
    \\    var i: u32 = 0;
    \\    var newer: usize = (head + n - 1) % n;
    \\    while (i < n) : (i += 1) {
    \\        const older = (newer + n - 1) % n;
    \\        if (ts[older] <= t and t <= ts[newer]) {
    \\            const span = ts[newer] - ts[older];
    \\            if (span <= 0.0) return vs[newer];
    \\            const f = (t - ts[older]) / span;
    \\            return vs[older] + (vs[newer] - vs[older]) * f;
    \\        }
    \\        newer = older;
    \\    }
    \\    // Unreachable for a monotone ring: the clamp above covers t ≤ oldest and
    \\    // `zAbsdelay` covers t > newest, so every remaining t is bracketed.
    \\    return vs[(head + n - 1) % n];
    \\}
    \\fn zHistPush(ts: []f64, vs: []f64, head: *u32, t: f64, v: f64) void {
    \\    const n: u32 = @intCast(ts.len);
    \\    ts[head.* % n] = t;
    \\    vs[head.* % n] = v;
    \\    // Saturating, not wrapping: `head` is a COUNT and zHistAt reads
    \\    // `head > n` as "the ring has overwritten its oldest sample". Letting it
    \\    // wrap at 2^32 accepted steps would read as an empty history.
    \\    if (head.* != ~@as(u32, 0)) head.* += 1;
    \\}
;

// ---- the `u/<key>.zig` file-scope prologue (see `Output.prelude`) ----------
//
// A unit file is a separate Zig FILE, so device.zig's file-scope helpers are
// not in its scope and Zig has no textual include. These blocks ALIAS them —
// one declaration for `zig` to analyse, versus one copy per unit if the helper
// text were re-emitted, which would multiply exactly the AstGen + Sema work the
// split exists to remove. `..` is the work_dir: `u/<key>.zig` sits one level
// under `device.zig`, which is the module root.
//
// They are DERIVED from the helper text by `aliasesOf`, so there is nothing to
// keep in sync: a helper that is emitted is aliased, by construction.

pub const helpers_head_txt =
    \\// GENERATED BY VerA — DO NOT EDIT.
    \\// The §4.3/§4.5 kernels, public so `u/<key>.zig` can alias them. device.zig
    \\// carries the same text privately: it must stay a valid stand-alone device.
    \\const std = @import("std");
    \\const contract = @import("contract");
    \\
    \\
;

pub const prelude_head_txt =
    \\// GENERATED BY VerA — DO NOT EDIT.
    \\const std = @import("std");
    \\const contract = @import("contract");
    \\const dev = @import("../device.zig");
    \\const h = @import("../h.zig");
    \\const U = dev.U;
    \\const Model = dev.Model;
    \\const Instance = dev.Instance;
    \\const InstancePtr = contract.InstancePtr(dev);
    \\const AnalysisKind = dev.AnalysisKind;
    \\const n_u = contract.nU(dev);
    \\
;

/// The `z*` helpers `src` publishes, aliased for a unit file: `const zFoo = h.zFoo;`.
///
/// DERIVED, not written out. The hand-written list this replaces drifted
/// silently: a new `fn zFoo` in `ops_txt` compiles into device.zig and leaves
/// every unit file naming a decl that is not in scope there — and only for the
/// models that happen to use it.
///
/// A line is a top-level declaration by the same predicate `publish` applies
/// (`fn ` or `const `), plus the `pub ` form, because the `@embedFile` blocks
/// (`str_kernels.zig` and friends) arrive already public and `publish` leaves
/// them alone. The name must then be `z` + an UPPERCASE letter: that is the
/// spelling of every helper an emitted body calls, and it is what keeps a
/// kernel's own internals (`zstd`, `zfIo`, `zf_max`, `ZScan`) out of the
/// prologue — none is ever named by generated code, and all four were omitted
/// from the hand list for that reason. Dropping the clause is legal and
/// unreferenced, but it changes the emitted bytes for no gain.
pub fn aliasesOf(comptime src: []const u8) []const u8 {
    comptime {
        // ponytail: a CEILING, not a measurement — the longest block is
        // file_kernels.zig at ~440 lines and this is two orders above it.
        @setEvalBranchQuota(100_000);
        var out: []const u8 = "";
        var it = std.mem.splitScalar(u8, src, '\n');
        while (it.next()) |line| {
            const decl = if (std.mem.startsWith(u8, line, "pub ")) line[4..] else line;
            const at: usize = if (std.mem.startsWith(u8, decl, "fn "))
                "fn ".len
            else if (std.mem.startsWith(u8, decl, "const "))
                "const ".len
            else
                continue;
            const rest = decl[at..];
            var n: usize = 0;
            while (n < rest.len and (std.ascii.isAlphanumeric(rest[n]) or rest[n] == '_')) n += 1;
            const name = rest[0..n];
            if (name.len < 2 or name[0] != 'z' or !std.ascii.isUpper(name[1])) continue;
            out = out ++ "const " ++ name ++ " = h." ++ name ++ ";\n";
        }
        return out;
    }
}

pub const prelude_math_txt = aliasesOf(math_txt ++ ops_txt);
pub const prelude_timer_txt = aliasesOf(timer_txt);
pub const prelude_hist_txt = aliasesOf(hist_txt);
pub const prelude_filt_txt = aliasesOf(filt_txt);

/// §9.4.3 `%<width>d`. Aliased whenever `display_txt` is emitted, which is a
/// printing artifact OR any device that formats into a string (§9.5.3 runs the
/// same formatter, and its call site can be in any unit, not just the display
/// one).
pub const prelude_display_txt = aliasesOf(display_txt);

/// §9.21. `zTabRes` is a type function, so it is aliased on the same terms as a
/// function — the recursion's return type names it.
pub const prelude_table_txt = aliasesOf(table_txt);
pub const prelude_rng_txt = aliasesOf(rng_txt);
pub const prelude_file_txt = aliasesOf(file_txt);
pub const prelude_str_txt = aliasesOf(str_txt);

/// Plain-f64 instantiation of the scalar interface. `updateState` has to run a
/// unit body on the accepted solution, where derivatives are meaningless.
/// §9.4.3 support, emitted ONLY into the printing artifact (`display == .emit`).
///
/// `std.fmt` writes `+42` for `{d:>5}`: once a width fixes the field, it spells
/// the sign. §9.4.3 — and C's `%5d`, and every other Verilog tool — writes
/// ` 42`. Padding the rendered DECIMAL rather than the integer gets that back,
/// and `{s:>5}` has no opinion about signs.
///
// ponytail: 24 bytes is i64's widest decimal (20 chars) plus slack, so the
// `catch unreachable` cannot fire. Zero-padding a NEGATIVE number still yields
// `00-42` where C yields `-0042`; nothing in the corpus writes `%05d` on a
// negative, and fixing it means reimplementing the sign placement here.
pub const display_txt =
    \\fn zPadInt(buf: []u8, v: i64) []const u8 { // §9.4.3 %<width>d
    \\    return std.fmt.bufPrint(buf, "{d}", .{v}) catch unreachable;
    \\}
    \\
    \\/// §9.7 simulation control: the run ends here. Declared `f64` and not
    \\/// `noreturn` ON PURPOSE: statements after a §9.7.3 `$fatal` are legal
    \\/// dead code (exhaustive/011 writes `$finish; $stop;` after one), and a
    \\/// noreturn-typed call site would make Zig refuse the block for
    \\/// unreachable code. The value is never produced.
    \\fn zHalt(code: u8) f64 {
    \\    std.process.exit(code);
    \\}
    \\
;

pub const pscalar_txt =
    \\/// Value-only scalar for `precompute`, mirroring the ARPice host Dual's
    \\/// VALUE semantics op for op (gompute.math forwards to the builtins on
    \\/// the host): div is a*(1/b), abs/min/max/minC/maxC branch, expm1/log1p
    \\/// are the Kahan corrections over exp/log. R (plain a/b, device-routed
    \\/// expm1) is deliberately NOT reused: updateState keeps R, so accepted-state
    \\/// bits do not move; eval keeps the host's S, so a field read must
    \\/// reproduce the host chain it replaced bit for bit.
    \\const P = struct {
    \\    v: f64,
    \\    const T = @This();
    \\    pub fn con(c: f64) T { return .{ .v = c }; }
    \\    pub fn val(a: T) f64 { return a.v; }
    \\    pub fn ddxAt(_: T, _: usize) f64 { return 0.0; }
    \\    pub fn add(a: T, b: T) T { return .{ .v = a.v + b.v }; }
    \\    pub fn sub(a: T, b: T) T { return .{ .v = a.v - b.v }; }
    \\    pub fn neg(a: T) T { return .{ .v = -a.v }; }
    \\    pub fn mul(a: T, b: T) T { return .{ .v = a.v * b.v }; }
    \\    pub fn div(a: T, b: T) T { return .{ .v = a.v * (1.0 / b.v) }; }
    \\    pub fn scale(a: T, c: f64) T { return .{ .v = a.v * c }; }
    \\    pub fn addC(a: T, c: f64) T { return .{ .v = a.v + c }; }
    \\    pub fn exp(a: T) T { return .{ .v = @exp(a.v) }; }
    \\    pub fn log(a: T) T { return .{ .v = @log(a.v) }; }
    \\    pub fn expm1(a: T) T {
    \\        const u = @exp(a.v);
    \\        if (u == 1.0) return .{ .v = a.v };
    \\        if (u - 1.0 == -1.0) return .{ .v = -1.0 };
    \\        return .{ .v = (u - 1.0) * a.v / @log(u) };
    \\    }
    \\    pub fn log1p(a: T) T {
    \\        const u = 1.0 + a.v;
    \\        return .{ .v = if (u == 1.0) a.v else @log(u) * (a.v / (u - 1.0)) };
    \\    }
    \\    pub fn sqrt(a: T) T { return .{ .v = @sqrt(a.v) }; }
    \\    pub fn sin(a: T) T { return .{ .v = @sin(a.v) }; }
    \\    pub fn cos(a: T) T { return .{ .v = @cos(a.v) }; }
    \\    pub fn tanh(a: T) T { return .{ .v = std.math.tanh(a.v) }; }
    \\    pub fn sinh(a: T) T { return .{ .v = std.math.sinh(a.v) }; }
    \\    pub fn cosh(a: T) T { return .{ .v = std.math.cosh(a.v) }; }
    \\    pub fn atan(a: T) T { return .{ .v = std.math.atan(a.v) }; }
    \\    pub fn abs(a: T) T { return if (a.v < 0) .{ .v = -a.v } else a; }
    \\    pub fn minC(a: T, c: f64) T { return if (a.v > c) .{ .v = c } else a; }
    \\    pub fn maxC(a: T, c: f64) T { return if (a.v < c) .{ .v = c } else a; }
    \\    pub fn min(a: T, b: T) T { return if (a.v <= b.v) a else b; }
    \\    pub fn max(a: T, b: T) T { return if (a.v >= b.v) a else b; }
    \\    pub fn pow(a: T, c: f64) T { return .{ .v = std.math.pow(f64, a.v, c) }; }
    \\    pub fn lt(a: T, b: T) T { return .{ .v = @floatFromInt(@intFromBool(a.v < b.v)) }; }
    \\    pub fn le(a: T, b: T) T { return .{ .v = @floatFromInt(@intFromBool(a.v <= b.v)) }; }
    \\    pub fn eq(a: T, b: T) T { return .{ .v = @floatFromInt(@intFromBool(a.v == b.v)) }; }
    \\    pub fn sel(c: T, a: T, b: T) T { return if (c.v != 0.0) a else b; }
    \\};
    \\
    \\
;

pub const rscalar_txt =
    \\/// Value-only scalar: `updateState` runs unit bodies on the accepted
    \\/// solution, where no derivative is wanted.
    \\const R = struct {
    \\    v: f64,
    \\    const T = @This();
    \\    pub fn con(c: f64) T { return .{ .v = c }; }
    \\    pub fn val(a: T) f64 { return a.v; }
    \\    pub fn ddxAt(_: T, _: usize) f64 { return 0.0; }
    \\    pub fn add(a: T, b: T) T { return .{ .v = a.v + b.v }; }
    \\    pub fn sub(a: T, b: T) T { return .{ .v = a.v - b.v }; }
    \\    pub fn neg(a: T) T { return .{ .v = -a.v }; }
    \\    pub fn mul(a: T, b: T) T { return .{ .v = a.v * b.v }; }
    \\    pub fn div(a: T, b: T) T { return .{ .v = a.v / b.v }; }
    \\    pub fn scale(a: T, c: f64) T { return .{ .v = a.v * c }; }
    \\    pub fn addC(a: T, c: f64) T { return .{ .v = a.v + c }; }
    \\    // Transcendentals via zDev* (math_txt): this type also compiles in
    \\    // the GPU StateKernel, where the raw builtins have no libcall. The
    \\    // host branch of each IS the builtin — host output is unchanged.
    \\    pub fn exp(a: T) T { return .{ .v = zDevExp(a.v) }; }
    \\    pub fn log(a: T) T { return .{ .v = zDevLog(a.v) }; }
    \\    pub fn expm1(a: T) T { return .{ .v = zDevExpm1(a.v) }; }
    \\    pub fn log1p(a: T) T { return .{ .v = std.math.log1p(a.v) }; }
    \\    pub fn sqrt(a: T) T { return .{ .v = @sqrt(a.v) }; }
    \\    pub fn sin(a: T) T { return .{ .v = zDevSin(a.v) }; }
    \\    pub fn cos(a: T) T { return .{ .v = zDevCos(a.v) }; }
    \\    pub fn tanh(a: T) T { return .{ .v = zDevTanh(a.v) }; }
    \\    pub fn sinh(a: T) T { return .{ .v = zDevSinh(a.v) }; }
    \\    pub fn cosh(a: T) T { return .{ .v = zDevCosh(a.v) }; }
    \\    pub fn atan(a: T) T { return .{ .v = zDevAtan(a.v) }; }
    \\    pub fn abs(a: T) T { return .{ .v = @abs(a.v) }; }
    \\    pub fn minC(a: T, c: f64) T { return .{ .v = @min(a.v, c) }; }
    \\    pub fn maxC(a: T, c: f64) T { return .{ .v = @max(a.v, c) }; }
    \\    pub fn min(a: T, b: T) T { return .{ .v = @min(a.v, b.v) }; }
    \\    pub fn max(a: T, b: T) T { return .{ .v = @max(a.v, b.v) }; }
    \\    pub fn pow(a: T, c: f64) T { return .{ .v = zDevPow(a.v, c) }; }
    \\    // Contract masks and select (see contract.zig's S notes).
    \\    pub fn lt(a: T, b: T) T { return .{ .v = @floatFromInt(@intFromBool(a.v < b.v)) }; }
    \\    pub fn le(a: T, b: T) T { return .{ .v = @floatFromInt(@intFromBool(a.v <= b.v)) }; }
    \\    pub fn eq(a: T, b: T) T { return .{ .v = @floatFromInt(@intFromBool(a.v == b.v)) }; }
    \\    pub fn sel(c: T, a: T, b: T) T { return .{ .v = if (c.v != 0.0) a.v else b.v }; }
    \\};
    \\
    \\
;
