//! An elaborated design -> the Zig root of its executable.
//!
//! In: a `Run` that `elaborate` returned, and the source it came from. Out:
//! one Zig file whose `main` prints what `vera --run` of that source prints.
//! A design `plan.zig` cannot make native embeds its source and runs the
//! interpreter (`rt.interpret`); the `fallback` reason says why.
const std = @import("std");
const Front = @import("frontend");
const Run = @import("root.zig").Run;

/// What `vera --emit-exe design.v` was given: enough to run the source again.
pub const Embed = struct {
    source: []const u8,
    file_name: []const u8,
    include_dirs: []const []const u8,
    language: Front.token.KeywordSet,
};

pub const Program = struct {
    /// The executable's root module.
    text: []const u8,
    /// Null when the design runs natively; else why it does not.
    fallback: ?[]const u8,
};

/// The root module of `r`'s executable. `r` is read, never run.
pub fn program(arena: std.mem.Allocator, r: *Run, embed: Embed) std.mem.Allocator.Error!Program {
    _ = r;
    const why = "native code generation is not implemented";
    return .{ .text = try interpreted(arena, embed, why), .fallback = why };
}

fn interpreted(arena: std.mem.Allocator, embed: Embed, why: []const u8) std.mem.Allocator.Error![]const u8 {
    var out: std.Io.Writer.Allocating = .init(arena);
    const w = &out.writer;
    w.print(
        \\// GENERATED BY VerA — DO NOT EDIT. {s}
        \\// Not native ({s}): the embedded source runs through the interpreter.
        \\const std = @import("std");
        \\pub fn main(init: std.process.Init) u8 {{
        \\    return @import("sim").rt.interpret(init, .{{ .file_name = "{f}", .language = .{t}, .include_dirs = &.{{
    , .{ embed.file_name, why, std.zig.fmtString(embed.file_name), embed.language }) catch return error.OutOfMemory;
    for (embed.include_dirs) |d| w.print(" \"{f}\",", .{std.zig.fmtString(d)}) catch return error.OutOfMemory;
    w.print(" }} }}, \"{f}\");\n}}\n", .{std.zig.fmtString(embed.source)}) catch return error.OutOfMemory;
    return out.written();
}
