const std = @import("std");
const Token = @This();

tag: Tag,
start: u32,
end: u32,

pub fn slice(self: Token, source: []const u8) []const u8 {
    return source[self.start..self.end];
}

pub fn len(self: Token) u32 {
    return self.end - self.start;
}

/// What the token list stores: 5 bytes/token. `end` is recomputed by
/// re-lexing from `start` on the rare text reads (Zig-compiler pattern).
pub const Stored = struct {
    tag: Tag,
    start: u32,
};

pub const Tag = enum(u8) {
    // ── Literals ──────────────────────────────────────────────────────
    int_literal,
    real_literal,
    si_real_literal,
    string_literal,
    // ── Identifiers ───────────────────────────────────────────────────
    identifier,
    escaped_identifier,
    system_identifier,
    // ── Keywords ──────────────────────────────────────────────────────
    kw_module,
    kw_endmodule,
    kw_analog,
    kw_begin,
    kw_end,
    kw_if,
    kw_else,
    kw_for,
    kw_while,
    kw_case,
    kw_endcase,
    kw_default,
    kw_parameter,
    kw_localparam,
    kw_aliasparam,
    kw_real,
    kw_integer,
    kw_string,
    kw_input,
    kw_output,
    kw_inout,
    kw_branch,
    kw_discipline,
    kw_enddiscipline,
    kw_nature,
    kw_endnature,
    kw_function,
    kw_endfunction,
    kw_from,
    kw_exclude,
    kw_inf,
    kw_initial_step,
    kw_final_step,
    kw_disable,
    kw_ground,
    kw_generate,
    kw_genvar,
    kw_electrical,
    kw_potential,
    kw_flow,
    kw_domain,
    kw_discrete,
    kw_continuous,
    kw_abstol,
    kw_access,
    kw_idt_nature,
    kw_ddt_nature,
    kw_units,
    kw_thermal,
    kw_ifdef,
    kw_endif,
    kw_else_directive,
    kw_define,
    kw_paramset,
    kw_endparamset,
    kw_endgenerate,
    // ── Punctuation ───────────────────────────────────────────────────
    semicolon,
    comma,
    dot,
    colon,
    at_sign,
    hash,
    question,
    l_paren,
    r_paren,
    l_brace,
    r_brace,
    l_bracket,
    r_bracket,
    // ── Operators ─────────────────────────────────────────────────────
    eq,
    eq2,
    neq,
    lt,
    gt,
    lte,
    gte,
    plus,
    minus,
    star,
    slash,
    percent,
    pow,
    amp,
    pipe,
    caret,
    tilde,
    bang,
    amp2,
    pipe2,
    shl,
    shr,
    ashl,
    ashr,
    nxor_l,
    nxor_r,
    contribute,
    // ── Attributes ────────────────────────────────────────────────────
    attr_open,
    attr_close,
    arr_start,
    // ── Special ───────────────────────────────────────────────────────
    eof,
    invalid,

    pub fn isKeyword(self: Tag) bool {
        return @intFromEnum(self) >= @intFromEnum(Tag.kw_module) and
            @intFromEnum(self) <= @intFromEnum(Tag.kw_endgenerate);
    }
};

pub const keyword_map = std.StaticStringMap(Tag).initComptime(.{
    .{ "module", .kw_module },
    .{ "endmodule", .kw_endmodule },
    .{ "analog", .kw_analog },
    .{ "begin", .kw_begin },
    .{ "end", .kw_end },
    .{ "if", .kw_if },
    .{ "else", .kw_else },
    .{ "for", .kw_for },
    .{ "while", .kw_while },
    .{ "case", .kw_case },
    .{ "endcase", .kw_endcase },
    .{ "default", .kw_default },
    .{ "parameter", .kw_parameter },
    .{ "localparam", .kw_localparam },
    .{ "aliasparam", .kw_aliasparam },
    .{ "real", .kw_real },
    .{ "integer", .kw_integer },
    .{ "string", .kw_string },
    .{ "input", .kw_input },
    .{ "output", .kw_output },
    .{ "inout", .kw_inout },
    .{ "branch", .kw_branch },
    .{ "discipline", .kw_discipline },
    .{ "enddiscipline", .kw_enddiscipline },
    .{ "nature", .kw_nature },
    .{ "endnature", .kw_endnature },
    .{ "function", .kw_function },
    .{ "endfunction", .kw_endfunction },
    .{ "from", .kw_from },
    .{ "exclude", .kw_exclude },
    .{ "inf", .kw_inf },
    .{ "initial_step", .kw_initial_step },
    .{ "final_step", .kw_final_step },
    .{ "disable", .kw_disable },
    .{ "ground", .kw_ground },
    .{ "generate", .kw_generate },
    .{ "genvar", .kw_genvar },
    .{ "electrical", .kw_electrical },
    .{ "potential", .kw_potential },
    .{ "flow", .kw_flow },
    .{ "domain", .kw_domain },
    .{ "discrete", .kw_discrete },
    .{ "continuous", .kw_continuous },
    .{ "abstol", .kw_abstol },
    .{ "access", .kw_access },
    .{ "idt_nature", .kw_idt_nature },
    .{ "ddt_nature", .kw_ddt_nature },
    .{ "units", .kw_units },
    .{ "thermal", .kw_thermal },
    .{ "paramset", .kw_paramset },
    .{ "endparamset", .kw_endparamset },
    .{ "endgenerate", .kw_endgenerate },
});
