//! The Zig text `compileRelease` and `buildEngine` write next to a device:
//! each artifact's root file (`shim*.zig`, `vera_engine_*.zig`), which binds
//! the device to the host's `dyn` module. Build options in, source text out.
//! Every byte here reaches a `zig` child and is frozen: the goldens
//! (`--emit-zig`) cover the device only, never this text.

const std = @import("std");
const Allocator = std.mem.Allocator;
const Part = @import("../orchestrator.zig").Part;

/// Returns the `shim_<piece>.zig` file name of a split build's piece.
pub fn fileName(arena: Allocator, piece: []const u8) ![]const u8 {
    return arena.print("shim_{s}.zig", .{piece});
}

/// Returns the dyn-ABI export shim, which re-exports the device under the
/// host's C ABI. It depends only on `name` and whether `engine` is linked,
/// so rebuilds never dirty it. Caller owns the text and frees it with `gpa`.
pub fn device(gpa: Allocator, name: []const u8, engine: bool) ![]u8 {
    return gpa.print(
        \\// GENERATED BY VerA — DO NOT EDIT.
        \\{s}comptime {{
        \\    @import("dyn").exportDevice(@import("device"), "{s}");
        \\}}
        \\
    , .{ rootDecls(engine), name });
}

/// The shim's root declarations: the `dyn` host's opt-in to the contract's
/// conformance checks, forwarded because the shim, not `dyn`, is the root
/// `contract.validating` reads; and, with `engine`, the one that makes
/// `sim`'s runtime call the linked engine object (`rt.prebuilt`).
fn rootDecls(engine: bool) []const u8 {
    const validate =
        "pub const vera_validate_contract = @hasDecl(@import(\"dyn\"), \"vera_validate_contract\") and " ++
        "@import(\"dyn\").vera_validate_contract;\n";
    return if (engine) validate ++ "pub const vera_prebuilt_engine = {};\n" else validate;
}

/// The root of one part's object: the host's `exportDevicePart` for that
/// part, or, for a host without one, its `exportDevice` in the setup object
/// and nothing in the others. With `chunks` (a `setup` emitted as chunks),
/// every part calls the chunks through their objects (`chunk`)
/// when the host names its value scalar. Allocated in `arena`.
pub fn part(arena: Allocator, name: []const u8, which: Part, engine: bool, chunks: bool) ![]u8 {
    const head = try std.mem.concat(arena, u8, &.{ rootDecls(engine), if (chunks) setup_split_decl else "" });
    return if (which == .setup) arena.print(
        \\// GENERATED BY VerA — DO NOT EDIT.
        \\{1s}comptime {{
        \\    const dyn = @import("dyn");
        \\    if (@hasDecl(dyn, "exportDevicePart"))
        \\        dyn.exportDevicePart(@import("device"), "{0s}", .setup)
        \\    else
        \\        dyn.exportDevice(@import("device"), "{0s}");
        \\}}
        \\
    , .{ name, head }) else arena.print(
        \\// GENERATED BY VerA — DO NOT EDIT.
        \\{s}comptime {{
        \\    const dyn = @import("dyn");
        \\    if (@hasDecl(dyn, "exportDevicePart")) dyn.exportDevicePart(@import("device"), "{s}", .{t});
        \\}}
        \\
    , .{ head, name, which });
}

/// A split build's parts call `setup`'s chunks through the chunk objects
/// exactly when the chunk objects export them: when the host names the
/// value scalar it passes `setup` (`contract.DevicePart`).
const setup_split_decl = "pub const vera_setup_split = @hasDecl(@import(\"dyn\"), \"SetupValue\");\n";

/// The root of setup chunk `k`'s object: the chunk, for the host's value
/// scalar, or nothing for a host that does not name one. Allocated in `arena`.
pub fn chunk(arena: Allocator, k: u32, engine: bool) ![]u8 {
    return arena.print(
        \\// GENERATED BY VerA — DO NOT EDIT.
        \\{s}{s}comptime {{
        \\    const dyn = @import("dyn");
        \\    const D = @import("device");
        \\    if (@hasDecl(dyn, "SetupValue")) D.setup_chunks.exportChunk(dyn.SetupValue(D), {d});
        \\}}
        \\
    , .{ rootDecls(engine), setup_split_decl, k });
}

/// The root of the engine object: `sim`'s runtime, with no root options
/// (a device's shim declares none).
pub const engine_root =
    \\// GENERATED BY VerA — DO NOT EDIT.
    \\comptime {
    \\    @import("sim").rt.engine.exportAll();
    \\}
    \\
;
