#!/usr/bin/env python3
"""Read licensed local IEEE Annex G and enumerate its public declarations.

Output is a declaration inventory, not a runtime conformance score. Comments
are removed before extraction; commented duplicate defines are not obligations.
"""
import argparse
import hashlib
import pathlib
import re
import subprocess

PDF_SHA = "3bebc696d5a338dbfa6925c9ffdeccc6de745e703abae8af84dd8f5551fe0a9e"


def clean(text):
    return re.sub(r"/\*.*?\*/", "", text, flags=re.S)


def normalize(text):
    return re.sub(r"\s+", "", text)


def macros(text):
    return re.findall(r"^\s*#define[ \t]+(\w+(?:\([^\n]*?\))?)[ \t]*([^\n]*)", text, re.M)


def render(pdf, header):
    if hashlib.sha256(pdf.read_bytes()).hexdigest() != PDF_SHA:
        raise ValueError("unexpected IEEE PDF: review source edition before inventory")
    source = subprocess.run(["pdftotext", "-layout", "-f", "552", "-l", "566",
                             str(pdf), "-"], check=True, capture_output=True, text=True).stdout
    pages = source.split("\f")
    # Preserve page mapping while removing running headers/footers.
    source = "\n".join("\n".join(line for line in page.splitlines()
                                if not re.search(r"Copyright|Authorized licensed|HARDWARE DESCRIPTION|IEEE STANDARD|Std 1364|^\s*(?:IEEE|\d+)\s*$", line))
                       for page in pages)
    source = clean(source)
    current = clean(header.read_text())
    print("# IEEE Annex G symbol-level header inventory\n")
    print(f"Source SHA256 `{PDF_SHA}`; printed522–536.\n")
    print(f"Header SHA256 `{hashlib.sha256(header.read_bytes()).hexdigest()}`.\n")
    print("Generated by tools/inventory_vpi_annex_g.py. Presence is not type, ABI, or runtime proof.\n")
    print("## Macro definitions\n\nConditional definitions retain every alternative; empty helpers may be cleaned up at end of header. No preprocessor evaluation is claimed.\n")
    print("| Symbol | Source replacement | Header comparison |\n|---|---|---|")
    actual = dict(macros(current))
    seen = set()
    for name, value in macros(source):
        if (name, value) in seen:
            continue
        seen.add((name, value))
        state = "absent" if name not in actual else ("same replacement" if normalize(value) == normalize(actual[name]) else "different replacement")
        print(f"| `{name}` | `{value.strip().replace('|', '&#124;') or '(empty)'}` | {state} |")
    print("\n## Typedefs, tags and members\n\nMember presence does not check declaration order or compatible types. Known mismatches are recorded in the review.\n")
    print("| Symbol | Header comparison |\n|---|---|")
    emitted = set()
    def row(name, scope=None):
        if name in emitted:
            raise ValueError(f"duplicate symbol row {name}")
        emitted.add(name)
        token = name.rsplit(".", 1)[-1]
        target = current if scope is None else scope
        print(f"| `{name}` | {'present; type review required' if re.search(r'\b' + re.escape(token) + r'\b', target) else 'absent'} |")
    for scalar in re.findall(r"typedef\s+(?!struct\b)[^;{}]+?\b(\w+)\s*;", source):
        row(scalar)
    struct_pattern = r"typedef\s+struct\s+(\w+)\s*\{(.*?)\}\s*(s_\w+)\s*,\s*\*(p_\w+)\s*;"
    for tag, body, alias, pointer in re.findall(struct_pattern, source, re.S):
        for name in (tag, alias, pointer):
            row(name)
        root_match = re.search(r"typedef\s+struct\s+" + tag + r"\s*\{(.*?)\}\s*" + alias, current, re.S)
        root_body = root_match.group(1) if root_match else ""
        union = False
        for decl in body.split(";"):
            decl = decl.strip()
            if not decl:
                continue
            if "union" in decl:
                union = True
                decl = decl.split("{", 1)[1]
            if "}" in decl:
                union = False
                decl = decl.rsplit("}", 1)[1]
            function = re.search(r"\(\s*\*\s*(\w+)\s*\)", decl)
            members = [function.group(1)] if function else [re.search(r"(\w+)\s*$", item).group(1) for item in decl.split(",")]
            for member in members:
                row(alias + (".value." if union else ".") + member, root_body)
    print("\n## Function and global declarations\n\nFunction rows establish declaration presence only; the by-name signature discrepancy is independently compile-tested.\n")
    print("| Symbol | Header comparison |\n|---|---|")
    for name in re.findall(r"\b(vpi_\w+)\s+PROTO_PARAMS\s*\(", source):
        row(name)
    row("vlog_startup_routines")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("pdf", type=pathlib.Path)
    parser.add_argument("header", type=pathlib.Path)
    args = parser.parse_args()
    render(args.pdf, args.header)
