#!/usr/bin/env python3
"""Audit Table B.1 against the PDF; emit exhaustive spelling fixtures to stdout.

This checks the spelling inventory, not implementation of keyword constructs
or every grammar position. No compiler token table is used as the oracle.
"""

import argparse
import hashlib
from html.parser import HTMLParser
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SOURCE_SHA256 = "e93b5b6a767fe10e0e4a3ef312ffdc67907ffcc3c7553d16e04e03383a99c134"


class KeywordTable(HTMLParser):
    def __init__(self):
        super().__init__()
        self.in_table = False
        self.in_code = False
        self.words = []

    def handle_starttag(self, tag, attrs):
        if tag == "table":
            self.in_table = True
        if tag == "code":
            self.in_code = True

    def handle_endtag(self, tag):
        if tag == "table":
            self.in_table = False
        if tag == "code":
            self.in_code = False

    def handle_data(self, data):
        if self.in_table and self.in_code:
            self.words.extend(data.split())


def keywords():
    pdf = ROOT / "docs/VAMS-LRM-2023.pdf"
    if hashlib.sha256(pdf.read_bytes()).hexdigest() != SOURCE_SHA256:
        raise ValueError("Source PDF changed: re-audit Table B.1 pages and correction")
    source = subprocess.run([
        "pdftotext", "-f", "400", "-l", "401", "-layout",
        str(pdf), "-",
    ], check=True, capture_output=True, text=True).stdout
    words = []
    for line in source.splitlines():
        if re.fullmatch(r"\s*[a-z][a-z_0-9]*(?:\s+[a-z][a-z_0-9]*){0,2}\s*", line):
            words.extend(line.split())
    # Visually confirmed source-table defect, also labeled in the HTML.
    if words.count("negedgenmos") != 1:
        raise ValueError("Source table changed: re-audit the negedgenmos correction")
    words.remove("negedgenmos")
    words.extend(["negedge", "nmos"])
    if len(words) != len(set(words)):
        raise ValueError("Duplicate source keyword")
    html = KeywordTable()
    html.feed((ROOT / "docs/annex-b-keywords.html").read_text())
    if len(html.words) != len(set(html.words)):
        raise ValueError("Duplicate HTML keyword")
    if set(words) != set(html.words):
        raise ValueError(f"PDF-only: {set(words) - set(html.words)}; "
                         f"HTML-only: {set(html.words) - set(words)}")
    return sorted(words)


def fixture(words, mode):
    entries = []
    for word in words:
        if mode == "escaped":
            entries.append(("\\" + word + " ", "escaped " + word))
        else:
            entries.extend([(word.upper(), "uppercase " + word),
                            (word[0].upper() + word[1:], "initial-uppercase " + word)])
    lines = [
        "// Generated by tools/lrm_keywords.py --fixture " + mode,
        "// Source: VAMS-2023 Table B.1, physical pages 400-401;",
        "// the PDF's negedgenmos defect is split into negedge and nmos.",
        "// Annex B and 2.8.2 reserve nonescaped lowercase spellings only.",
        "// Each legal identifier is assigned its one-based inventory position.",
        "// All assignments precede all observations: name aliasing cannot hide",
        "// behind an immediate assignment/read pair. Each expected integer is",
        "// independently fixed by the generator, not read from the compiler.",
        "// This tests variable identifiers, not all identifier grammar positions.",
        "// Reads use a plain temporary so macro-argument whitespace processing",
        "// cannot hide the keyword-name test; see KEY-MACRO-001 in the audit.",
        "//! lrm B", "//! lrm 2.8.2", f"//! checks {len(entries)}", "//! print none",
        '`include "check.vh"', f"module audit_all_{mode}_keywords(p, n);",
        "    inout p, n;", "    electrical p, n;",
    ]
    lines += [f"    real {name};" for name, _ in entries]
    lines += ["    real observed;"]
    lines += ["    analog begin"]
    lines += [f"        {name} = {i}.0;" for i, (name, _) in enumerate(entries, 1)]
    for i, (name, label) in enumerate(entries, 1):
        lines += [f"        observed = {name};",
                  f'        `CHECKX("{label}", observed, {i}.0);']
    lines += ["        I(p,n) <+ 0.0;", "    end", "endmodule"]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixture", choices=["escaped", "case"])
    parser.add_argument("--check-fixtures", action="store_true")
    args = parser.parse_args()
    words = keywords()
    if args.fixture:
        print(fixture(words, args.fixture), end="")
        return
    if args.check_fixtures:
        for mode in ["escaped", "case"]:
            path = ROOT / f"tests/fixtures/annex_b_keywords/audit_all_{mode}_keywords.va"
            if path.read_text() != fixture(words, mode):
                raise SystemExit(f"Fixture drift: {path}")
    print(f"Table B.1: {len(words)} distinct corrected spellings; PDF and HTML sets match.")


if __name__ == "__main__":
    main()
