#!/usr/bin/env python3
"""The smallest independently-ownable units of VerA's Zig source.

    tools/units.py > docs/UNITS.md

A unit is a strongly connected component of the file-level `@import` graph
(relative paths, plus `build.zig` module names mapped to their root file):
files that import each other in a cycle cannot change shape apart, and an
acyclic edge between two units is a seam. Units are printed in dependency
order, so a layer's units only depend on earlier layers.

The large units are the sub-file pattern (AGENTS.md §4): a root file owns the
shared type, `self: *T` sub-files hang off it, and they cross-call. Freezing
the files every sibling imports (the hubs: the type and the cross-called
helpers) breaks the cycle; what is left are slices one agent can change as
long as their `pub` signatures and the hubs stay put. A hub is a seam.

`@import`s inside `\\\\` string literals (generated device text) and comments
are not edges.
"""
import collections
import os
import re
import sys

ROOTS = ["lib", "src", "tools"]  # recursively
FLAT = ["tests"]  # top level only: tests/fixtures and tests/vdev are data
BUDGET = 4000  # lines one agent owns: smaller units are not split
MAX_HUBS = 8

os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
mods = dict(re.findall(r'\.name = "(\w+)", \.path = "([^"]+)"', open("build.zig").read()))
files = sorted(
    [os.path.join(dp, f) for r in ROOTS for dp, _, fs in os.walk(r) for f in fs if f.endswith(".zig")]
    + [os.path.join(r, f) for r in FLAT for f in os.listdir(r) if f.endswith(".zig")]
)
fset = set(files)
imp = re.compile(r'@import\("([^"]+)"\)')
G = {f: set() for f in files}
lines = {}
for f in files:
    text = open(f).read().splitlines()
    lines[f] = len(text)
    code = "\n".join("" if l.lstrip().startswith("\\\\") else l.split("//")[0] for l in text)
    for m in imp.findall(code):
        if m.endswith(".zig"):
            t = os.path.normpath(os.path.join(os.path.dirname(f), m))
            if t in fset:
                G[f].add(t)
        elif m in mods:
            G[f].add(mods[m])


def scc(nodes, edges):
    """Tarjan, iterative. Returns components, each sorted."""
    index, low, on, stack, out, n = {}, {}, set(), [], [], 0
    for root in sorted(nodes):
        if root in index:
            continue
        work = [(root, iter(sorted(edges[root] & nodes)))]
        index[root] = low[root] = n; n += 1; stack.append(root); on.add(root)
        while work:
            v, it = work[-1]
            for w in it:
                if w not in index:
                    index[w] = low[w] = n; n += 1; stack.append(w); on.add(w)
                    work.append((w, iter(sorted(edges[w] & nodes))))
                    break
                if w in on:
                    low[v] = min(low[v], index[w])
            else:
                work.pop()
                if work:
                    low[work[-1][0]] = min(low[work[-1][0]], low[v])
                if low[v] == index[v]:
                    c = []
                    while True:
                        w = stack.pop(); on.discard(w); c.append(w)
                        if w == v:
                            break
                    out.append(sorted(c))
    return out


def size(fs):
    return sum(lines[f] for f in fs)


units = scc(fset, G)
uid = {f: i for i, u in enumerate(units) for f in u}
deps = [sorted({uid[w] for f in u for w in G[f]} - {i}) for i, u in enumerate(units)]
layer = {}
for i in range(len(units)):  # Tarjan emits sinks first, so deps are done
    layer[i] = 1 + max((layer[j] for j in deps[i]), default=-1)
order = sorted(range(len(units)), key=lambda i: (layer[i], units[i][0]))
name = {i: f"U{k:02d}" for k, i in enumerate(order)}
users = collections.defaultdict(list)
for i in range(len(units)):
    for j in deps[i]:
        users[j].append(i)


def label(i):
    """A unit is named by the file the rest of the program imports most."""
    u = units[i]
    if len(u) == 1:
        return u[0]
    ext = collections.Counter(w for f in files if uid[f] != i for w in G[f] if uid[w] == i)
    return f"{max(u, key=lambda f: (ext[f], lines[f]))} (+{len(u) - 1})"


def split(u):
    """Peel the most-imported files until the rest falls apart."""
    s = set(u)
    indeg = collections.Counter(w for f in u for w in G[f] if w in s)
    hubs, edges = [], {f: set(G[f]) for f in u}
    while len(hubs) < MAX_HUBS:
        h = max((f for f in u if f not in hubs), key=lambda f: (indeg[f], f))
        hubs.append(h)
        for f in u:
            edges[f].discard(h)
        slices = scc(s - set(hubs), edges)
        if max(map(size, slices)) <= BUDGET:
            break
    return hubs, sorted(slices, key=lambda p: (-size(p), p))


out = sys.stdout.write
out("# Units\n\n")
out("Generated by `tools/units.py`; do not edit. Regenerate after any change to\n")
out("an `@import`. A unit is an import cycle: its files change shape together.\n")
out("`Uses` are seams. Layer N depends only on layers below N.\n\n")
out(f"{len(files)} files, {size(files)} lines, {len(units)} units, "
    f"{sum(len(u) > 1 for u in units)} of them multi-file.\n\n")
out("| Unit | Layer | Lines | Files | Uses | Used by |\n|---|---:|---:|---|---|---|\n")
for i in order:
    out(f"| {name[i]} | {layer[i]} | {size(units[i])} | `{label(i)}` | "
        f"{' '.join(name[j] for j in sorted(deps[i], key=name.get)) or '—'} | "
        f"{' '.join(name[j] for j in sorted(users[i], key=name.get)) or '—'} |\n")

out("\n## Multi-file units\n\n")
out("Hubs are the files every sibling imports: freeze them (they are seams),\n")
out("and each slice below can be owned alone while its `pub` signatures hold.\n")
out("A `test.zig` slice belongs with the unit's root file (tests move with code).\n")
for i in order:
    u = units[i]
    if len(u) < 2:
        continue
    out(f"\n### {name[i]} `{label(i)}`, {size(u)} lines\n\n")
    if size(u) <= BUDGET:
        out("".join(f"- `{f}` {lines[f]}\n" for f in u))
        continue
    hubs, slices = split(u)
    out("".join(f"- hub `{h}` {lines[h]}\n" for h in hubs))
    for p in slices:
        out(f"- slice {size(p)}: " + ", ".join(f"`{f}` {lines[f]}" for f in p) + "\n")

out("\n## Module seams\n\n")
out("`build.zig` module edges, with the files on each side that cross them.\n\n")
mod_root = {v: k for k, v in mods.items()}
module_of = {}  # module name -> files outside its unit that import it
for f in files:
    for w in G[f]:
        if w in mod_root and uid[w] != uid[f]:
            module_of.setdefault(mod_root[w], set()).add(f)
for m in mods:
    if m in module_of:
        users_m = sorted(module_of[m])
        out(f"- `{m}` ({mods[m]}) ← {len(users_m)} files: "
            + ", ".join(f"`{f}`" for f in users_m) + "\n")
