// IEEE 1364-2005 §17.8, pp. 310-311: "The conversion system functions may be
// used in constant expressions, as specified in Clause 5." ... "$rtoi
// Converts real values to integers by truncating the real value (for
// example, 123.45 becomes 123). $itor Converts integers to real values (for
// example, 123 becomes 123.0). $realtobits Passes bit patterns across module
// ports; converts from a real number to the 64-bit representation (vector)
// of that real number. $bitstoreal Is the reverse of $realtobits; converts
// from the bit pattern to a real number. The real numbers accepted or
// generated by these functions shall conform to the IEEE 754 representation
// of the real number."
//
// Hand derivation:
//   $rtoi(123.45) -> 123; $rtoi(-2.7) truncates toward zero -> -2
//   $itor(123) -> 123.0, printed %f as 123.000000
//   1.5 = 1.1b x 2^0: sign 0, exponent 1023 = 0x3FF, fraction 0x8000000000000
//     -> $realtobits(1.5) = 3ff8000000000000; $bitstoreal of it -> 1.5
//   -0.25 = -1.0b x 2^-2: sign 1, exponent 1021 = 0x3FD, fraction 0
//     -> bits bfd0000000000000
//   Constant expressions: parameter P = $rtoi(7.9) -> 7;
//     parameter [63:0] B = $realtobits(0.5): exponent 1022 = 0x3FE -> 3fe0000000000000
//   Across a port, the clause's driver/receiver pattern: the driver puts
//   $realtobits(r) on a 64-bit net, the receiver reads it back with
//   $bitstoreal. The driver sets r = -0.25 at t=1, when the receiver's
//   always block has long been waiting on net_r (no t=0 race), and the top
//   reads the receiver's r at t=2: -0.250000. The clause's example declares
//   the ports without a range (`output net_r;` then `wire [64:1] net_r`);
//   §12.3.3 (p. 174) says "the range specification between the two
//   declarations of a port shall be identical", so here both carry [64:1].
//! inherited IEEE 1364-2005 17.8
`timescale 1 ns / 1 ns
module b_17_8_conversions;
  parameter P = $rtoi(7.9);
  parameter [63:0] B = $realtobits(0.5);
  wire [64:1] net_r;
  real rr;
  b_17_8_conversions_driver d (net_r);
  b_17_8_conversions_receiver rcv (net_r);
  initial begin
    $display("%0d %0d", $rtoi(123.45), $rtoi(-2.7));
    $display("%f", $itor(123));
    $display("%h %f", $realtobits(1.5), $bitstoreal(64'h3ff8000000000000));
    $display("%h", $realtobits(-0.25));
    $display("%0d %h", P, B);
    #2 $display("%f", rcv.r);
    $finish(0);
  end
endmodule

module b_17_8_conversions_driver (net_r);
  output [64:1] net_r;
  real r;
  wire [64:1] net_r = $realtobits(r);
  initial #1 r = -0.25;
endmodule

module b_17_8_conversions_receiver (net_r);
  input [64:1] net_r;
  wire [64:1] net_r;
  real r;
  always @(net_r) r = $bitstoreal(net_r);
endmodule
